# 데이터 불러오기

- 2022년 주유소들의 일자별 가격 데이터
- https://www.opinet.co.kr/user/opdown/opDownload.do

In [10]:
import pandas as pd
# 상반기, 하반기 주유소 가격 데이터 조회
oil1 = pd.read_csv('data/2022년_서울_상반기_일별_가격.csv', encoding='cp949')
oil2 = pd.read_csv('data/2022년_서울_하반기_일별_가격.csv', encoding='cp949')
oil1

,번호,지역,상호,주소,기간,상표,셀프여부,고급휘발유,휘발유,경유,실내등유
0,A0006039,서울 강남구,(유)동하석유 힐탑셀프주유소,서울 강남구 논현로 640,20220101,SK에너지,셀프,1887,1737,1587,0
1,A0006039,서울 강남구,(유)동하석유 힐탑셀프주유소,서울 강남구 논현로 640,20220102,SK에너지,셀프,1887,1737,1587,0
2,A0006039,서울 강남구,(유)동하석유 힐탑셀프주유소,서울 강남구 논현로 640,20220103,SK에너지,셀프,1887,1737,1587,0
3,A0006039,서울 강남구,(유)동하석유 힐탑셀프주유소,서울 강남구 논현로 640,20220104,SK에너지,셀프,1887,1737,1587,0
4,A0006039,서울 강남구,(유)동하석유 힐탑셀프주유소,서울 강남구 논현로 640,20220105,SK에너지,셀프,1887,1737,1587,0
...,...,...,...,...,...,...,...,...,...,...,...
82684,A0009197,서울 중랑구,현대오일뱅크㈜직영 중랑교셀프주유소,서울 중랑구 망우로 229 (중화동),20220507,현대오일뱅크,셀프,2152,1910,1841,0
82685,A0009197,서울 중랑구,현대오일뱅크㈜직영 중랑교셀프주유소,서울 중랑구 망우로 229 (중화동),20220508,현대오일뱅크,셀프,2152,1910,1841,0
82686,A0009197,서울 중랑구,현대오일뱅크㈜직영 중랑교셀프주유소,서울 중랑구 망우로 229 (중화동),20220509,현대오일뱅크,셀프,2152,1910,1841,0
82687,A0009197,서울 중랑구,현대오일뱅크㈜직영 중랑교셀프주유소,서울 중랑구 망우로 229 (중화동),20220510,현대오일뱅크,셀프,2152,1910,1841,0
82688,A0009197,서울 중랑구,현대오일뱅크㈜직영 중랑교셀프주유소,서울 중랑구 망우로 229 (중화동),20220511,현대오일뱅크,셀프,2152,1910,1841,0

In [9]:
oil2

,번호,지역,상호,주소,기간,상표,셀프여부,고급휘발유,휘발유,경유,실내등유
0,A0006039,서울 강남구,(유)동하석유 힐탑셀프주유소,서울 강남구 논현로 640,20220701,SK에너지,셀프,2487,2287,2297,0
1,A0006039,서울 강남구,(유)동하석유 힐탑셀프주유소,서울 강남구 논현로 640,20220702,SK에너지,셀프,2447,2247,2277,0
2,A0006039,서울 강남구,(유)동하석유 힐탑셀프주유소,서울 강남구 논현로 640,20220703,SK에너지,셀프,2447,2247,2277,0
3,A0006039,서울 강남구,(유)동하석유 힐탑셀프주유소,서울 강남구 논현로 640,20220704,SK에너지,셀프,2447,2247,2277,0
4,A0006039,서울 강남구,(유)동하석유 힐탑셀프주유소,서울 강남구 논현로 640,20220705,SK에너지,셀프,2447,2247,2277,0
...,...,...,...,...,...,...,...,...,...,...,...
81788,A0009138,서울 중랑구,우림주유소,서울 중랑구 용마산로 487 (망우제3동),20221227,GS칼텍스,셀프,0,1525,1745,0
81789,A0009138,서울 중랑구,우림주유소,서울 중랑구 용마산로 487 (망우제3동),20221228,GS칼텍스,셀프,0,1525,1720,0
81790,A0009138,서울 중랑구,우림주유소,서울 중랑구 용마산로 487 (망우제3동),20221229,GS칼텍스,셀프,0,1525,1720,0
81791,A0009138,서울 중랑구,우림주유소,서울 중랑구 용마산로 487 (망우제3동),20221230,GS칼텍스,셀프,0,1515,1715,0
81792,A0009138,서울 중랑구,우림주유소,서울 중랑구 용마산로 487 (망우제3동),20221231,GS칼텍스,셀프,0,1515,1715,0

In [13]:
# 상반기, 하반기 DataFrame 합치기
oil = pd.concat([oil1, oil2])
oil

,번호,지역,상호,주소,기간,상표,셀프여부,고급휘발유,휘발유,경유,실내등유
0,A0006039,서울 강남구,(유)동하석유 힐탑셀프주유소,서울 강남구 논현로 640,20220101,SK에너지,셀프,1887,1737,1587,0
1,A0006039,서울 강남구,(유)동하석유 힐탑셀프주유소,서울 강남구 논현로 640,20220102,SK에너지,셀프,1887,1737,1587,0
2,A0006039,서울 강남구,(유)동하석유 힐탑셀프주유소,서울 강남구 논현로 640,20220103,SK에너지,셀프,1887,1737,1587,0
3,A0006039,서울 강남구,(유)동하석유 힐탑셀프주유소,서울 강남구 논현로 640,20220104,SK에너지,셀프,1887,1737,1587,0
4,A0006039,서울 강남구,(유)동하석유 힐탑셀프주유소,서울 강남구 논현로 640,20220105,SK에너지,셀프,1887,1737,1587,0
...,...,...,...,...,...,...,...,...,...,...,...
81788,A0009138,서울 중랑구,우림주유소,서울 중랑구 용마산로 487 (망우제3동),20221227,GS칼텍스,셀프,0,1525,1745,0
81789,A0009138,서울 중랑구,우림주유소,서울 중랑구 용마산로 487 (망우제3동),20221228,GS칼텍스,셀프,0,1525,1720,0
81790,A0009138,서울 중랑구,우림주유소,서울 중랑구 용마산로 487 (망우제3동),20221229,GS칼텍스,셀프,0,1525,1720,0
81791,A0009138,서울 중랑구,우림주유소,서울 중랑구 용마산로 487 (망우제3동),20221230,GS칼텍스,셀프,0,1515,1715,0
81792,A0009138,서울 중랑구,우림주유소,서울 중랑구 용마산로 487 (망우제3동),20221231,GS칼텍스,셀프,0,1515,1715,0

In [18]:
# DataFrame 기본 정보 조회
oil.info()

<class 'pandas.core.frame.DataFrame'>
Index: 164482 entries, 0 to 81792
Data columns (total 11 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   번호      164482 non-null  object
 1   지역      164482 non-null  object
 2   상호      164482 non-null  object
 3   주소      164482 non-null  object
 4   기간      164482 non-null  int64
 5   상표      164482 non-null  object
 6   셀프여부    164482 non-null  object
 7   고급휘발유   164482 non-null  int64
 8   휘발유     164482 non-null  int64
 9   경유      164482 non-null  int64
 10  실내등유    164482 non-null  int64
dtypes: int64(5), object(6)
memory usage: 15.1+ MB

In [16]:
# 상표 컬럼의 고유값 조회
oil['상표'].unique()

array(['SK에너지', 'GS칼텍스', '현대오일뱅크', 'S-OIL', '알뜰주유소', '자가상표', '알뜰(ex)'],
      dtype=object)

In [17]:
# 지역 컬럼의 고유값 조회
oil['지역'].unique()

array(['서울 강남구', '서울 강동구', '서울 강북구', '서울 강서구', '서울 관악구', '서울 광진구',
       '서울 구로구', '서울 금천구', '서울 노원구', '서울 도봉구', '서울 동대문구', '서울 동작구',
       '서울 마포구', '서울 서대문구', '서울 서초구', '서울 성동구', '서울 성북구', '서울 송파구',
       '서울 양천구', '서울 영등포구', '서울 용산구', '서울 은평구', '서울 종로구', '서울 중구',
       '서울 중랑구'], dtype=object)

> ### str accessor
> - `Series.str.String메소드()`
> - 문자열 타입 Series에 String 메소드들을 사용하여 일괄처리 할 수 있도록 한다.
> - str accessor 메소드 : https://pandas.pydata.org/pandas-docs/stable/reference/series.html#api-series-str

> ### datetime으로 변환
> - `pd.to_datetime(변환할 Series, format="날짜형식")`
> - x 또는 y 축이 날짜 일 경우 datetime 타입으로 처리하는 것이 좋다.
> - format: 년월일의 형식을 strftime 형식문자열로 지정한다. 
>      - [strftime 형식](https://docs.python.org/3/library/datetime.html#strftime-and-strptime-format-codes)  
> - datetime을 변환하면 날짜만의 기능을 다룰 수 있다.
>     - dt accessor를 이용해 datetime의 속성값들을(년, 월, 일 등) 추출할 수 있다.
>     - https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.dt.html

In [20]:
# 지역 컬럼의 값을 이용하여 "구" 컬럼 생성 (지역에서 구만 추출해서 파생변수컬럼 생성해서 구별로로 집계를 할 수있도록 한다.)
oil['구'] = oil['지역'].str.split().str[1]
oil

,번호,지역,상호,주소,기간,상표,셀프여부,고급휘발유,휘발유,경유,실내등유,구
0,A0006039,서울 강남구,(유)동하석유 힐탑셀프주유소,서울 강남구 논현로 640,20220101,SK에너지,셀프,1887,1737,1587,0,강남구
1,A0006039,서울 강남구,(유)동하석유 힐탑셀프주유소,서울 강남구 논현로 640,20220102,SK에너지,셀프,1887,1737,1587,0,강남구
2,A0006039,서울 강남구,(유)동하석유 힐탑셀프주유소,서울 강남구 논현로 640,20220103,SK에너지,셀프,1887,1737,1587,0,강남구
3,A0006039,서울 강남구,(유)동하석유 힐탑셀프주유소,서울 강남구 논현로 640,20220104,SK에너지,셀프,1887,1737,1587,0,강남구
4,A0006039,서울 강남구,(유)동하석유 힐탑셀프주유소,서울 강남구 논현로 640,20220105,SK에너지,셀프,1887,1737,1587,0,강남구
...,...,...,...,...,...,...,...,...,...,...,...,...
81788,A0009138,서울 중랑구,우림주유소,서울 중랑구 용마산로 487 (망우제3동),20221227,GS칼텍스,셀프,0,1525,1745,0,중랑구
81789,A0009138,서울 중랑구,우림주유소,서울 중랑구 용마산로 487 (망우제3동),20221228,GS칼텍스,셀프,0,1525,1720,0,중랑구
81790,A0009138,서울 중랑구,우림주유소,서울 중랑구 용마산로 487 (망우제3동),20221229,GS칼텍스,셀프,0,1525,1720,0,중랑구
81791,A0009138,서울 중랑구,우림주유소,서울 중랑구 용마산로 487 (망우제3동),20221230,GS칼텍스,셀프,0,1515,1715,0,중랑구
81792,A0009138,서울 중랑구,우림주유소,서울 중랑구 용마산로 487 (망우제3동),20221231,GS칼텍스,셀프,0,1515,1715,0,중랑구

In [29]:
# 기간 컬럼을 datetime 타입으로 변경한다.
oil['기간']= pd.to_datetime(oil['기간'], format='%Y%m%d')
oil

,번호,지역,상호,주소,기간,상표,셀프여부,고급휘발유,휘발유,경유,실내등유,구
0,A0006039,서울 강남구,(유)동하석유 힐탑셀프주유소,서울 강남구 논현로 640,2022-01-01,SK에너지,셀프,1887,1737,1587,0,강남구
1,A0006039,서울 강남구,(유)동하석유 힐탑셀프주유소,서울 강남구 논현로 640,2022-01-02,SK에너지,셀프,1887,1737,1587,0,강남구
2,A0006039,서울 강남구,(유)동하석유 힐탑셀프주유소,서울 강남구 논현로 640,2022-01-03,SK에너지,셀프,1887,1737,1587,0,강남구
3,A0006039,서울 강남구,(유)동하석유 힐탑셀프주유소,서울 강남구 논현로 640,2022-01-04,SK에너지,셀프,1887,1737,1587,0,강남구
4,A0006039,서울 강남구,(유)동하석유 힐탑셀프주유소,서울 강남구 논현로 640,2022-01-05,SK에너지,셀프,1887,1737,1587,0,강남구
...,...,...,...,...,...,...,...,...,...,...,...,...
81788,A0009138,서울 중랑구,우림주유소,서울 중랑구 용마산로 487 (망우제3동),2022-12-27,GS칼텍스,셀프,0,1525,1745,0,중랑구
81789,A0009138,서울 중랑구,우림주유소,서울 중랑구 용마산로 487 (망우제3동),2022-12-28,GS칼텍스,셀프,0,1525,1720,0,중랑구
81790,A0009138,서울 중랑구,우림주유소,서울 중랑구 용마산로 487 (망우제3동),2022-12-29,GS칼텍스,셀프,0,1525,1720,0,중랑구
81791,A0009138,서울 중랑구,우림주유소,서울 중랑구 용마산로 487 (망우제3동),2022-12-30,GS칼텍스,셀프,0,1515,1715,0,중랑구
81792,A0009138,서울 중랑구,우림주유소,서울 중랑구 용마산로 487 (망우제3동),2022-12-31,GS칼텍스,셀프,0,1515,1715,0,중랑구

In [57]:
# 기간 컬럼을 이용해 "월", "일", "요일" 컬럼 생성 (dt accessor 이용) (월, 일, 요일 별로 집계할 수있도록 한다.)
oil['월'] = oil['기간'].dt.month
oil['일'] = oil['기간'].dt.day
oil['요일'] = oil['기간'].dt.weekday
oil

,번호,지역,상호,주소,기간,상표,셀프여부,고급휘발유,휘발유,경유,실내등유,구,월,일,요일
0,A0006039,서울 강남구,(유)동하석유 힐탑셀프주유소,서울 강남구 논현로 640,2022-01-01,SK에너지,셀프,1887,1737,1587,0,강남구,1,1,5
1,A0006039,서울 강남구,(유)동하석유 힐탑셀프주유소,서울 강남구 논현로 640,2022-01-02,SK에너지,셀프,1887,1737,1587,0,강남구,1,2,6
2,A0006039,서울 강남구,(유)동하석유 힐탑셀프주유소,서울 강남구 논현로 640,2022-01-03,SK에너지,셀프,1887,1737,1587,0,강남구,1,3,0
3,A0006039,서울 강남구,(유)동하석유 힐탑셀프주유소,서울 강남구 논현로 640,2022-01-04,SK에너지,셀프,1887,1737,1587,0,강남구,1,4,1
4,A0006039,서울 강남구,(유)동하석유 힐탑셀프주유소,서울 강남구 논현로 640,2022-01-05,SK에너지,셀프,1887,1737,1587,0,강남구,1,5,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81788,A0009138,서울 중랑구,우림주유소,서울 중랑구 용마산로 487 (망우제3동),2022-12-27,GS칼텍스,셀프,0,1525,1745,0,중랑구,12,27,1
81789,A0009138,서울 중랑구,우림주유소,서울 중랑구 용마산로 487 (망우제3동),2022-12-28,GS칼텍스,셀프,0,1525,1720,0,중랑구,12,28,2
81790,A0009138,서울 중랑구,우림주유소,서울 중랑구 용마산로 487 (망우제3동),2022-12-29,GS칼텍스,셀프,0,1525,1720,0,중랑구,12,29,3
81791,A0009138,서울 중랑구,우림주유소,서울 중랑구 용마산로 487 (망우제3동),2022-12-30,GS칼텍스,셀프,0,1515,1715,0,중랑구,12,30,4
81792,A0009138,서울 중랑구,우림주유소,서울 중랑구 용마산로 487 (망우제3동),2022-12-31,GS칼텍스,셀프,0,1515,1715,0,중랑구,12,31,5

In [58]:
# 요일 - 0:월, 1:화, 2:수, 3:목, 4:금, 5:토, 6:일 로 변경
dict = {0:'월', 1:'화', 2:'수', 3:'목', 4:'금', 5:'토', 6:'일'}
oil['요일'] = oil['요일'].map(dict)
oil

,번호,지역,상호,주소,기간,상표,셀프여부,고급휘발유,휘발유,경유,실내등유,구,월,일,요일
0,A0006039,서울 강남구,(유)동하석유 힐탑셀프주유소,서울 강남구 논현로 640,2022-01-01,SK에너지,셀프,1887,1737,1587,0,강남구,1,1,토
1,A0006039,서울 강남구,(유)동하석유 힐탑셀프주유소,서울 강남구 논현로 640,2022-01-02,SK에너지,셀프,1887,1737,1587,0,강남구,1,2,일
2,A0006039,서울 강남구,(유)동하석유 힐탑셀프주유소,서울 강남구 논현로 640,2022-01-03,SK에너지,셀프,1887,1737,1587,0,강남구,1,3,월
3,A0006039,서울 강남구,(유)동하석유 힐탑셀프주유소,서울 강남구 논현로 640,2022-01-04,SK에너지,셀프,1887,1737,1587,0,강남구,1,4,화
4,A0006039,서울 강남구,(유)동하석유 힐탑셀프주유소,서울 강남구 논현로 640,2022-01-05,SK에너지,셀프,1887,1737,1587,0,강남구,1,5,수
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81788,A0009138,서울 중랑구,우림주유소,서울 중랑구 용마산로 487 (망우제3동),2022-12-27,GS칼텍스,셀프,0,1525,1745,0,중랑구,12,27,화
81789,A0009138,서울 중랑구,우림주유소,서울 중랑구 용마산로 487 (망우제3동),2022-12-28,GS칼텍스,셀프,0,1525,1720,0,중랑구,12,28,수
81790,A0009138,서울 중랑구,우림주유소,서울 중랑구 용마산로 487 (망우제3동),2022-12-29,GS칼텍스,셀프,0,1525,1720,0,중랑구,12,29,목
81791,A0009138,서울 중랑구,우림주유소,서울 중랑구 용마산로 487 (망우제3동),2022-12-30,GS칼텍스,셀프,0,1515,1715,0,중랑구,12,30,금
81792,A0009138,서울 중랑구,우림주유소,서울 중랑구 용마산로 487 (망우제3동),2022-12-31,GS칼텍스,셀프,0,1515,1715,0,중랑구,12,31,토

In [63]:
# 휘발유 가격이 가장 비싼 5개 행 조회
oil.sort_values(by='휘발유', ascending=False).head()

,번호,지역,상호,주소,기간,상표,셀프여부,고급휘발유,휘발유,경유,실내등유,구,월,일,요일
78938,A0000767,서울 중구,서남주유소,서울 중구 통일로 30,2022-06-25,SK에너지,일반,3496,3096,3223,2719,중구,6,25,토
78935,A0000767,서울 중구,서남주유소,서울 중구 통일로 30,2022-06-22,SK에너지,일반,3496,3096,3223,2719,중구,6,22,수
78940,A0000767,서울 중구,서남주유소,서울 중구 통일로 30,2022-06-27,SK에너지,일반,3496,3096,3223,2719,중구,6,27,월
78936,A0000767,서울 중구,서남주유소,서울 중구 통일로 30,2022-06-23,SK에너지,일반,3496,3096,3223,2719,중구,6,23,목
78939,A0000767,서울 중구,서남주유소,서울 중구 통일로 30,2022-06-26,SK에너지,일반,3496,3096,3223,2719,중구,6,26,일

In [65]:
# 휘발유 가격이 가장 저렴한 5개 행 조회 (단 0원인 주유소 제외)
oil[oil['휘발유'] > 0].sort_values(by='휘발유').head()

,번호,지역,상호,주소,기간,상표,셀프여부,고급휘발유,휘발유,경유,실내등유,구,월,일,요일
15150,A0000549,서울 강서구,이케이에너지(주) 강서주유소,서울 강서구 화곡로 273 (화곡동),2022-12-24,현대오일뱅크,셀프,0,1410,1660,0,강서구,12,24,토
15149,A0000549,서울 강서구,이케이에너지(주) 강서주유소,서울 강서구 화곡로 273 (화곡동),2022-12-23,현대오일뱅크,셀프,0,1410,1660,0,강서구,12,23,금
65745,A0001005,서울 양천구,현대주유소,서울 양천구 남부순환로 372 (신월동),2022-12-27,S-OIL,셀프,0,1410,1660,0,양천구,12,27,화
16805,A0000519,서울 강서구,화곡역주유소,서울 강서구 강서로 154 (화곡동),2022-12-23,알뜰주유소,셀프,0,1410,1660,0,강서구,12,23,금
15151,A0000549,서울 강서구,이케이에너지(주) 강서주유소,서울 강서구 화곡로 273 (화곡동),2022-12-25,현대오일뱅크,셀프,0,1410,1660,0,강서구,12,25,일

In [66]:
# 고급휘발유 가격이 가장 비싼 5개 행 조회
oil.sort_values(by='고급휘발유', ascending=False).head()

,번호,지역,상호,주소,기간,상표,셀프여부,고급휘발유,휘발유,경유,실내등유,구,월,일,요일
78940,A0000767,서울 중구,서남주유소,서울 중구 통일로 30,2022-06-27,SK에너지,일반,3496,3096,3223,2719,중구,6,27,월
78938,A0000767,서울 중구,서남주유소,서울 중구 통일로 30,2022-06-25,SK에너지,일반,3496,3096,3223,2719,중구,6,25,토
78939,A0000767,서울 중구,서남주유소,서울 중구 통일로 30,2022-06-26,SK에너지,일반,3496,3096,3223,2719,중구,6,26,일
78936,A0000767,서울 중구,서남주유소,서울 중구 통일로 30,2022-06-23,SK에너지,일반,3496,3096,3223,2719,중구,6,23,목
78937,A0000767,서울 중구,서남주유소,서울 중구 통일로 30,2022-06-24,SK에너지,일반,3496,3096,3223,2719,중구,6,24,금

In [67]:
# 고급휘발유 가격이 가장 저렴한 5개 행 조회 (단 0원인 주유소 제외)
oil[oil['고급휘발유'] > 0].sort_values(by='고급휘발유').head()

,번호,지역,상호,주소,기간,상표,셀프여부,고급휘발유,휘발유,경유,실내등유,구,월,일,요일
15887,A0000520,서울 강서구,하이웨이주유소,서울특별시 강서구 공항대로 432(화곡동),2022-12-25,S-OIL,셀프,1599,1499,1729,0,강서구,12,25,일
15888,A0000520,서울 강서구,하이웨이주유소,서울특별시 강서구 공항대로 432(화곡동),2022-12-26,S-OIL,셀프,1599,1499,1729,0,강서구,12,26,월
15886,A0000520,서울 강서구,하이웨이주유소,서울특별시 강서구 공항대로 432(화곡동),2022-12-24,S-OIL,셀프,1599,1499,1729,0,강서구,12,24,토
15889,A0000520,서울 강서구,하이웨이주유소,서울특별시 강서구 공항대로 432(화곡동),2022-12-27,S-OIL,셀프,1599,1499,1729,0,강서구,12,27,화
15882,A0000520,서울 강서구,하이웨이주유소,서울특별시 강서구 공항대로 432(화곡동),2022-12-20,S-OIL,셀프,1599,1527,1787,0,강서구,12,20,화

In [68]:
# 경유 가격이 가장 비싼 5개 행 조회
oil.sort_values(by='경유', ascending=False).head()

,번호,지역,상호,주소,기간,상표,셀프여부,고급휘발유,휘발유,경유,실내등유,구,월,일,요일
78941,A0000767,서울 중구,서남주유소,서울 중구 통일로 30,2022-06-28,SK에너지,일반,3481,3081,3230,2703,중구,6,28,화
78942,A0000767,서울 중구,서남주유소,서울 중구 통일로 30,2022-06-29,SK에너지,일반,3481,3081,3230,2703,중구,6,29,수
78943,A0000767,서울 중구,서남주유소,서울 중구 통일로 30,2022-06-30,SK에너지,일반,3481,3081,3230,2703,중구,6,30,목
77929,A0000767,서울 중구,서남주유소,서울 중구 통일로 30,2022-07-01,SK에너지,일반,3481,3081,3230,2703,중구,7,1,금
77931,A0000767,서울 중구,서남주유소,서울 중구 통일로 30,2022-07-03,SK에너지,일반,3481,3081,3230,2703,중구,7,3,일

In [69]:
# 경유 가격이 가장 저렴한 5개 행 조회 (단 0원인 주유소 제외)
oil[oil['경유'] > 0].sort_values(by='경유').head()

,번호,지역,상호,주소,기간,상표,셀프여부,고급휘발유,휘발유,경유,실내등유,구,월,일,요일
45209,A0011826,서울 서초구,만남의광장주유소,서울 서초구 양재대로12길 73-71,2022-01-16,알뜰(ex),셀프,0,1565,1367,0,서초구,1,16,일
12345,A0004657,서울 강서구,뉴신정주유소,서울 강서구 곰달래로 207 (화곡동),2022-01-13,알뜰주유소,일반,0,1547,1377,0,강서구,1,13,목
12339,A0004657,서울 강서구,뉴신정주유소,서울 강서구 곰달래로 207 (화곡동),2022-01-07,알뜰주유소,일반,0,1547,1377,1397,강서구,1,7,금
12344,A0004657,서울 강서구,뉴신정주유소,서울 강서구 곰달래로 207 (화곡동),2022-01-12,알뜰주유소,일반,0,1547,1377,0,강서구,1,12,수
16319,A0000519,서울 강서구,화곡역주유소,서울 강서구 강서로 154 (화곡동),2022-01-07,알뜰주유소,셀프,0,1547,1377,0,강서구,1,7,금

In [ ]:
# 상표별 휘발유 평균가격 조회

In [ ]:
# 상표별 휘발유 평균가격 시각화

In [ ]:
# 셀프주유소와 일반주유소 개수 확인

In [ ]:
# 셀프 여부에 따른 휘발유 평균 가격 비교

In [ ]:
# 상표별 일반/셀프 주유소의 휘발유 가격 평균 비교

In [ ]:
# 상표별 일반/셀프 주유소의 휘발유 가격 평균 비교 시각화

In [ ]:
# 상표별 휘발유 가격의 분포를 boxplot으로 시각화

In [ ]:
# 상표별 일반/셀프 주유소의 휘발유 가격에 대한 분포 확인 - boxplot으로 시각화

In [ ]:
# 구별 휘발유 가격의 평균

In [ ]:
# 평균 가격이 가장 높은 구의 상표별 휘발유 평균가격

In [ ]:
# 월 평균 휘발유 가격

In [ ]:
# 각 구의 월별 평균 휘발유 가격

In [ ]:
# 각 구의 월별 평균가격의 변화추이 시각화

In [ ]:
# 가장 휘발유가격이 비싼 주유소 상위 5 - (같은 주유소가 여러개 나오므로 가장 비싼 가격을 기준으로 집계)

In [ ]:
# 가장 휘발유가격이 저렴한 주유소 상위 5 - (같은 주유소가 여러개 나오므로 가장 비싼 가격을 기준으로 집계)

In [ ]:
# 휘발유 비싼 주유소의 상위 5개의 상호, 주소, 상표, 셀프여부,  조회 - 위에서 조회한 결과에 추가 정보(상표, 셀프여부 등) 조회 (중복제거-drop_duplicates)

In [ ]:
# 휘발유 저렴한 주유소의 상위 5개의 상호, 주소, 상표, 셀프여부,  조회 - 위에서 조회한 결과에 추가 정보(상표, 셀프여부 등) 조회 (중복제거-drop_duplicates)

In [ ]:
# 고급 휘발유를 가장 많이 파는 구 조회

In [ ]:
###############################################################################
# 주유소 가격 데이터를 이용해서 알고 싶은 정보들을 추가 분석해 보세요.
###############################################################################