# RAG 평가 개요
- RAG 평가란 RAG 시스템이 주어진 입력에 대해 얼마나 효과적으로 관련 정보를 검색하고, 이를 기반으로 정확하고 유의미한 응답을 생성하는지를 측정하는 과정이다. 
- **평가 요소**
    - **검색 단계 평가**
        - 입력 질문에 대해 검색된 문서나 정보의 관련성과 정확성을 평가.
    - **생성 단계 평가**
        - 검색된 정보를 기반으로 생성된 응답의 품질, 정확성등을 평가.
- **평가 방법**
    - 온/오프라인 평가
        1. **오프라인 평가**
            - 미리 준비된 데이터셋을 활용하여 RAG 시스템의 성능을 측정한다.
        2. **온라인 평가**
            - 실제 사용자 트래픽과 피드백을 기반으로 시스템의 실시간 성능을 평가한다.
    - 정량적/정성적 평가
        1. 정량적 평가
            - 자동화된 지표를 사용하여 생성된 텍스트의 품질을 평가한다.
        2. 정성적 평가
            - 전문가나 일반 사용자가 직접 생성된 응답의 품질을 평가하여 주관적인 지표를 평가한다.

# [RAGAS](https://www.ragas.io/)
- RAGAS는 RAG 파이프라인을 **정량적 으로 평가하는** 오픈소스 프레임 워크이다. 
- RAGAS 문서: https://docs.ragas.io/en/stable/
## 설치
- `pip install ragas rapidfuzz`

In [1]:
!uv pip install ragas rapidfuzz

error: No virtual environment found; run `uv venv` to create an environment, or pass `--system` to install into a non-virtual environment

## RAGAS 평가 지표 개요
![ragas_score](figures/ragas_score.png)
- **Generation**
    - llm 모델이 생성한 답변에 대한 평가 지표들.
    - **Faithfulness(신뢰성)**
        -  생성된 답변과 검색된 문서(context)간의 관련성을 평가하는 지표
        -  생성된 답변이 주어진 문맥(context)에 얼마나 충실한지를 평가하는 지표로 할루시네이션에 대한 평가로 볼 수있다.
    - **Answer relevancy(답변 적합성)**
        - 생성된 답변과 사용자의 질문간의 관련성을 평가하는 지표
        - 생성된 답변이 사용자의 질문과 얼마나 관련성이 있는지를 평가하는 지표.
- **Retrieval**
    -  질문에 대해 검색한 문서(context)들에 대한 평가
    -  **Context Precision(문맥 정밀도)**
        -  검색된 문서(context)들 중 질문과 관련 있는 것들이 **얼마나 상위 순위에 위치하는지** 평가하는 지표.
    -  **Context Recall(문맥 재현률)**
        -  검색된 문서(context)가 정답(ground-truth)의 정보를 얼마나 포함하고 있는지 평가하는 지표.
- 이러한 지표들은 RAG 파이프라인의 성능을 다각도로 평가하는 데 활용된다.
![RAGAS_score2](figures/RAGAS_score2.png)

## 주요 평가지표
### Generation 평가
- LLM이 생성한 답변에 대한 평가
  
#### Faithfulness (신뢰성)
- 생성된 답변이 얼마나 주어진 검색 문서들(context)를 잘 반영해서 생성되었는지 평가한다. 할루시네이션에 대한 평가라고 할 수 있다. 
- 점수범위: **0 ~ 1** (1에 가까울수록 좋음)
- 답변에 포함된 모든 주장이 context에서 얼마나 추출 가능한지를 확인한다.

##### 평가 방법
1. Answer에서 주장 구문(claim statement)들을 생성(추출)한다. (주장이란, 질문(user input)과 관련된 내용)
    - 예) 
        - **질문**: 한국의 수도는 어디이고 인구는 얼마나 되나요? 
        - **LLM 답변**: 한국의 수도는 서울이고 인구수는 3000만명이다. 
        - **주장(claim)**: 
            1. 한국의 수도는 서울이다.
            2. 인구수는 3000만명이다.
2. 각 주장들을 context로 부터 추론 가능한지 판단한다. 이를 바탕으로 faithfulness 점수를 계산한다.
    - 예)
        - context: 한국은 동아시아에 위치하고 있는 나라다. 한국의 수도는 서울이다. .... 한국의 인구는 5000만명이고 서울에 1000만이 살고 있다.
        - 위 context에서 추론 가능한 주장: 
            - 한국의 수도는 서울이다. -> context에서 추론가능한 주장.
            - 한국의 인구는 3000만명이다. -> context에서 추론 불가능한 주장.
3. **Faithfulness score** 를 계산한다. 총 주장 수 중에서 context로 부터 추론가능한 주장의 개수.    
    - 예)
        - Faithfulness Score = $\cfrac{1}{2} = 0.5$ (두 개의 주장 중 한 개의 주장만 context에서 유추할 수있다.)
    - LLM 답변에서 주장을 추출 하는 것과 각 주장이 context에서 추론 가능한 지를 판단하는 것은 LLM 을 활용한다.
- 공식
    $$
    \text{Faithfulness Score}\;=\;\cfrac{\text{주어진\;context\;에서\;추론할\;수\;있는\;주장의\;개수}}{\text{총\;주장\;개수}}
    $$

### Answer relevancy (답변 적합성)
- 생성된 답변이 질문(user input)에 얼마나 잘 부합하는 지를 평가한다.
- 점수 범위: -1~1 (1에 가까울수록 좋음)
- LLM이 생성한 답변을 기반으로 질문들을 생성한다. 이렇게 생성한 질문들과 실제 질문(user input) 간의 유사도를 측정한다.

#### 평가방법
1. LLM이 생성한 답변을 기반으로 질문들을 생성한다.
    - 예) 
        - **LLM** 답변: 한국의 수도는 서울이고 인구수는 3000만명이다. 
        - **생성된 질문**: 
            1. 한국의 수도는 어디이고 인구는 얼마나 되나요?
            2. 한국의 수도는 어디인가요?
            3. 한국의 인구는 얼마나 되나요?
2. 실제 질문과 생성한 질문간의 코사인 유사도를 측정한다. 그 평균이 최종 점수가 된다.
    - 예)
        - **실제 질문**: 한국의 수도는 어디이고 인구는 얼마나 되나요?
        - **생성된 질문**: 
            1. 한국의 수도는 어디이고 인구는 얼마나 되나요?
            2. 한국의 수도는 어디인가요?
            3. 한국의 인구는 얼마나 되나요?
- 공식
  $$
    \cfrac{1}{N} \sum_{i=1}^{N} \text{cosine\_similarity}(q_{\text{user}_{_i}}, q_{\text{generated}})
  $$

## Retrieval 평가
Vector store에서 검색한 context에 대한 평가

### Context Precision
- 검색된 문서(context)들 중 질문과 관련 있는 것들이 얼마나 **상위 순위**에 있는 지 평가.
- 점수 범위: 0~1 (1에 가까울수록 좋음)


#### 평가방법

- 공식
$$
 \text{Context\;Precision@K} = \frac{\sum_{k=1}^{K} \left( \text{Precision@k} \times v_k \right)}{\ 상위\;K개\;결과에서의\;관련\;항목\;수}
$$
$$
 \text{Precision@k} = \frac{\text{True\;positive@k}}{(\text{True\;positive@k} + \text{False\;positive@k})} \\
$$
- $\text{Precision@k}$: 개별 문서에 대한 Precision
- K: context 의 개수(chuck 수)
- $v_k$: 관련성 여부로 0 또는 1. (0: 관련 없음, 1: 관련 있음)

#### 예시
- 질문과 context 관련성 예
    - 질문: 한국의 수도는 어디이고 인구는 얼마나 되나요?
    - 높은 정밀도 context
        - 한국의 수도는 서울이고 인구는 5000명 입니다. 
        - 한국의 수도는 서울입니다.
        - 한국은 동아시아에 위치해 있는 국가로 수도는 서울입니다.
        - 한국의 인구는 5000만명 입니다.
    - 낮은 정밀도 context
        - 한국은 동아시아에 위치한 국가입니다.
        - 한국의 K-pop은 전 세계적으로 유명합니다.
        - 비빔밥, 불고기는 한국의 대표적인 음식입니다.
    - **높은 정밀도의 context이 상위 순위에 위치했으면 높은 점수를 받는다.**
- 상위 5개의 검색 결과 중 1번째, 3번째, 4번째 문서가 관련이 있다고 가정
    ```bash
    Precision@1 = 1/1 = 1.0    # True positive@1/(True positive@1 + False positive@1).  1/1(1번 문서 계산 시에는 1개 문서만 있으므로 분모가 1이 된다.)
    Precision@2 = 1/2 = 0.5     
    Precision@3 = 2/3 ≈ 0.67    
    Precision@4 = 3/4 = 0.75
    Precision@5 = 3/5 = 0.6
    ```
- vk의 값
    - 1번째: $v_1 = 1$
    - 2번째: $v_2 = 0$
    - 3번째: $v_3 = 1$
    - 4번째: $v_4 = 1$
    - 5번째: $v_5 = 0$

- Context Precision@5
$$
\text{Context\;Precision@5} = \frac{(1.0 \times 1) + (0.5 \times 0) + (0.67 \times 1) + (0.75 \times 1) + (0.6 \times 0)}{3} = \frac{1.0 + 0 + 0.67 + 0.75 + 0}{3} ≈ 0.807
$$

# GUIDE
- 예를 들어, 상위 5개의 검색 결과 중 1번째, 3번째, 4번째 문서가 관련이 있다고 가정하면:
```bash
Precision@1 = 1/1 = 1.0     # 1등 -> 1/1  --> 1 등이 관련 없는 것이면 전체 평균 점수가 확 낮아 질 수있다.
Precision@2 = 1/2 = 0.5     # 2등 -> 1/2  (1, 2등 두개 중에 하나만 관련(1번)이 있다.)
Precision@3 = 2/3 ≈ 0.67    # 3등 -> 2/3  (1, 2, 3 등 세개 중에 두개만 관련(1,3번)이 있다.)
Precision@4 = 3/4 = 0.75
Precision@5 = 3/5 = 0.
```
왜 분모가 1, 2, 3, 4, 5 -> 그 순위에는 상위순위와 자신밖에 없으므로 그 개수가 분모가됨. (3등은 1, 2, 3 등 세개 문서로.)

### Context Recall (문맥 재현률)
- 검색된 문서(context)가 얼마나 정답(ground-truth)의 정보를 포함있는 지 평가하는 지표
- 점수 범위: 0~1 (1에 가까울수록 좋음)
- **정답(ground truth)의 각 주장(claim)이 검색된 context와 얼마나 일치**하는지 계산함.

#### 평가방법
1. 정답에서 주장(claim)들을 생성(추출)한다.
    - 예) 
        - **정답**: 한국의 수도는 서울이고 인구수는 5000만명이다. 
        - **주장(claim)**: 
            1. 한국의 수도는 서울이다.
            2. 인구수는 5000만명이다.
2. 각 주장(claim)의 정보를 검색된 contexts에서 찾을 수 있는지 판별한다. 이를 바탕으로 context recall 점수를 계산한다.
    - 예)
        - context: 한국은 동아시아에 위치하고 있는 나라다. 한국의 수도는 서울이다.
        - 위 context에서 추론 가능한 주장: 
            - 한국의 수도는 서울이다. -> context에서 찾을 수 있다.
            - 한국의 인구는 5000만명이다. -> context에서 찾을 수 없다.
3. **Context Recall Score** 를 계산한다. 총 주장 수 중에서 context로 부터 찾을 수 있는 주장의 개수.
    - 예)
        - Context Recall Score = $\cfrac{1}{2} = 0.5$ (두 개의 주장 중 한 개의 주장만 context에서 찾을 수 있다.)

- 공식
    $$
    \text{Context Recall Score}\;=\;\cfrac{\text{GT의\;주장\;중\;주어진\;context\;에서\;찾을\;수\;있는\;주장의\;개수}}{\text{GT의\;총\;주장\;개수}}
    $$

# RAGAS 평가 실습

In [2]:
# !uv pip install ragas rapidfuzz
# 설치 후 커널 재시작

In [3]:
from langchain_text_splitters import MarkdownHeaderTextSplitter
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.runnables import RunnablePassthrough
from langchain_core.output_parsers import StrOutputParser

from langchain_openai import ChatOpenAI
from langchain_qdrant import FastEmbedSparse, QdrantVectorStore, RetrievalMode
from qdrant_client import QdrantClient, models
from qdrant_client.models import Distance, SparseVectorParams, VectorParams
from langchain_openai import OpenAIEmbeddings

from dotenv import load_dotenv

load_dotenv()

True

In [4]:
# ##############################################################
# 데이터 준비
##############################################################

def load_and_split_olympic_data(file_path="data/olympic_wiki.md"):
    with open(file_path, "r", encoding="utf-8") as fr:
        olympic_text = fr.read()

    # Split
    splitter = MarkdownHeaderTextSplitter(
        headers_to_split_on=[
            ("#", "Header 1"),
            ("##", "Header 2"),
            ("###", "Header 3"),
        ],
        # strip_headers=False, # 문서에 header 포함 여부(default: True - 제거)
    )

    return splitter.split_text(olympic_text)

In [5]:
#################################################################
# Vector DB 연결
# retriever 생성
#################################################################

def get_vectorstore(collection_name: str = "olympic_info_wiki"):


    dense_embeddings = OpenAIEmbeddings(model="text-embedding-3-large")

    client = QdrantClient(host="localhost", port=6333)

    # 컬렉션 삭제
    if client.collection_exists(collection_name):
        result = client.delete_collection(collection_name=collection_name)

    # 컬렉션 생성
    client.create_collection(
        collection_name=collection_name,
        vectors_config=VectorParams(size=3072, distance=Distance.COSINE),
    )

    vectorstore = QdrantVectorStore(
        client=client,
        collection_name=collection_name,    
        embedding=dense_embeddings
    )
    
    ######################################
    # Document들 추가
    ######################################
    documents = load_and_split_olympic_data()
    vectorstore.add_documents(documents=documents)

    return vectorstore


def get_retriever(vectorstore, k: int = 5):
    retriever = vectorstore.as_retriever(
        search_kwargs={"k": k}
    )
    return retriever

In [6]:
vectorstore = get_vectorstore()

retriever = get_retriever(vectorstore)
retriever

VectorStoreRetriever(tags=['QdrantVectorStore', 'OpenAIEmbeddings'], vectorstore=<langchain_qdrant.qdrant.QdrantVectorStore object at 0x0000018137D5AF90>, search_kwargs={'k': 5})

In [7]:
################################################################################
# 평가할 RAG Chain
################################################################################

from langchain_core.prompts import PromptTemplate, ChatPromptTemplate
from langchain_core.runnables import RunnablePassthrough 
from langchain_core.output_parsers import StrOutputParser
from langchain_core.documents import Document


vectorstore = get_vectorstore()
retriever = get_retriever(vectorstore)

prompt_txt = """# Instruction:
당신은 정보제공을 목적으로하는 유능한 AI Assistant 입니다.
주어진 context의 내용을 기반으로 질문에 답변을 합니다.
Context에 질문에 대한 명확한 정보가 있는 경우 그것을 바탕으로 답변을 합니다.
Context에 질문에 대한 명확한 정보가 없는 경우 "정보가 부족해 답을 할 수없습니다." 라고 답합니다.
절대 추측이나 일반 상식을 바탕으로 답을 하거나 Context 없는 내용을 만들어서 답변해서는 안됩니다.

# Context:
{context}

# 질문:
{query}
"""
prompt = ChatPromptTemplate.from_template(
    template=prompt_txt
)


def format_docs(documents:list)->str:
    """
    VectorStore에 조회한 문서들에서 내용(page_content)만 추출해서 str으로 합쳐서 반환.
    VectorStore의 검색결과인 List[Document]를 받아서 Document들에서 page_content의 내용만 추출한다.
    
    Args:
        documents(list[Document]): [Document(..), Document(...), ..]}
    Returns:
        str: 각 문서의 내용을 "\n\n"으로 연결한 string
    """
    return "\n\n".join(doc.page_content for doc in documents)

model = ChatOpenAI(model="gpt-5-mini")
parser = StrOutputParser()

# chain = {
#     "context":retriever | format_docs,
#     "query":RunnablePassthrough()
# } | prompt | model | parser


# RAG 평가를 위해서 "답변", "검색한 문서" 둘이 출력되도록 변경.
from langchain_core.runnables import RunnablePassthrough, RunnableLambda
from operator import itemgetter

def format_doc_list(docs_dict: dict) -> list:
    # dictionary[list[Document], query:str] -> list[str]  
    # 문서내용만 추출해서(Document.page_content)만 추출한 리스트
    return [doc.page_content for doc in docs_dict['context']]

# dict | dict -> dict
# RunnablePassthrough() | dict | dict ==> RunnableSequence
chain = RunnablePassthrough() | {
    "context":retriever,
    "query":RunnablePassthrough()
} | {
    "response": prompt | model | parser,
    "retrieved_context": format_doc_list, # RAGAS 평가시 context -> List[str]
}

In [8]:
res = chain.invoke("1회 올림픽은 언제 어디서 열렸지")

In [9]:
res.keys()

dict_keys(['response', 'retrieved_context'])

In [10]:
print(res['response'])

제1회 올림픽은 1896년 그리스 아테네에서 열렸습니다.

In [11]:
res['retrieved_context']

['고대의 올림픽 경기(올림피아 경기)는 고대 그리스의 여러 도시 국가의 대표선수들이 모여 벌인 일련의 시합이었으며, 육상 경기가 주 종목이지만 격투기와 전차 경기도 열렸다. 그리고 패배하면 죽기도 하였다. 고대 올림픽의 유래는 수수께끼로 남아있다. 잘 알려진 신화로는 헤라클레스와 그의 아버지인 제우스가 올림픽의 창시자였다는 것이다. 전설에 따르면 이 경기를 최초로 \'올림픽\'이라고 부르고, 4년마다 대회를 개최하는 관례를 만든 사람이 헤라클레스라고 한다. 어떤 전설에서는 헤라클레스가 이른바 헤라클레스의 12업을 달성한 뒤에 제우스를 기리고자 올림픽 경기장을 지었다고 한다. 경기장이 완성되자 헤라클레스는 일직선으로 200 걸음을 걸었으며, 이 거리를 "스타디온"이라 불렀는데, 후에 이것이 길이 단위인 \'스타디온\'(그리스어: στάδιον → 라틴어: 영어: stadium)이 되었다. 또 다른 설로는 \'올림픽 휴전\'(그리스어: ἐκεχειρία 에케케이리아[*])이라는 고대 그리스의 관념이 최초의 올림피아 경기와 관련이 있다고 한다. \'올림픽 휴전\'이란 어느 도시 국가라도 올림피아 경기 기간 중에 다른 나라를 침범하면 그에 대한 응징을 받을 수 있다는 뜻으로, "올림픽 기간에는 전쟁하지 말 것"으로 요약할 수 있다.  \n고대 올림피아 경기가 처음 열린 시점은 보통 기원전 776년으로 인정되고 있는데, 이 연대는 그리스 올림피아에서 발견된 비문에 근거를 둔 것이다. 이 비문의 내용은 달리기 경주 승자 목록이며 기원전 776년부터 4년 이후 올림피아 경기 마다의 기록이 남겨져 있다. 고대 올림픽의 종목으로는 육상, 5종 경기(원반던지기, 창던지기, 달리기, 레슬링, 멀리뛰기), 복싱, 레슬링, 승마 경기가 있었다. 전설에 따르면 엘리스의 코로이보스가 최초로 올림피아 경기에서 우승한 사람이라고 한다.  \n고대 올림피아 경기는 근본적으로 종교적인 중요성을 띄고 있었는데, 스포츠 경기를 할 때는 제우스(올림피아의 제우스 신전에는 페이디아스가 만든 제우스 상이 있음)와 펠롭스를 기리기 위하여 제물 봉헌 의식을 치렀다. 펠롭스는 올림피아의 전설상의 임금이었던 피사티스의 오이노마오스 왕과 전차 경주를 겨룬 영웅으로 유명한 인물이다. 올림피아 경기의 승자는 시와 조각상으로 칭송받았다. 올림피아 경기는 4년마다 열렸으며, 이 기간을 \'올림피아드\'(Olympiad)라고 했는데, 그리스인들은 이를 시간 단위로 이용하였다. 올림피아 경기는 고대 그리스에서 정기적으로 열렸던 범그리스 대회의 순환 대회 가운데 하나였다.  \n올림피아 경기는 기원전 6세기~기원전 5세기에 절정에 이르렀으나, 그 후 로마가 패권을 잡은 뒤 그리스에 영향력을 행사하면서 서서히 쇠퇴하게 된다. 고대 올림픽이 공식적으로 끝난 해는 확실히 알 수 없으나, 대부분 테오도시우스 1세 황제가 모든 이단 숭배 및 예배를 금지했던 393년을 고대 올림픽의 마지막이라고 추정한다. 다른 설에 따르면 테오도시우스의 후계자인 테오도시우스 2세가 모든 그리스 신전을 파괴하라고 명령한 426년이라고도 한다. 이렇게 올림픽이 사라진 이후로 이보다 한참 뒤인 19세기에 이르러서야 비로소 다시 올림픽 경기가 열리게 된다.',
 '쿠베르탱의 생각과는 달리, 올림픽이 세계에 완벽한 평화를 가져다주지는 못했다. 실제로 제1차 세계대전으로 인해 독일 베를린에서 열리기로 했던 제6회 1916년 하계 올림픽이 취소되었고, 제2차 세계대전 때는 일본 도쿄에서 열리기로 했던 제12회 1940년 하계 올림픽, 삿포로에서 열리기로 했던 1940년 동계 올림픽, 영국 런던에서 열리기로 했던 제13회 1944년 하계 올림픽, 이탈리아 코르티나담페초에서 열릴 예정인 1944년 동계 올림픽이 취소되었다. 베이징에서 열린 2008년 하계 올림픽 개막식날 조지아와 러시아 간의 2008년 남오세티아 전쟁이 일어나기도 했다. 부시 대통령과 푸틴 대통령이 이 올림픽을 보러 왔으며 중국 주석인 후진타오가 주최한 오찬에 참석해서 이 현안에 대해 논의하기도 했다. 조지아 대표인 니노 살루크바체와 러시아 대표인 나탈리야 파데리나가 여자 10m 공기권총 경기에서 각각 동메달과 은메달을 땄을 때 이 일은 베이징 올림픽의 유명한 사건 중 하나로 남게 되었다. 살루크바체와 파데리나는 시상식이 끝난 뒤 서로 포옹을 하며 국적에 상관없이 기쁨을 나누었다.  \n테러도 올림픽에서 공포의 대상이었다. 뮌헨 참사로 알려진 1972년에 서독 바이에른의 뮌헨에서 열린 하계 올림픽때의 사건은 테러리스트인 검은 9월단이 일으킨 사건으로서 이스라엘 선수 11명을 인질로 붙잡았다가 전원이 사망한 사건이다. 당시 미숙한 진압으로 인해 인질 9명(선수 1명과 코치 1명은 인질로 잡기 이전에 살해), 테러범 5명, 독일 경찰관 1명이 사망했으며 이 진압 작전 이전에는 인질들은 단 한 명도 죽지 않았다. 애틀랜타에서 열린 1996년 하계 올림픽 때는 센테니얼 올림픽 공원(Centennial Olympic Park)에서 폭발 사건이 일어나 2명이 죽고 111명이 다치는 사건이 발생했다. 이 사건의 주모자 에릭 로버트 루돌프는 종신형을 선고받았다. 참고로 마라톤 역시 전쟁에서 유래한 것이다.',
 '올림픽(영어: Olympic Games, 프랑스어: Jeux olympiques)은 전 세계 각 대륙 각국에서 모인 수천 명의 선수가 참가해 여름과 겨울에 스포츠 경기를 하는 국제적인 대회이다. 전 세계에서 가장 큰 지구촌 최대의 스포츠 축제인 올림픽은 세계에서 가장 인지도있는 국제 행사이다. 올림픽은 2년마다 하계 올림픽과 동계 올림픽이 번갈아 열리며, 국제 올림픽 위원회(IOC)가 감독하고 있다. 또한 오늘날의 올림픽은 기원전 8세기부터 서기 5세기에 이르기까지 고대 그리스 올림피아에서 열렸던 올림피아 제전에서 비롯되었다. 그리고 19세기 말에 피에르 드 쿠베르탱 남작이 고대 올림피아 제전에서 영감을 얻어, 근대 올림픽을 부활시켰다. 이를 위해 쿠베르탱 남작은 1894년에 IOC를 창설했으며, 2년 뒤인 1896년에 그리스 아테네에서 제 1회 올림픽이 열렸다. 이때부터 IOC는 올림픽 운동의 감독 기구가 되었으며, 조직과 활동은 올림픽 헌장을 따른다. 오늘날 전 세계 대부분의 국가에서 올림픽 메달은 매우 큰 영예이며, 특히 올림픽 금메달리스트는 국가 영웅급의 대우를 받으며 스포츠 스타가 된다. 국가별로 올림픽 메달리스트들에게 지급하는 포상금도 크다. 대부분의 인기있는 종목들이나 일상에서 쉽게 접하고 즐길 수 있는 생활스포츠 종목들이 올림픽이라는 한 대회에서 동시에 열리고, 전 세계 대부분의 국가 출신의 선수들이 참여하는 만큼 전 세계 스포츠 팬들이 가장 많이 시청하는 이벤트이다. 2008 베이징 올림픽의 모든 종목 누적 시청자 수만 47억 명에 달하며, 이는 인류 역사상 가장 많은 수의 인구가 시청한 이벤트였다.  \n또한 20세기에 올림픽 운동이 발전함에 따라, IOC는 변화하는 세계의 사회 환경에 적응해야 했다. 이러한 변화의 예로는 얼음과 눈을 이용한 경기 종목을 다루는 동계 올림픽, 장애인이 참여하는 패럴림픽, 스페셜 올림픽, 데플림픽, 10대 선수들이 참여하는 유스 올림픽 등을 들 수 있다. 그 뿐만 아니라 IOC는 20세기의 변화하는 경제, 정치, 기술 환경에도 적응해야 했다. 그리하여 올림픽은 피에르 드 쿠베르탱이 기대했던 순수한 아마추어 정신에서 벗어나서, 프로 선수도 참가할 수 있게 되었다. 올림픽은 점차 대중 매체의 중요성이 커짐에 따라 올림픽의 상업화와 기업 후원을 놓고도 논란이 생겨났다. 또한 올림픽을 치르며 발생한 보이콧, 도핑, 심판 매수, 테러와 같은 수많은 일들은 올림픽이 더욱 굳건히 성장할 수 있는 원동력이 되었다.  \n올림픽은 국제경기연맹(IF), 국가 올림픽 위원회(NOC), 각 올림픽의 위원회(예-벤쿠버동계올림픽조직위원회)로 구성된다. 의사 결정 기구인 IOC는 올림픽 개최 도시를 선정하며, 각 올림픽 대회마다 열리는 올림픽 종목도 IOC에서 결정한다. 올림픽 경기 개최 도시는 경기 축하 의식이 올림픽 헌장에 부합하도록 조직하고 기금을 마련해야 한다. 올림픽 축하 행사로는 여러 의식과 상징을 들 수 있는데 올림픽기나 성화가 그 예이다.  \n올림픽은 거의 모든 국가가 참여할 정도로 규모가 커졌다. 하계 올림픽은 33개의 종목과 약 400개의 세부종목에서 13,000명이 넘는 선수들이 겨루고 그중 각 종목별 1, 2, 3위는 각각 금/은/동을 수여받는다. 전 세계 언론에서 각각 4년마다 열리는 올림픽 경기를 중계하기 때문에 이름 없는 선수가 개인적, 국가적, 세계적으로 명성을 얻을 수 있는 기회가 된다. 이와 더불어 올림픽 경기는 개최지와 개최국에게도 전 세계에 그 이름을 널리 알리는 좋은 기회가 된다.',
 '올림픽 개최지는 해당 올림픽 개최 7년 전에 IOC 위원들의 투표로 결정된다. 개최지 선정에는 약 2년이 걸린다. 유치를 희망하는 도시는 우선 자국의 올림픽 위원회에 신청을 해야 한다. 만약 한 국가에서 두 도시 이상이 유치를 희망한다면, 한 국가당 한 도시만 후보가 될 수 있다는 규칙에 따라 내부적으로 후보 도시를 결정해야 한다. 후보 도시가 결정되면 후보 도시가 소속된 국가의 올림픽 위원회는 IOC에 개최 신청을 하고, 신청 후에는 올림픽 개최에 대한 질의 응답서를 보내야 한다. 이 질의응답서에서 신청한 도시는 올림픽 헌장을 준수하며 IOC 상임이사회에 의한 다른 규정들을 지킬 것이라는 확신을 주어야 한다. 이 질의응답서는 전문가들이 검토하여 신청 도시들의 잠재성과 계획을 평가한다. 이 전문적인 평가를 바탕으로 IOC 상임이사회에서는 신청도시 중에서 후보도시를 고른다.  \n후보도시로 선택되면 그 도시들은 IOC에 보내는 후보도시에 관한 문서에 그들의 계획을 더욱 상세하고 방대한 양으로 적어서 보내야 한다. 평가조사단들이 이 후보도시들을 평가한다. 평가조사단은 후보도시들을 방문해서 지역 관계자들과 회견을 갖고 경기장 시설을 세심하게 조사한 뒤 개최지 투표를 하기 한달전에 조사를 바탕으로 한 공식 보고를 한다. 회견을 하는 동안에도 후보도시들은 자신들이 올림픽을 개최하는 데 충분한 자금이 조달될 수 있는지 등을 입증할 수 있어야 한다. 평가조사단의 업무가 끝나면 후보지의 국가 위원들은 IOC 정기총회에 참석한다. 이 총회에서 IOC 위원들은 올림픽 개최지를 선정하게 되며 후보지의 국가에 소속된 위원들은 자국의 후보지가 탈락하지 않는 이상 투표를 할 수 없다. 투표가 끝난후에 개최지로 선정된 곳의 유치위원회가 IOC와 개최도시 계약서에 서명을 하면 공식적으로 올림픽 개최도시(개최국)으로 인정된다.  \n2016년까지 올림픽은 23개국 44개 도시에서 열렸으며 유럽과 북아메리카대륙 이외의 대륙에서는 고작 8번 밖에 개최하지 못했다. 1988년 하계 올림픽이 대한민국의 서울에서 열린것을 시작으로 그 후 아시아와 오세아니아 대륙에서 올림픽이 4번이나 열렸으며, 이는 그 이전의 현대 올림픽사와 비교해보면 엄청나게 늘어난 수치였다. 2016년 하계 올림픽이 개최된 브라질의 리우데자네이루는 남미에서 열리는 첫 번째 올림픽이다. 아직 아프리카에서는 올림픽이 한 번도 개최되지 않았다. 2008년 하계 올림픽 때 가장 많은 선수가 참여한 나라는 중국으로 639명이 참가했으며 그 다음은 미국과 러시아로 각각 596명과 455명이 참가했다.  \n미국은 5번의 하계 올림픽과 4번의 동계 올림픽을 개최하면서 최다 올림픽을 개최한 나라이다. 영국은 2012년에 3번째 올림픽을 개최하였다. 독일, 오스트레일리아, 그리스는 하계 올림픽을 2번 개최한 국가이다. 동계 올림픽에서는 이탈리아가 2026년 밀라노-코르티나담페초 개최지로 선정되어 3번 개최될 예정이다. 또한 프랑스가 3번을 개최했으며 2024년 하계올림픽 개최예정으로 영국에 이번 두 번째로 한 도시에서 3번 올림픽 개최하며 하계올림픽3번 개최하였다. 프랑스는 동계, 하계 올림픽 각 3번씩 총 6번 개최로 9번으로 최다개최국인 미국 다음으로 두 번째로 많이 개최한 국가가 된다. 스위스, 오스트리아, 노르웨이, 일본, 이탈리아는 2번씩 개최했다. 일본은 하계,동계 각 2번씩 총 4번으로 미국, 프랑스 다음 세번째로 많이 개최한 국가이다. 2010년에 밴쿠버에서 열린 2010년 동계 올림픽은 캐나다에서 열리는 두 번째 동계 올림픽이고, 동/하계 올림픽을 합쳐 캐나다에서 3번째로 개최되는 올림픽이다.',
 '고대 올림피아 경기를 제대로 구현한 최초의 시도는 혁명 시대의 프랑스에서 1796년부터 1798년까지 3년동안 실시했던 프랑스 국내 올림픽인 \'공화국 올림픽\'(L\'Olympiade de la République)이었다. 이 대회의 종목 중에는 고대 그리스 올림피아 경기 때 행한 일부 종목도 있었다. 특히 1798년 공화국 올림픽 대회는 미터법을 최초로 스포츠에 도입시킨 대회이기도 하다. 이후 52년뒤인 1850년에는 잉글랜드 슈롭셔주의 웬록에서 올림픽급의 대회가 열리기 시작하였다. 이 대회는 1859년에 아테네에서 열렸을 때 웬록 올림픽으로 명칭이 변경되었으며 지금도 열리고 있다. 브룩스 박사는 1859년에 아테네에서 열린 올림픽 경기의 내용을 이후 경기에 채택하였다. 1866년 런던의 수정궁에서는 윌리엄 페니 브룩스가 영국의 국가 올림픽 대회를 만들었다.  \n1821년 그리스에서는 오스만 제국의 지배에 반기를 들고 독립 전쟁이 일어나면서, 이때부터 올림픽 부활에 대한 관심이 생겨났다. 시인이자 신문 편집자였던 파나요티스 수초스(Παναγιώτης Σούτσος)는 1833년에 출간한 자신의 시 \'망자(亡者)의 대화\'에서 최초로 올림픽 부활에 대한 제안을 내놓았다. 그리스의 부유한 박애주의자였던 에방겔리스 자파스(Ευαγγέλης Ζάππας)는 1859년에 아테네 시 광장에서 열린 "올림픽 경기(일명 자파스 올림픽)"를 후원하였다. 이 경기에는 그리스와 오스만 제국 출신의 선수들이 참가하였다. 에방겔리스 자파스는 이후에도 올림픽 경기를 개최할 수 있도록 고대의 경기장이었던 파나티네코 경기장을 복원하는 데도 돈을 썼다. 파나티네코 경기장에서 1870년과 1875년에 자파스 올림픽을 개최했으며, 현대 올림픽인 2004년 하계 올림픽 때는 양궁 경기장으로도 쓰였다.  \n역사학자였던 쿠베르탱은 프로이센-프랑스 전쟁(1870–1871)에서 프랑스의 패배 원인을 분석하면서 군사들이 체계적인 체력 훈련을 받지 않았기 때문에 전쟁에서 패배했다고 말한 인물이다. 1890년 웬록 올림픽에 참석한 쿠베르탱은 그 이후부터 올림픽을 대규모로 부활시킬 수 있으리라 생각했다. 쿠베르탱은 웬록 올림픽과 자파스 올림픽을 토대로 하여 올림픽 경기를 국제적으로 시행하기 위해 나라별로 올림픽을 번갈아가며 개최하는 방식을 생각해냈다. 그는 이 방안을 새로 설립된 국제 올림픽 위원회(IOC)의 첫 올림픽 의회 기간 중에 언급했다. 총회는 파리의 소르본 대학교에서 1894년 6월 16일부터 6월 23일까지 7일간 지속되었으며, 총회 마지막날, 2년 후인 1896년에 아테네에서 국제적 규모의 올림픽 대회를 열기로 결정되었다. IOC는 올림픽을 조직하는 데에 모든 책임을 졌으며, 초대 위원장으로는 그리스의 작가였던 디미트리오스 비켈라스(Δημήτριος Βικέλας)가 선출되었다.']

# RAGAS 를 이용해 평가를 위한 합성 데이터 셋 만들기

- 평가 데이터셋 구성
  - `user_input`: 사용자 질문
  - `retrieved_contexts`: Vectorstore에서 검색한 context
  - `response`: LLM의 응답
  - `reference`: 정답

## TestsetGenerator
- **문서(retrieved_contexts)를 기준**으로 **질문**, **정답** 을 생성한다.
- 평가할 LLM으로 생성된 질문을 넣어 답변을 추출하여 데이터셋을 구성한다.

In [12]:
# 주피터노트북 환경에서 비동기적 처리 위해
# script(.py) 로 작성할 경우는 필요 없다.

import nest_asyncio
nest_asyncio.apply()

In [13]:
###########################################
# 데이터셋을 생성할 때 사용할 context를 추출 - sampling
###########################################
client = QdrantClient(host="localhost", port=6333)
COLLECTION_NAME = "olympic_info_wiki"

# 전체 데이터를 다 조회해서 그 중 랜덤하게 K개만 sampling
info = client.get_collection(COLLECTION_NAME)
# info.points_count # 저장된 데이터 개수
results, next_id = client.scroll(
    collection_name=COLLECTION_NAME,
    limit=info.points_count
)

# sampling
import random
sample_dataset = random.sample(results, 5) # 리스트에서 랜덤하게 K개를 추출

# 문서 내용만 추출
docs = [point.payload['page_content'] for point in sample_dataset]
docs

['올림픽에서는 올림픽 헌장에 구체적으로 나타난 이상이나 철학을 표현하는 상징을 사용한다. 오륜기로 잘 알려져 있는 올림픽기는 5개의 둥근 고리가 얽혀있으며 각 원마다 5대륙을 상징한다.(남아메리카와 북아메리카는 아메리카로 합쳐 있다.) 파랑, 노랑, 검정, 초록, 빨간 고리에 흰색 바탕은 올림픽 기를 나타낸다. 이 색들이 선택된 이유는 모든 국기에서 적어도 이 5개의 색 중 하나를 가지고 있기 때문이다. 올림픽 기가 채택된 것은 1914년이지만 1920년 하계 올림픽 때부터 사용되기 시작했다. 이 때부터 올림픽 기는 올림픽을 기념하기 위해 올림픽이 열리는 기간 동안 게양한다.  \n올림픽 표어는 라틴어로 Citius, Altius, Fortius이며 "더 빨리, 더 높게, 더 힘차게"라는 뜻이다. 쿠베르탱의 이상은 올림픽 선서에 더 잘 나타나 있다.  \n- 올림픽 선서 중에서\n- "인생에서 가장 중요한 것은 승리가 아니라 이를 위해 분투하는 것이고, 올림픽에서 가장 중요한 것 역시 승리가 아니라 참가 자체에 의의가 있다. 우리에게 있어 본질은 정복하는 것이 아니라 잘 싸우는 것이다."  \n매 올림픽이 시작되기 몇 개월전에 고대 그리스에서 제사를 지냈던 그리스의 올림피아에서 올림픽 성화가 채화된다. 여자 배우가 마치 여자 사제인 것처럼 연기해서 태양광선을 포물면 거울(오목 거울의 하나)의 안쪽에 집중시켜서 점화한다. 그 후에 여자는 첫 번째 성화 봉송 주자에게 성화를 넘기고 개최도시의 개막식이 열리는 올림픽 경기장까지 여러 사람의 손을 거쳐서 올림픽 성화는 전달된다. 올림픽 상징으로서의 올림픽 성화는 1928년 하계 올림픽 때 이미 있었지만, 성화 봉송은 1936년 하계 올림픽때 독일 정부의 나치즘 선전의 일환으로 처음 시행된 것이 그 유래이다.  \n개최도시의 문화적 상징물을 동물이나 사람의 형상으로 나타내는 올림픽 마스코트는 1968년에 처음 소개되었다. 이후 1980년 하계 올림픽 때 러시아 아기곰인 미샤가 국제적인 스타의 자리에 오르며, 올림픽의 상징에 있어 마스코트가 한층 더 중요한 역할을 하게 되었다. 가장 최근의 하계 올림픽 마스코트는 2012 런던 올림픽의 마스코트인 웬록으로, 웬록은 영국 중서부 슈롭셔의 작은 마을 이름이며 이곳은 근대 올림픽 창시자인 쿠베르탱이 올림픽을 창안했던 곳이다. 또한 가장 최근의 동계 올림픽 마스코트로는 2010년 동계 올림픽의 마스코트인 미가, 콰치, 수미가 있다.',
 '1859년 자파스 올림픽에 참가한 선수의 수는 250명을 넘지 못했다. 에방겔리스 자파스는 "지난 자파스 올림픽을 포함, 1896년에 개최될 2번째 올림픽을 위해 파나티네코 경기장을 보수해야 한다."라는 충고를 하지만, 그리스 정부는 그의 말을 듣지 않았고 결국 1896년 아테네 올림픽 준비를 위해 파나티네코 경기장은 두 번이나 정비해야 했다. 1회 대회 정식종목으로는 9종목이 있었는데 육상, 사이클, 펜싱, 체조, 사격, 수영, 테니스, 역도, 레슬링이 있었으며, 조정도 정식종목이었으나 매우 나쁜 날씨로 인해 조정 경기는 취소되었다. 펜싱 경기는 역사적 건물인 자피온(에반젤리스 자파스의 이름을 딴 것이다)에서 열렸다. 그리스의 관리들과 국민들은 올림픽 경기 개최에 열광적이었다. 많은 선수들이 이에 동감하면서 앞으로도 올림픽 대회를 아테네에서 영구히 개최해야 한다고 요구하기까지 하였다. 그러나 국제올림픽위원회(IOC)는 근대 올림픽은 순환 개최로 열리는 세계적인 행사가 되어야 한다고 생각했다. 결국 2회 올림픽은 프랑스 파리에서 열기로 결정되었다.  \n#### 변화와 발전  \n1896년 올림픽 대회의 성공을 이어서 개최된 두 번째 올림픽인 1900년 올림픽에서는 올림픽의 존폐여부를 위협받는 지경에 이르게 되었다. 1900년에 파리와 1904년에 세인트루이스에서 열린 올림픽은 하필이면 엑스포와 시간과 장소가 겹치는 바람에 빛을 바래게 된다. 1904년 대회를 예로 들면 650명의 선수단이 참가했지만 그중 580명은 미국국적을 가진 사람이었다. 1900년과 1904년의 두 올림픽 대회는 역대 올림픽중에 최저점을 기록한다. 올림픽은 1906년 올림픽이 아테네에서 개최되었을 때 다시 일어서게 된다. 또 다른 성공적인 올림픽은 그리스 올림픽 협회가 조직했으며 세 차례나 올림픽을 치른 경기장에서 개최되었다. 이 경기는 비공식 올림픽이긴 했지만 세계적으로 상당한 참가자들을 불러 모았으며 대중들에게 큰 재미를 갖다주었다. 이 때를 시작으로 올림픽의 인기와 번영이 시작되었다.',
 "올림픽 경기 종목은 총 33개부문 52개 종목에서 약 400개의 경기로 이루어져있다. 예를 들어서 하계 올림픽 부문인 레슬링은 자유형과 그레코로만형의 두 종목으로 나뉜다. 여기에서 10경기는 남자부, 4경기는 여자부로 열리며 분류기준은 체중이다. 하계 올림픽은 26개, 동계 올림픽은 7개 부문으로 이루어져있다. 하계 올림픽에서는 육상, 수영, 펜싱, 체조가 1회 대회때부터 한번도 빠짐없이 정식종목이었으며, 동계 올림픽에서는 크로스컨트리, 피겨 스케이팅, 아이스 하키, 노르딕 복합, 스키 점프, 스피드 스케이팅이 1924년 동계 올림픽부터 빠짐없이 정식종목이었다. 배드민턴, 농구, 배구와 같은 정식종목들은 처음에는 시범종목이었으며 그 후에 정식종목으로 승인 되었다. 야구처럼 예전에는 정식종목 이었지만 지금은 정식 종목에서 빠진 종목도 있다.  \n각 올림픽 종목들은 IOC로부터 승인을 받은 국제경기연맹의 관리를 받는다. 35개의 연맹이 IOC에서 승인을 받았으며, 승인을 받았지만 현재 정식종목이 아닌 종목을 감독하는 연맹도 있다. IOC의 승인을 받았지만 올림픽 종목이 아닌 스포츠들은 올림픽 종목으로 고려되지는 않으나, 올림픽이 끝난 후 처음으로 열리는 IOC총회 때마다 정식종목이 되도록 신청을 할 수는 있다. IOC 총회 때 정식종목 선정은 총회에 참석중인 IOC위원들의 투표를 통해 이루어지며, 재적 위원 수의 과반수 이상 찬성표를 얻어야 정식종목으로 인정을 받는다. IOC의 승인을 받은 스포츠이나 찬성표를 받지 못해 정식종목이 되지 못한 스포츠로는 체스와 서핑과 같은 것이 있다.  \n2004년 10월과 11월에 IOC는 '올림픽 프로그램 위원회'(Olympic Programme Commission)를 설립했다. 여기서는 올림픽 종목과 올림픽 종목이 아닌 스포츠를 모두 재검토하는 일을 한다. 이 위원회의 목표는 올림픽 종목에 더 체계적으로 다가가는 것이다. 위원회에서는 우선적으로 올림픽 종목으로 포함되기 위해서는 7개의 기준을 충족시켜야 한다고 말한다. 이 7개의 기준은 역사, 전통, 보편성, 인기도와 잠재성, 선수의 건강, 연맹의 스포츠를 관리할만한 능력, 스포츠를 여는 데에 필요한 비용이다. 예를 들면 2012년 하계 올림픽의 정식종목 후보에 7개 조건을 포함한 비(非)올림픽 스포츠가 올랐고 그 내용은, 골프, 가라테, 럭비, 인라인 스케이팅, 스쿼시였다. 이 스포츠들은 IOC 상임이사회에서 재검토되어 2005년 7월에 열린 싱가포르 총회에서 최종 결정하기로 했다. 결국 5개 중 2개(가라테와 스쿼시) 가 최종 후보로 올라왔으나 가라테와 스쿼시 둘 다 2/3의 미만의 찬성표로 정식종목이 되지는 못한다. 그 후 2016년 올림픽 정식종목에는 7개의 스포츠가 정식종목 신청을 했는데, 내용은 가라테, 골프, 스쿼시, 야구, 소프트볼, 7인제 럭비, 인라인 스케이팅이었다. 2009년 8월 13일, 신청된 7개의 스포츠 중 단 2개만 최종후보로 선정되었는데, 이는 7인제 럭비와 골프였다. 같은해인 2009년 10월에 열린 IOC 총회에서 골프와 럭비는 과반수 이상의 득표를 얻어서 2016년 하계 올림픽과 2020년 하계 올림픽의 정식종목으로 채택되었다.  \n2002년에 열린 제114차 IOC 총회에서는 하계 올림픽 종목은 최대 28부문 301개 경기에 10,500명이 참가하는 것으로 제한하기로 결정했다. 그 후 3년 뒤인 제117차 IOC 총회에서는 정식종목이었던 야구와 소프트볼을 정식 종목에서 제외시킨다. 이 결과에 대한 이견이 없었으므로 2012년 올림픽 때는 26개부문에서 경기가 열린다. 2016년과 2020년 올림픽 때는 럭비와 골프가 추가되어 다시 28개부문에서 경기가 열린다.",
 '베를린에서 열렸던 1936년 하계 올림픽은 전 세계가 아닌 독일 내에서만의 방송이지만 텔레비전으로 방송한 첫 번째 올림픽이었다. 1956년 동계 올림픽은 올림픽을 전 세계적으로 중계 방송한 첫 번째 올림픽이었으며, 1960년 동계 올림픽에서는 중계권을 어느 특정한 방송사에 판매한첫 번째 올림픽이다. 그 후 수십 년간 올림픽은 냉전중인 국가들의 이데올로기 선전의 장이 되었다. 강대국들은 정치 주권을 위해 IOC(국제 올림픽 위원회)를 조종했으며, IOC는 중계권 판매를 통해 이익을 높이고자 하였다. 중계권의 판매는 올림픽을 전 세계적으로 알리는 데 큰 기여를 했으며, 그로 인해 텔레비전의 광고 시간을 사는 광고주들에게 경쟁을 유발하여 IOC는 더욱더 많은 이익을 얻게 되었다. 이는 IOC에게 있는 중계권을 비롯한 수많은 권리들에 지불해야 할 금액들이 앞으로도 지속적으로 늘어나게 됨을 의미한다. 예를 들면 1998년 동계 올림픽 중계권을 사는 데 CBS는 3억 7500만 달러를 지불했지만 2000~2012년 올림픽의 중계권을 따내는 데 NBC는 35억 달러나 지불해야 했다.  \n올림픽 시청자들 또한 1960년대부터 기하급수적으로 증가했다. 1968년 하계 올림픽을 텔레비전으로 시청한 사람들은 6억 명으로 추측되었고, 1984년 하계 올림픽을 시청한 사람들은 9억 명으로 늘어났으며, 1992년 하계 올림픽은 약 35억 명이 시청한 것으로 추측되고 있다. 하지만 NBC의 조사에 의하면 시드니에서 열린 2000년 하계 올림픽은 1968년부터 개최된 올림픽 중에서 가장 적은 수의 사람들이 시청한 것으로 조사되었다. 시청자 수 감소의 원인으로 크게 두 가지가 지목되는데, 그중 하나는 케이블 채널 간의 경쟁이 심화된 것이고, 다른 하나는 실시간으로 경기 영상과 결과를 보여주는 인터넷의 대중화이다. 이러한 원인 분석에도 불구하고 텔레비전 방송국들은 아직도 지연방송에 의존하고 있다. 시청률 감소를 다르게 표현하자면 텔레비전 방송국에서는 광고 시간을 예전보다 싼 가격에 제공할 수밖에 없다는 것을 의미하기도 한다. 텔레비전 방송국들은 국제 올림픽 위원회에게 많은 방송 비용과 인터넷의 발달로 인한 케이블의 치열한 경쟁을 이유로 엄청난 중계권 가격을 조금 낮춰달라고 요구하고 있다. 결국 IOC는 올림픽 프로그램 진행 시간을 상당 부분 변경하게 된다. 예를 들면 하계 올림픽 때 체조종목은 밤 7시에서 9시까지 하는 것으로 바뀌었으며, 갈라쇼는 흥미를 높이는 데에 초점을 맞추게 되었다. 또한 IOC는 수영과 다이빙 종목의 시간은 늘렸는데, 이 종목은 텔레비전 시청자들 중 가장 인기가 있는 종목 중 하나이기 때문이다. 이는 미국 방송국들의 로비가 올림픽 종목들의 일정 시간까지도 미국의 텔레비전 황금시간대에 맞춰서 변경될 수 있음을 의미하는 것이었다. 이 변화는 장점과 단점이 혼재되어 있고, 그 예로 유럽에서 열렸던 2006년 동계 올림픽의 시청률은 미국 솔트레이크 시티에서 열렸던 2002년 동계 올림픽과 비교해보면 확연히 낮았으며 또한 베이징에서 열렸던 2008년 하계 올림픽의 시청자는 급격히 늘어났다.',
 "프로 NHL선수들은 1998년부터 아이스 하키종목에 출전할 수 있게 되었다. (나가노 올림픽 결승전 러시아 vs 체코).  \n영국 명문 공립 학교의 이념은 쿠베르탱에게 큰 영향을 끼쳤다. 영국 공립 학교는 스포츠를 교육의 중요한 부분이라 생각해서 '건전한 신체에 건전한 정신을'이라는 의미를 가진 라틴어 mens sana in corpore sano를 표어로 삼았다. 이 이념에 의하면 신사들은 특정한 분야에서만 우수해서는 안되고 모든 분야에서 고르게 잘해야 하고, 공정한 결과에는 승복해야 하며, 연습이나 훈련은 속이는 것과 마찬가지로 여겼다. 전문적으로 스포츠를 연습한 사람은 취미로 연습한 사람에 비해 공평하지 않다고 생각한 것이다.  \n현대 올림픽에서는 프로 선수의 참가 불허가 많은 분쟁을 가져왔다. 1912년 하계 올림픽의 근대 5종 경기와 10종 경기에서 우승한 짐 소프는 올림픽에 나가기 전에 준프로야구선수로 활동했다는 게 나중에 밝혀져 메달이 박탈되었다. 소프는 후에 동정적 여론의 힘을 업고 1983년에 메달을 돌려받게 된다. 1936년 동계 올림픽 때 스위스와 오스트리아 스키선수들은 돈을 벌기 위해 스포츠를 했는데 이러한 행동이 아마추어 정신에 위배된다고 결정되어 그들은 스키종목에 참가할 수 없었다.  \n20세기에 이르러서 계급구조가 붕괴되면서 이른바 귀족적인 신사라는 아마추어 선수에 대한 정의는 시대에 뒤처지는 말이 되게 된다. 일부 국가들은 '정식 아마추어 선수'를 '키워서' 순수한 아마추어 정신을 벗어나고 있었고, 자신이 내는 비용으로 연습하는 선수들의 불리함에 대한 목소리가 나오기 시작했다. 하지만 IOC는 아마추어 정신에 관한 입장을 고수했다. 1970년대 초에는 아마추어 정신이 올림픽헌장에서 폐지되어야 한다는 말이 나오기 시작했다. 결국 프로선수들의 출전은 국제경기연맹(IF)에서 결정짓도록 되었다. 2008년 기준으로 아마추어 선수만 출전하고 있는 올림픽 종목은 복싱이 유일하며 남자 축구에서는 나이가 23세 이상인 선수를 3명까지만 선발할 수 있다. 이는 아마추어 정신을 지키기 위한 일환으로 볼 수 있다."]

In [14]:
from ragas.testset import TestsetGenerator
from ragas.llms import LangchainLLMWrapper
from ragas.embeddings import LangchainEmbeddingsWrapper

from langchain_openai import ChatOpenAI, OpenAIEmbeddings

# gpt-5 버전은 사용할 수없다. (temperature 설정 문제가 있다.)
generator_llm = LangchainLLMWrapper(ChatOpenAI(model="gpt-4.1")) #Langchain모델을 RAGAS에서 사용할 수있도록 변환(Wrapping)
generator_embeddings = LangchainEmbeddingsWrapper(OpenAIEmbeddings(model="text-embedding-3-large"))

generator = TestsetGenerator(
    llm=generator_llm,
    embedding_model=generator_embeddings,
    llm_context="데이터셋은 반드시 한국어로 작성한다. 데이터셋은 JSON 문법을 꼭 지켜서 작성한다.\
특히 구두점은 꼭 지켜야 한다. Document에 JSON 문법에 맞지 않는 표현이 있으면 반드시 수정해서 처리한다."  
    # 질문/답변 생성할 때 llm에 전달할 추가 system prompt를 설정.
)

C:\Users\82107\AppData\Local\Temp\ipykernel_356236\1878484181.py:8: DeprecationWarning: LangchainLLMWrapper is deprecated and will be removed in a future version. Use llm_factory instead: from openai import OpenAI; from ragas.llms import llm_factory; llm = llm_factory('gpt-4o-mini', client=OpenAI(api_key='...'))
  generator_llm = LangchainLLMWrapper(ChatOpenAI(model="gpt-4.1")) #Langchain모델을 RAGAS에서 사용할 수있도록 변환(Wrapping)
C:\Users\82107\AppData\Local\Temp\ipykernel_356236\1878484181.py:9: DeprecationWarning: LangchainEmbeddingsWrapper is deprecated and will be removed in a future version. Use the modern embedding providers instead: embedding_factory('openai', model='text-embedding-3-small', client=openai_client) or from ragas.embeddings import OpenAIEmbeddings, GoogleEmbeddings, HuggingFaceEmbeddings
  generator_embeddings = LangchainEmbeddingsWrapper(OpenAIEmbeddings(model="text-embedding-3-large"))

In [15]:
testset = generator.generate_with_chunks(
    docs, testset_size=10  # context 내용, 테스트데이터셋 몇개를 만들지.
)

Applying SummaryExtractor:   0%|          | 0/5 [00:00<?, ?it/s]

Applying CustomNodeFilter:   0%|          | 0/5 [00:00<?, ?it/s]

Node 648db3f7-f794-46cb-93d8-db534d1d34e0 does not have a summary. Skipping filtering.
Node 82786a2f-0b07-4815-90de-5f6a204cef2c does not have a summary. Skipping filtering.
Node 258b28f9-0c7b-4221-9782-c3afc667a598 does not have a summary. Skipping filtering.
Node ad2994d8-c8c1-479b-ac5d-164a2aea8ef4 does not have a summary. Skipping filtering.
Node 6792a167-18c2-4a91-bdd0-3b2f6f4760ef does not have a summary. Skipping filtering.

Applying EmbeddingExtractor:   0%|          | 0/5 [00:00<?, ?it/s]

Applying ThemesExtractor:   0%|          | 0/5 [00:00<?, ?it/s]

Applying NERExtractor:   0%|          | 0/5 [00:00<?, ?it/s]

Applying CosineSimilarityBuilder:   0%|          | 0/1 [00:00<?, ?it/s]

Applying OverlapScoreBuilder:   0%|          | 0/1 [00:00<?, ?it/s]

Skipping multi_hop_abstract_query_synthesizer due to unexpected error: No relationships match the provided condition. Cannot form clusters.

Generating personas:   0%|          | 0/3 [00:00<?, ?it/s]

Generating Scenarios:   0%|          | 0/2 [00:00<?, ?it/s]

Generating Samples:   0%|          | 0/11 [00:00<?, ?it/s]

In [16]:
print(type(testset))
testset

<class 'ragas.testset.synthesizers.testset_schema.Testset'>

Testset(samples=[TestsetSample(eval_sample=SingleTurnSample(user_input='2012 런던 올림픽 마스코트 뭐에요?', retrieved_contexts=None, reference_contexts=['올림픽에서는 올림픽 헌장에 구체적으로 나타난 이상이나 철학을 표현하는 상징을 사용한다. 오륜기로 잘 알려져 있는 올림픽기는 5개의 둥근 고리가 얽혀있으며 각 원마다 5대륙을 상징한다.(남아메리카와 북아메리카는 아메리카로 합쳐 있다.) 파랑, 노랑, 검정, 초록, 빨간 고리에 흰색 바탕은 올림픽 기를 나타낸다. 이 색들이 선택된 이유는 모든 국기에서 적어도 이 5개의 색 중 하나를 가지고 있기 때문이다. 올림픽 기가 채택된 것은 1914년이지만 1920년 하계 올림픽 때부터 사용되기 시작했다. 이 때부터 올림픽 기는 올림픽을 기념하기 위해 올림픽이 열리는 기간 동안 게양한다.  \n올림픽 표어는 라틴어로 Citius, Altius, Fortius이며 "더 빨리, 더 높게, 더 힘차게"라는 뜻이다. 쿠베르탱의 이상은 올림픽 선서에 더 잘 나타나 있다.  \n- 올림픽 선서 중에서\n- "인생에서 가장 중요한 것은 승리가 아니라 이를 위해 분투하는 것이고, 올림픽에서 가장 중요한 것 역시 승리가 아니라 참가 자체에 의의가 있다. 우리에게 있어 본질은 정복하는 것이 아니라 잘 싸우는 것이다."  \n매 올림픽이 시작되기 몇 개월전에 고대 그리스에서 제사를 지냈던 그리스의 올림피아에서 올림픽 성화가 채화된다. 여자 배우가 마치 여자 사제인 것처럼 연기해서 태양광선을 포물면 거울(오목 거울의 하나)의 안쪽에 집중시켜서 점화한다. 그 후에 여자는 첫 번째 성화 봉송 주자에게 성화를 넘기고 개최도시의 개막식이 열리는 올림픽 경기장까지 여러 사람의 손을 거쳐서 올림픽 성화는 전달된다. 올림픽 상징으로서의 올림픽 성화는 1928년 하계 올림픽 때 이미 있었지만, 성화 봉송은 1936년 하계 올림픽때 독일 정부의 나치즘 선전의 일환으로 처음 시행된 것이 그 유래이다.  \n개최도시의 문화적 상징물을 동물이나 사람의 형상으로 나타내는 올림픽 마스코트는 1968년에 처음 소개되었다. 이후 1980년 하계 올림픽 때 러시아 아기곰인 미샤가 국제적인 스타의 자리에 오르며, 올림픽의 상징에 있어 마스코트가 한층 더 중요한 역할을 하게 되었다. 가장 최근의 하계 올림픽 마스코트는 2012 런던 올림픽의 마스코트인 웬록으로, 웬록은 영국 중서부 슈롭셔의 작은 마을 이름이며 이곳은 근대 올림픽 창시자인 쿠베르탱이 올림픽을 창안했던 곳이다. 또한 가장 최근의 동계 올림픽 마스코트로는 2010년 동계 올림픽의 마스코트인 미가, 콰치, 수미가 있다.'], retrieved_context_ids=None, reference_context_ids=None, response=None, multi_responses=None, reference='2012 런던 올림픽의 마스코트는 웬록으로, 웬록은 영국 중서부 슈롭셔의 작은 마을 이름이며 이곳은 근대 올림픽 창시자인 쿠베르탱이 올림픽을 창안했던 곳이다.', rubrics=None, persona_name='Olympic Enthusiast', query_style='MISSPELLED', query_length='SHORT'), synthesizer_name='single_hop_specific_query_synthesizer'), TestsetSample(eval_sample=SingleTurnSample(user_input='파나티네코 경기장은 1896년 아테네 올림픽을 준비하는 과정에서 어떤 역할을 했으며, 그 보수와 정비에 관한 이야기는 무엇인가요?', retrieved_contexts=None, reference_contexts=['1859년 자파스 올림픽에 참가한 선수의 수는 250명을 넘지 못했다. 에방겔리스 자파스는 "지난 자파스 올림픽을 포함, 1896년에 개최될 2번째 올림픽을 위해 파나티네코 경기장을 보수해야 한다."라는 충고를 하지만, 그리스 정부는 그의 말을 듣지 않았고 결국 1896년 아테네 올림픽 준비를 위해 파나티네코 경기장은 두 번이나 정비해야 했다. 1회 대회 정식종목으로는 9종목이 있었는데 육상, 사이클, 펜싱, 체조, 사격, 수영, 테니스, 역도, 레슬링이 있었으며, 조정도 정식종목이었으나 매우 나쁜 날씨로 인해 조정 경기는 취소되었다. 펜싱 경기는 역사적 건물인 자피온(에반젤리스 자파스의 이름을 딴 것이다)에서 열렸다. 그리스의 관리들과 국민들은 올림픽 경기 개최에 열광적이었다. 많은 선수들이 이에 동감하면서 앞으로도 올림픽 대회를 아테네에서 영구히 개최해야 한다고 요구하기까지 하였다. 그러나 국제올림픽위원회(IOC)는 근대 올림픽은 순환 개최로 열리는 세계적인 행사가 되어야 한다고 생각했다. 결국 2회 올림픽은 프랑스 파리에서 열기로 결정되었다.  \n#### 변화와 발전  \n1896년 올림픽 대회의 성공을 이어서 개최된 두 번째 올림픽인 1900년 올림픽에서는 올림픽의 존폐여부를 위협받는 지경에 이르게 되었다. 1900년에 파리와 1904년에 세인트루이스에서 열린 올림픽은 하필이면 엑스포와 시간과 장소가 겹치는 바람에 빛을 바래게 된다. 1904년 대회를 예로 들면 650명의 선수단이 참가했지만 그중 580명은 미국국적을 가진 사람이었다. 1900년과 1904년의 두 올림픽 대회는 역대 올림픽중에 최저점을 기록한다. 올림픽은 1906년 올림픽이 아테네에서 개최되었을 때 다시 일어서게 된다. 또 다른 성공적인 올림픽은 그리스 올림픽 협회가 조직했으며 세 차례나 올림픽을 치른 경기장에서 개최되었다. 이 경기는 비공식 올림픽이긴 했지만 세계적으로 상당한 참가자들을 불러 모았으며 대중들에게 큰 재미를 갖다주었다. 이 때를 시작으로 올림픽의 인기와 번영이 시작되었다.'], retrieved_context_ids=None, reference_context_ids=None, response=None, multi_responses=None, reference='에방겔리스 자파스는 1896년에 개최될 2번째 올림픽을 위해 파나티네코 경기장을 보수해야 한다고 충고했으나, 그리스 정부는 그의 말을 듣지 않았습니다. 결국 1896년 아테네 올림픽 준비를 위해 파나티네코 경기장은 두 번이나 정비해야 했습니다.', rubrics=None, persona_name='Olympic Enthusiast', query_style='PERFECT_GRAMMAR', query_length='LONG'), synthesizer_name='single_hop_specific_query_synthesizer'), TestsetSample(eval_sample=SingleTurnSample(user_input='올림픽 프로그람 커미션은 뭐하는 기구에요?', retrieved_contexts=None, reference_contexts=["올림픽 경기 종목은 총 33개부문 52개 종목에서 약 400개의 경기로 이루어져있다. 예를 들어서 하계 올림픽 부문인 레슬링은 자유형과 그레코로만형의 두 종목으로 나뉜다. 여기에서 10경기는 남자부, 4경기는 여자부로 열리며 분류기준은 체중이다. 하계 올림픽은 26개, 동계 올림픽은 7개 부문으로 이루어져있다. 하계 올림픽에서는 육상, 수영, 펜싱, 체조가 1회 대회때부터 한번도 빠짐없이 정식종목이었으며, 동계 올림픽에서는 크로스컨트리, 피겨 스케이팅, 아이스 하키, 노르딕 복합, 스키 점프, 스피드 스케이팅이 1924년 동계 올림픽부터 빠짐없이 정식종목이었다. 배드민턴, 농구, 배구와 같은 정식종목들은 처음에는 시범종목이었으며 그 후에 정식종목으로 승인 되었다. 야구처럼 예전에는 정식종목 이었지만 지금은 정식 종목에서 빠진 종목도 있다.  \n각 올림픽 종목들은 IOC로부터 승인을 받은 국제경기연맹의 관리를 받는다. 35개의 연맹이 IOC에서 승인을 받았으며, 승인을 받았지만 현재 정식종목이 아닌 종목을 감독하는 연맹도 있다. IOC의 승인을 받았지만 올림픽 종목이 아닌 스포츠들은 올림픽 종목으로 고려되지는 않으나, 올림픽이 끝난 후 처음으로 열리는 IOC총회 때마다 정식종목이 되도록 신청을 할 수는 있다. IOC 총회 때 정식종목 선정은 총회에 참석중인 IOC위원들의 투표를 통해 이루어지며, 재적 위원 수의 과반수 이상 찬성표를 얻어야 정식종목으로 인정을 받는다. IOC의 승인을 받은 스포츠이나 찬성표를 받지 못해 정식종목이 되지 못한 스포츠로는 체스와 서핑과 같은 것이 있다.  \n2004년 10월과 11월에 IOC는 '올림픽 프로그램 위원회'(Olympic Programme Commission)를 설립했다. 여기서는 올림픽 종목과 올림픽 종목이 아닌 스포츠를 모두 재검토하는 일을 한다. 이 위원회의 목표는 올림픽 종목에 더 체계적으로 다가가는 것이다. 위원회에서는 우선적으로 올림픽 종목으로 포함되기 위해서는 7개의 기준을 충족시켜야 한다고 말한다. 이 7개의 기준은 역사, 전통, 보편성, 인기도와 잠재성, 선수의 건강, 연맹의 스포츠를 관리할만한 능력, 스포츠를 여는 데에 필요한 비용이다. 예를 들면 2012년 하계 올림픽의 정식종목 후보에 7개 조건을 포함한 비(非)올림픽 스포츠가 올랐고 그 내용은, 골프, 가라테, 럭비, 인라인 스케이팅, 스쿼시였다. 이 스포츠들은 IOC 상임이사회에서 재검토되어 2005년 7월에 열린 싱가포르 총회에서 최종 결정하기로 했다. 결국 5개 중 2개(가라테와 스쿼시) 가 최종 후보로 올라왔으나 가라테와 스쿼시 둘 다 2/3의 미만의 찬성표로 정식종목이 되지는 못한다. 그 후 2016년 올림픽 정식종목에는 7개의 스포츠가 정식종목 신청을 했는데, 내용은 가라테, 골프, 스쿼시, 야구, 소프트볼, 7인제 럭비, 인라인 스케이팅이었다. 2009년 8월 13일, 신청된 7개의 스포츠 중 단 2개만 최종후보로 선정되었는데, 이는 7인제 럭비와 골프였다. 같은해인 2009년 10월에 열린 IOC 총회에서 골프와 럭비는 과반수 이상의 득표를 얻어서 2016년 하계 올림픽과 2020년 하계 올림픽의 정식종목으로 채택되었다.  \n2002년에 열린 제114차 IOC 총회에서는 하계 올림픽 종목은 최대 28부문 301개 경기에 10,500명이 참가하는 것으로 제한하기로 결정했다. 그 후 3년 뒤인 제117차 IOC 총회에서는 정식종목이었던 야구와 소프트볼을 정식 종목에서 제외시킨다. 이 결과에 대한 이견이 없었으므로 2012년 올림픽 때는 26개부문에서 경기가 열린다. 2016년과 2020년 올림픽 때는 럭비와 골프가 추가되어 다시 28개부문에서 경기가 열린다."], retrieved_context_ids=None, reference_context_ids=None, response=None, multi_responses=None, reference='올림픽 프로그램 위원회는 올림픽 종목과 올림픽 종목이 아닌 스포츠를 모두 재검토하는 일을 하며, 올림픽 종목에 더 체계적으로 다가가는 것이 목표입니다. 이 위원회에서는 올림픽 종목으로 포함되기 위해 7개의 기준을 충족해야 한다고 말합니다.', rubrics=None, persona_name='Olympic History Enthusiast', query_style='MISSPELLED', query_length='MEDIUM'), synthesizer_name='single_hop_specific_query_synthesizer'), TestsetSample(eval_sample=SingleTurnSample(user_input='1936년 하계 올림픽의 방송 관련 특징은 무엇인가요?', retrieved_contexts=None, reference_contexts=['베를린에서 열렸던 1936년 하계 올림픽은 전 세계가 아닌 독일 내에서만의 방송이지만 텔레비전으로 방송한 첫 번째 올림픽이었다. 1956년 동계 올림픽은 올림픽을 전 세계적으로 중계 방송한 첫 번째 올림픽이었으며, 1960년 동계 올림픽에서는 중계권을 어느 특정한 방송사에 판매한첫 번째 올림픽이다. 그 후 수십 년간 올림픽은 냉전중인 국가들의 이데올로기 선전의 장이 되었다. 강대국들은 정치 주권을 위해 IOC(국제 올림픽 위원회)를 조종했으며, IOC는 중계권 판매를 통해 이익을 높이고자 하였다. 중계권의 판매는 올림픽을 전 세계적으로 알리는 데 큰 기여를 했으며, 그로 인해 텔레비전의 광고 시간을 사는 광고주들에게 경쟁을 유발하여 IOC는 더욱더 많은 이익을 얻게 되었다. 이는 IOC에게 있는 중계권을 비롯한 수많은 권리들에 지불해야 할 금액들이 앞으로도 지속적으로 늘어나게 됨을 의미한다. 예를 들면 1998년 동계 올림픽 중계권을 사는 데 CBS는 3억 7500만 달러를 지불했지만 2000~2012년 올림픽의 중계권을 따내는 데 NBC는 35억 달러나 지불해야 했다.  \n올림픽 시청자들 또한 1960년대부터 기하급수적으로 증가했다. 1968년 하계 올림픽을 텔레비전으로 시청한 사람들은 6억 명으로 추측되었고, 1984년 하계 올림픽을 시청한 사람들은 9억 명으로 늘어났으며, 1992년 하계 올림픽은 약 35억 명이 시청한 것으로 추측되고 있다. 하지만 NBC의 조사에 의하면 시드니에서 열린 2000년 하계 올림픽은 1968년부터 개최된 올림픽 중에서 가장 적은 수의 사람들이 시청한 것으로 조사되었다. 시청자 수 감소의 원인으로 크게 두 가지가 지목되는데, 그중 하나는 케이블 채널 간의 경쟁이 심화된 것이고, 다른 하나는 실시간으로 경기 영상과 결과를 보여주는 인터넷의 대중화이다. 이러한 원인 분석에도 불구하고 텔레비전 방송국들은 아직도 지연방송에 의존하고 있다. 시청률 감소를 다르게 표현하자면 텔레비전 방송국에서는 광고 시간을 예전보다 싼 가격에 제공할 수밖에 없다는 것을 의미하기도 한다. 텔레비전 방송국들은 국제 올림픽 위원회에게 많은 방송 비용과 인터넷의 발달로 인한 케이블의 치열한 경쟁을 이유로 엄청난 중계권 가격을 조금 낮춰달라고 요구하고 있다. 결국 IOC는 올림픽 프로그램 진행 시간을 상당 부분 변경하게 된다. 예를 들면 하계 올림픽 때 체조종목은 밤 7시에서 9시까지 하는 것으로 바뀌었으며, 갈라쇼는 흥미를 높이는 데에 초점을 맞추게 되었다. 또한 IOC는 수영과 다이빙 종목의 시간은 늘렸는데, 이 종목은 텔레비전 시청자들 중 가장 인기가 있는 종목 중 하나이기 때문이다. 이는 미국 방송국들의 로비가 올림픽 종목들의 일정 시간까지도 미국의 텔레비전 황금시간대에 맞춰서 변경될 수 있음을 의미하는 것이었다. 이 변화는 장점과 단점이 혼재되어 있고, 그 예로 유럽에서 열렸던 2006년 동계 올림픽의 시청률은 미국 솔트레이크 시티에서 열렸던 2002년 동계 올림픽과 비교해보면 확연히 낮았으며 또한 베이징에서 열렸던 2008년 하계 올림픽의 시청자는 급격히 늘어났다.'], retrieved_context_ids=None, reference_context_ids=None, response=None, multi_responses=None, reference='베를린에서 열렸던 1936년 하계 올림픽은 전 세계가 아닌 독일 내에서만의 방송이지만 텔레비전으로 방송한 첫 번째 올림픽이었다.', rubrics=None, persona_name='Olympic Enthusiast', query_style='WEB_SEARCH_LIKE', query_length='SHORT'), synthesizer_name='single_hop_specific_query_synthesizer'), TestsetSample(eval_sample=SingleTurnSample(user_input='NHL 선수들 언제부터 올림픽 아이스 하키에 나갈 수 있었는지, 그리고 그거랑 올림픽 아마추어 정신이랑 무슨 관계 있는지 설명해줘요. 그리고 NHL 선수들 출전 허용되기 전에는 어떤 논란 있었는지도 궁금해요.', retrieved_contexts=None, reference_contexts=["프로 NHL선수들은 1998년부터 아이스 하키종목에 출전할 수 있게 되었다. (나가노 올림픽 결승전 러시아 vs 체코).  \n영국 명문 공립 학교의 이념은 쿠베르탱에게 큰 영향을 끼쳤다. 영국 공립 학교는 스포츠를 교육의 중요한 부분이라 생각해서 '건전한 신체에 건전한 정신을'이라는 의미를 가진 라틴어 mens sana in corpore sano를 표어로 삼았다. 이 이념에 의하면 신사들은 특정한 분야에서만 우수해서는 안되고 모든 분야에서 고르게 잘해야 하고, 공정한 결과에는 승복해야 하며, 연습이나 훈련은 속이는 것과 마찬가지로 여겼다. 전문적으로 스포츠를 연습한 사람은 취미로 연습한 사람에 비해 공평하지 않다고 생각한 것이다.  \n현대 올림픽에서는 프로 선수의 참가 불허가 많은 분쟁을 가져왔다. 1912년 하계 올림픽의 근대 5종 경기와 10종 경기에서 우승한 짐 소프는 올림픽에 나가기 전에 준프로야구선수로 활동했다는 게 나중에 밝혀져 메달이 박탈되었다. 소프는 후에 동정적 여론의 힘을 업고 1983년에 메달을 돌려받게 된다. 1936년 동계 올림픽 때 스위스와 오스트리아 스키선수들은 돈을 벌기 위해 스포츠를 했는데 이러한 행동이 아마추어 정신에 위배된다고 결정되어 그들은 스키종목에 참가할 수 없었다.  \n20세기에 이르러서 계급구조가 붕괴되면서 이른바 귀족적인 신사라는 아마추어 선수에 대한 정의는 시대에 뒤처지는 말이 되게 된다. 일부 국가들은 '정식 아마추어 선수'를 '키워서' 순수한 아마추어 정신을 벗어나고 있었고, 자신이 내는 비용으로 연습하는 선수들의 불리함에 대한 목소리가 나오기 시작했다. 하지만 IOC는 아마추어 정신에 관한 입장을 고수했다. 1970년대 초에는 아마추어 정신이 올림픽헌장에서 폐지되어야 한다는 말이 나오기 시작했다. 결국 프로선수들의 출전은 국제경기연맹(IF)에서 결정짓도록 되었다. 2008년 기준으로 아마추어 선수만 출전하고 있는 올림픽 종목은 복싱이 유일하며 남자 축구에서는 나이가 23세 이상인 선수를 3명까지만 선발할 수 있다. 이는 아마추어 정신을 지키기 위한 일환으로 볼 수 있다."], retrieved_context_ids=None, reference_context_ids=None, response=None, multi_responses=None, reference="프로 NHL선수들은 1998년부터 아이스 하키종목에 출전할 수 있게 되었다. 현대 올림픽에서는 프로 선수의 참가 불허가 많은 분쟁을 가져왔다. 1912년 하계 올림픽의 근대 5종 경기와 10종 경기에서 우승한 짐 소프는 올림픽에 나가기 전에 준프로야구선수로 활동했다는 게 나중에 밝혀져 메달이 박탈되었다. 1936년 동계 올림픽 때 스위스와 오스트리아 스키선수들은 돈을 벌기 위해 스포츠를 했는데 이러한 행동이 아마추어 정신에 위배된다고 결정되어 그들은 스키종목에 참가할 수 없었다. 20세기에 이르러서 계급구조가 붕괴되면서 이른바 귀족적인 신사라는 아마추어 선수에 대한 정의는 시대에 뒤처지는 말이 되게 된다. 일부 국가들은 '정식 아마추어 선수'를 '키워서' 순수한 아마추어 정신을 벗어나고 있었고, 자신이 내는 비용으로 연습하는 선수들의 불리함에 대한 목소리가 나오기 시작했다. 하지만 IOC는 아마추어 정신에 관한 입장을 고수했다. 1970년대 초에는 아마추어 정신이 올림픽헌장에서 폐지되어야 한다는 말이 나오기 시작했다. 결국 프로선수들의 출전은 국제경기연맹(IF)에서 결정짓도록 되었다.", rubrics=None, persona_name='Olympic History Enthusiast', query_style='POOR_GRAMMAR', query_length='LONG'), synthesizer_name='single_hop_specific_query_synthesizer'), TestsetSample(eval_sample=SingleTurnSample(user_input='1936년 하계 올림픽이 텔레비전으로 방송된 첫 번째 올림픽이었다는 점과 이후 올림픽 중계권 판매 및 시청자 수 변화에 어떤 영향을 미쳤는가?', retrieved_contexts=None, reference_contexts=['<1-hop>\n\n베를린에서 열렸던 1936년 하계 올림픽은 전 세계가 아닌 독일 내에서만의 방송이지만 텔레비전으로 방송한 첫 번째 올림픽이었다. 1956년 동계 올림픽은 올림픽을 전 세계적으로 중계 방송한 첫 번째 올림픽이었으며, 1960년 동계 올림픽에서는 중계권을 어느 특정한 방송사에 판매한첫 번째 올림픽이다. 그 후 수십 년간 올림픽은 냉전중인 국가들의 이데올로기 선전의 장이 되었다. 강대국들은 정치 주권을 위해 IOC(국제 올림픽 위원회)를 조종했으며, IOC는 중계권 판매를 통해 이익을 높이고자 하였다. 중계권의 판매는 올림픽을 전 세계적으로 알리는 데 큰 기여를 했으며, 그로 인해 텔레비전의 광고 시간을 사는 광고주들에게 경쟁을 유발하여 IOC는 더욱더 많은 이익을 얻게 되었다. 이는 IOC에게 있는 중계권을 비롯한 수많은 권리들에 지불해야 할 금액들이 앞으로도 지속적으로 늘어나게 됨을 의미한다. 예를 들면 1998년 동계 올림픽 중계권을 사는 데 CBS는 3억 7500만 달러를 지불했지만 2000~2012년 올림픽의 중계권을 따내는 데 NBC는 35억 달러나 지불해야 했다.  \n올림픽 시청자들 또한 1960년대부터 기하급수적으로 증가했다. 1968년 하계 올림픽을 텔레비전으로 시청한 사람들은 6억 명으로 추측되었고, 1984년 하계 올림픽을 시청한 사람들은 9억 명으로 늘어났으며, 1992년 하계 올림픽은 약 35억 명이 시청한 것으로 추측되고 있다. 하지만 NBC의 조사에 의하면 시드니에서 열린 2000년 하계 올림픽은 1968년부터 개최된 올림픽 중에서 가장 적은 수의 사람들이 시청한 것으로 조사되었다. 시청자 수 감소의 원인으로 크게 두 가지가 지목되는데, 그중 하나는 케이블 채널 간의 경쟁이 심화된 것이고, 다른 하나는 실시간으로 경기 영상과 결과를 보여주는 인터넷의 대중화이다. 이러한 원인 분석에도 불구하고 텔레비전 방송국들은 아직도 지연방송에 의존하고 있다. 시청률 감소를 다르게 표현하자면 텔레비전 방송국에서는 광고 시간을 예전보다 싼 가격에 제공할 수밖에 없다는 것을 의미하기도 한다. 텔레비전 방송국들은 국제 올림픽 위원회에게 많은 방송 비용과 인터넷의 발달로 인한 케이블의 치열한 경쟁을 이유로 엄청난 중계권 가격을 조금 낮춰달라고 요구하고 있다. 결국 IOC는 올림픽 프로그램 진행 시간을 상당 부분 변경하게 된다. 예를 들면 하계 올림픽 때 체조종목은 밤 7시에서 9시까지 하는 것으로 바뀌었으며, 갈라쇼는 흥미를 높이는 데에 초점을 맞추게 되었다. 또한 IOC는 수영과 다이빙 종목의 시간은 늘렸는데, 이 종목은 텔레비전 시청자들 중 가장 인기가 있는 종목 중 하나이기 때문이다. 이는 미국 방송국들의 로비가 올림픽 종목들의 일정 시간까지도 미국의 텔레비전 황금시간대에 맞춰서 변경될 수 있음을 의미하는 것이었다. 이 변화는 장점과 단점이 혼재되어 있고, 그 예로 유럽에서 열렸던 2006년 동계 올림픽의 시청률은 미국 솔트레이크 시티에서 열렸던 2002년 동계 올림픽과 비교해보면 확연히 낮았으며 또한 베이징에서 열렸던 2008년 하계 올림픽의 시청자는 급격히 늘어났다.'], retrieved_context_ids=None, reference_context_ids=None, response=None, multi_responses=None, reference='1936년 하계 올림픽은 독일 내에서만이었지만 텔레비전으로 방송된 첫 번째 올림픽이었다. 이후 올림픽은 점차 전 세계적으로 중계 방송이 이루어졌고, 중계권 판매가 이루어지면서 IOC의 이익이 크게 증가하였다. 텔레비전 방송을 통한 올림픽의 전 세계적 홍보는 시청자 수의 기하급수적 증가로 이어졌으며, 1968년 하계 올림픽에는 6억 명, 1984년에는 9억 명, 1992년에는 약 35억 명이 시청한 것으로 추정된다. 그러나 2000년대 들어 케이블 채널 경쟁과 인터넷의 대중화로 시청자 수가 감소하기도 했다. 이러한 변화는 방송국들이 중계권 가격 인하를 요구하게 만들었고, IOC는 올림픽 프로그램의 진행 시간과 인기 종목의 방송 시간을 조정하는 등 여러 변화를 도입하게 되었다.', rubrics=None, persona_name=None, query_style=None, query_length=None), synthesizer_name='multi_hop_specific_query_synthesizer'), TestsetSample(eval_sample=SingleTurnSample(user_input='1960년 동계 올림픽이 중계권을 특정 방송사에 처음으로 판매한 올림픽이었다고 하는데, 이 변화가 이후 올림픽 중계권 가격과 텔레비전 시청자 수, 그리고 올림픽 경기 일정에 어떤 영향을 주었는지 설명해 주세요. 1960년 동계 올림픽과 관련된 변화가 이후 올림픽의 중계권 판매, 광고주 경쟁, 시청률, 그리고 경기 시간 조정에 어떻게 연결되는지 여러 예시와 함께 알려주세요.', retrieved_contexts=None, reference_contexts=['<1-hop>\n\n베를린에서 열렸던 1936년 하계 올림픽은 전 세계가 아닌 독일 내에서만의 방송이지만 텔레비전으로 방송한 첫 번째 올림픽이었다. 1956년 동계 올림픽은 올림픽을 전 세계적으로 중계 방송한 첫 번째 올림픽이었으며, 1960년 동계 올림픽에서는 중계권을 어느 특정한 방송사에 판매한첫 번째 올림픽이다. 그 후 수십 년간 올림픽은 냉전중인 국가들의 이데올로기 선전의 장이 되었다. 강대국들은 정치 주권을 위해 IOC(국제 올림픽 위원회)를 조종했으며, IOC는 중계권 판매를 통해 이익을 높이고자 하였다. 중계권의 판매는 올림픽을 전 세계적으로 알리는 데 큰 기여를 했으며, 그로 인해 텔레비전의 광고 시간을 사는 광고주들에게 경쟁을 유발하여 IOC는 더욱더 많은 이익을 얻게 되었다. 이는 IOC에게 있는 중계권을 비롯한 수많은 권리들에 지불해야 할 금액들이 앞으로도 지속적으로 늘어나게 됨을 의미한다. 예를 들면 1998년 동계 올림픽 중계권을 사는 데 CBS는 3억 7500만 달러를 지불했지만 2000~2012년 올림픽의 중계권을 따내는 데 NBC는 35억 달러나 지불해야 했다.  \n올림픽 시청자들 또한 1960년대부터 기하급수적으로 증가했다. 1968년 하계 올림픽을 텔레비전으로 시청한 사람들은 6억 명으로 추측되었고, 1984년 하계 올림픽을 시청한 사람들은 9억 명으로 늘어났으며, 1992년 하계 올림픽은 약 35억 명이 시청한 것으로 추측되고 있다. 하지만 NBC의 조사에 의하면 시드니에서 열린 2000년 하계 올림픽은 1968년부터 개최된 올림픽 중에서 가장 적은 수의 사람들이 시청한 것으로 조사되었다. 시청자 수 감소의 원인으로 크게 두 가지가 지목되는데, 그중 하나는 케이블 채널 간의 경쟁이 심화된 것이고, 다른 하나는 실시간으로 경기 영상과 결과를 보여주는 인터넷의 대중화이다. 이러한 원인 분석에도 불구하고 텔레비전 방송국들은 아직도 지연방송에 의존하고 있다. 시청률 감소를 다르게 표현하자면 텔레비전 방송국에서는 광고 시간을 예전보다 싼 가격에 제공할 수밖에 없다는 것을 의미하기도 한다. 텔레비전 방송국들은 국제 올림픽 위원회에게 많은 방송 비용과 인터넷의 발달로 인한 케이블의 치열한 경쟁을 이유로 엄청난 중계권 가격을 조금 낮춰달라고 요구하고 있다. 결국 IOC는 올림픽 프로그램 진행 시간을 상당 부분 변경하게 된다. 예를 들면 하계 올림픽 때 체조종목은 밤 7시에서 9시까지 하는 것으로 바뀌었으며, 갈라쇼는 흥미를 높이는 데에 초점을 맞추게 되었다. 또한 IOC는 수영과 다이빙 종목의 시간은 늘렸는데, 이 종목은 텔레비전 시청자들 중 가장 인기가 있는 종목 중 하나이기 때문이다. 이는 미국 방송국들의 로비가 올림픽 종목들의 일정 시간까지도 미국의 텔레비전 황금시간대에 맞춰서 변경될 수 있음을 의미하는 것이었다. 이 변화는 장점과 단점이 혼재되어 있고, 그 예로 유럽에서 열렸던 2006년 동계 올림픽의 시청률은 미국 솔트레이크 시티에서 열렸던 2002년 동계 올림픽과 비교해보면 확연히 낮았으며 또한 베이징에서 열렸던 2008년 하계 올림픽의 시청자는 급격히 늘어났다.'], retrieved_context_ids=None, reference_context_ids=None, response=None, multi_responses=None, reference='1960년 동계 올림픽은 중계권을 어느 특정한 방송사에 판매한 첫 번째 올림픽이었습니다. 이 변화는 이후 올림픽 중계권 판매 방식에 큰 영향을 주었고, 중계권의 판매는 올림픽을 전 세계적으로 알리는 데 큰 기여를 했습니다. 중계권 판매로 인해 텔레비전의 광고 시간을 사는 광고주들 사이에 경쟁이 생겼고, 그 결과 IOC(국제 올림픽 위원회)는 더 많은 이익을 얻게 되었습니다. 예를 들어, 1998년 동계 올림픽 중계권을 CBS가 3억 7500만 달러에 샀고, 2000~2012년 올림픽 중계권은 NBC가 35억 달러에 구매해야 했을 정도로 가격이 크게 올랐습니다. 또한, 1960년대부터 올림픽 시청자 수가 기하급수적으로 증가하여 1968년 하계 올림픽은 6억 명, 1984년 하계 올림픽은 9억 명, 1992년 하계 올림픽은 약 35억 명이 시청한 것으로 추정됩니다. 하지만 2000년 하계 올림픽에서는 케이블 채널 경쟁과 인터넷의 대중화로 시청자 수가 감소하기도 했습니다. 이러한 변화로 인해 방송국들은 광고 단가 하락과 높은 중계권 가격을 이유로 IOC에 가격 인하를 요구했고, IOC는 올림픽 경기 시간까지 미국의 텔레비전 황금시간대에 맞춰 조정하는 등 프로그램 진행 시간을 변경하게 되었습니다. 예를 들어, 체조 종목은 밤 7시에서 9시로, 수영과 다이빙 종목의 시간은 늘렸습니다. 이처럼 1960년 동계 올림픽의 중계권 판매는 이후 올림픽의 중계권 가격 상승, 시청자 수 변화, 광고주 경쟁, 그리고 경기 일정 조정 등 다양한 변화로 이어졌습니다.', rubrics=None, persona_name=None, query_style=None, query_length=None), synthesizer_name='multi_hop_specific_query_synthesizer'), TestsetSample(eval_sample=SingleTurnSample(user_input='1960년 동계 올림픽 중계권 팔앗던거랑 그 이후 텔레비전 시청자수 증가랑 무슨 관계가 있나요?', retrieved_contexts=None, reference_contexts=['<1-hop>\n\n베를린에서 열렸던 1936년 하계 올림픽은 전 세계가 아닌 독일 내에서만의 방송이지만 텔레비전으로 방송한 첫 번째 올림픽이었다. 1956년 동계 올림픽은 올림픽을 전 세계적으로 중계 방송한 첫 번째 올림픽이었으며, 1960년 동계 올림픽에서는 중계권을 어느 특정한 방송사에 판매한첫 번째 올림픽이다. 그 후 수십 년간 올림픽은 냉전중인 국가들의 이데올로기 선전의 장이 되었다. 강대국들은 정치 주권을 위해 IOC(국제 올림픽 위원회)를 조종했으며, IOC는 중계권 판매를 통해 이익을 높이고자 하였다. 중계권의 판매는 올림픽을 전 세계적으로 알리는 데 큰 기여를 했으며, 그로 인해 텔레비전의 광고 시간을 사는 광고주들에게 경쟁을 유발하여 IOC는 더욱더 많은 이익을 얻게 되었다. 이는 IOC에게 있는 중계권을 비롯한 수많은 권리들에 지불해야 할 금액들이 앞으로도 지속적으로 늘어나게 됨을 의미한다. 예를 들면 1998년 동계 올림픽 중계권을 사는 데 CBS는 3억 7500만 달러를 지불했지만 2000~2012년 올림픽의 중계권을 따내는 데 NBC는 35억 달러나 지불해야 했다.  \n올림픽 시청자들 또한 1960년대부터 기하급수적으로 증가했다. 1968년 하계 올림픽을 텔레비전으로 시청한 사람들은 6억 명으로 추측되었고, 1984년 하계 올림픽을 시청한 사람들은 9억 명으로 늘어났으며, 1992년 하계 올림픽은 약 35억 명이 시청한 것으로 추측되고 있다. 하지만 NBC의 조사에 의하면 시드니에서 열린 2000년 하계 올림픽은 1968년부터 개최된 올림픽 중에서 가장 적은 수의 사람들이 시청한 것으로 조사되었다. 시청자 수 감소의 원인으로 크게 두 가지가 지목되는데, 그중 하나는 케이블 채널 간의 경쟁이 심화된 것이고, 다른 하나는 실시간으로 경기 영상과 결과를 보여주는 인터넷의 대중화이다. 이러한 원인 분석에도 불구하고 텔레비전 방송국들은 아직도 지연방송에 의존하고 있다. 시청률 감소를 다르게 표현하자면 텔레비전 방송국에서는 광고 시간을 예전보다 싼 가격에 제공할 수밖에 없다는 것을 의미하기도 한다. 텔레비전 방송국들은 국제 올림픽 위원회에게 많은 방송 비용과 인터넷의 발달로 인한 케이블의 치열한 경쟁을 이유로 엄청난 중계권 가격을 조금 낮춰달라고 요구하고 있다. 결국 IOC는 올림픽 프로그램 진행 시간을 상당 부분 변경하게 된다. 예를 들면 하계 올림픽 때 체조종목은 밤 7시에서 9시까지 하는 것으로 바뀌었으며, 갈라쇼는 흥미를 높이는 데에 초점을 맞추게 되었다. 또한 IOC는 수영과 다이빙 종목의 시간은 늘렸는데, 이 종목은 텔레비전 시청자들 중 가장 인기가 있는 종목 중 하나이기 때문이다. 이는 미국 방송국들의 로비가 올림픽 종목들의 일정 시간까지도 미국의 텔레비전 황금시간대에 맞춰서 변경될 수 있음을 의미하는 것이었다. 이 변화는 장점과 단점이 혼재되어 있고, 그 예로 유럽에서 열렸던 2006년 동계 올림픽의 시청률은 미국 솔트레이크 시티에서 열렸던 2002년 동계 올림픽과 비교해보면 확연히 낮았으며 또한 베이징에서 열렸던 2008년 하계 올림픽의 시청자는 급격히 늘어났다.'], retrieved_context_ids=None, reference_context_ids=None, response=None, multi_responses=None, reference='1960년 동계 올림픽은 중계권을 어느 특정한 방송사에 판매한 첫 번째 올림픽이었고, 이로 인해 중계권 판매가 올림픽을 전 세계적으로 알리는 데 큰 기여를 하였습니다. 그 결과 1960년대부터 올림픽 시청자들이 기하급수적으로 증가하였으며, 1968년 하계 올림픽을 텔레비전으로 시청한 사람들은 6억 명, 1984년에는 9억 명, 1992년에는 약 35억 명으로 늘어났습니다. 즉, 1960년 동계 올림픽에서 시작된 중계권 판매가 텔레비전 시청자 수 증가와 밀접한 관련이 있습니다.', rubrics=None, persona_name=None, query_style=None, query_length=None), synthesizer_name='multi_hop_specific_query_synthesizer'), TestsetSample(eval_sample=SingleTurnSample(user_input='쿠베르탱의 이상이 올림픽 상징과 올림픽 선서, 그리고 영국 공립 학교의 이념과 어떻게 연결되어 있는지 설명하시오.', retrieved_contexts=None, reference_contexts=['<1-hop>\n\n올림픽에서는 올림픽 헌장에 구체적으로 나타난 이상이나 철학을 표현하는 상징을 사용한다. 오륜기로 잘 알려져 있는 올림픽기는 5개의 둥근 고리가 얽혀있으며 각 원마다 5대륙을 상징한다.(남아메리카와 북아메리카는 아메리카로 합쳐 있다.) 파랑, 노랑, 검정, 초록, 빨간 고리에 흰색 바탕은 올림픽 기를 나타낸다. 이 색들이 선택된 이유는 모든 국기에서 적어도 이 5개의 색 중 하나를 가지고 있기 때문이다. 올림픽 기가 채택된 것은 1914년이지만 1920년 하계 올림픽 때부터 사용되기 시작했다. 이 때부터 올림픽 기는 올림픽을 기념하기 위해 올림픽이 열리는 기간 동안 게양한다.  \n올림픽 표어는 라틴어로 Citius, Altius, Fortius이며 "더 빨리, 더 높게, 더 힘차게"라는 뜻이다. 쿠베르탱의 이상은 올림픽 선서에 더 잘 나타나 있다.  \n- 올림픽 선서 중에서\n- "인생에서 가장 중요한 것은 승리가 아니라 이를 위해 분투하는 것이고, 올림픽에서 가장 중요한 것 역시 승리가 아니라 참가 자체에 의의가 있다. 우리에게 있어 본질은 정복하는 것이 아니라 잘 싸우는 것이다."  \n매 올림픽이 시작되기 몇 개월전에 고대 그리스에서 제사를 지냈던 그리스의 올림피아에서 올림픽 성화가 채화된다. 여자 배우가 마치 여자 사제인 것처럼 연기해서 태양광선을 포물면 거울(오목 거울의 하나)의 안쪽에 집중시켜서 점화한다. 그 후에 여자는 첫 번째 성화 봉송 주자에게 성화를 넘기고 개최도시의 개막식이 열리는 올림픽 경기장까지 여러 사람의 손을 거쳐서 올림픽 성화는 전달된다. 올림픽 상징으로서의 올림픽 성화는 1928년 하계 올림픽 때 이미 있었지만, 성화 봉송은 1936년 하계 올림픽때 독일 정부의 나치즘 선전의 일환으로 처음 시행된 것이 그 유래이다.  \n개최도시의 문화적 상징물을 동물이나 사람의 형상으로 나타내는 올림픽 마스코트는 1968년에 처음 소개되었다. 이후 1980년 하계 올림픽 때 러시아 아기곰인 미샤가 국제적인 스타의 자리에 오르며, 올림픽의 상징에 있어 마스코트가 한층 더 중요한 역할을 하게 되었다. 가장 최근의 하계 올림픽 마스코트는 2012 런던 올림픽의 마스코트인 웬록으로, 웬록은 영국 중서부 슈롭셔의 작은 마을 이름이며 이곳은 근대 올림픽 창시자인 쿠베르탱이 올림픽을 창안했던 곳이다. 또한 가장 최근의 동계 올림픽 마스코트로는 2010년 동계 올림픽의 마스코트인 미가, 콰치, 수미가 있다.', "<2-hop>\n\n프로 NHL선수들은 1998년부터 아이스 하키종목에 출전할 수 있게 되었다. (나가노 올림픽 결승전 러시아 vs 체코).  \n영국 명문 공립 학교의 이념은 쿠베르탱에게 큰 영향을 끼쳤다. 영국 공립 학교는 스포츠를 교육의 중요한 부분이라 생각해서 '건전한 신체에 건전한 정신을'이라는 의미를 가진 라틴어 mens sana in corpore sano를 표어로 삼았다. 이 이념에 의하면 신사들은 특정한 분야에서만 우수해서는 안되고 모든 분야에서 고르게 잘해야 하고, 공정한 결과에는 승복해야 하며, 연습이나 훈련은 속이는 것과 마찬가지로 여겼다. 전문적으로 스포츠를 연습한 사람은 취미로 연습한 사람에 비해 공평하지 않다고 생각한 것이다.  \n현대 올림픽에서는 프로 선수의 참가 불허가 많은 분쟁을 가져왔다. 1912년 하계 올림픽의 근대 5종 경기와 10종 경기에서 우승한 짐 소프는 올림픽에 나가기 전에 준프로야구선수로 활동했다는 게 나중에 밝혀져 메달이 박탈되었다. 소프는 후에 동정적 여론의 힘을 업고 1983년에 메달을 돌려받게 된다. 1936년 동계 올림픽 때 스위스와 오스트리아 스키선수들은 돈을 벌기 위해 스포츠를 했는데 이러한 행동이 아마추어 정신에 위배된다고 결정되어 그들은 스키종목에 참가할 수 없었다.  \n20세기에 이르러서 계급구조가 붕괴되면서 이른바 귀족적인 신사라는 아마추어 선수에 대한 정의는 시대에 뒤처지는 말이 되게 된다. 일부 국가들은 '정식 아마추어 선수'를 '키워서' 순수한 아마추어 정신을 벗어나고 있었고, 자신이 내는 비용으로 연습하는 선수들의 불리함에 대한 목소리가 나오기 시작했다. 하지만 IOC는 아마추어 정신에 관한 입장을 고수했다. 1970년대 초에는 아마추어 정신이 올림픽헌장에서 폐지되어야 한다는 말이 나오기 시작했다. 결국 프로선수들의 출전은 국제경기연맹(IF)에서 결정짓도록 되었다. 2008년 기준으로 아마추어 선수만 출전하고 있는 올림픽 종목은 복싱이 유일하며 남자 축구에서는 나이가 23세 이상인 선수를 3명까지만 선발할 수 있다. 이는 아마추어 정신을 지키기 위한 일환으로 볼 수 있다."], retrieved_context_ids=None, reference_context_ids=None, response=None, multi_responses=None, reference="쿠베르탱의 이상은 올림픽 선서에 잘 나타나 있는데, 이는 '인생에서 가장 중요한 것은 승리가 아니라 이를 위해 분투하는 것이고, 올림픽에서 가장 중요한 것 역시 승리가 아니라 참가 자체에 의의가 있다'는 내용으로 요약된다(<1-hop>). 이러한 이상은 영국 명문 공립 학교의 이념에서 큰 영향을 받았는데, 영국 공립 학교는 스포츠를 교육의 중요한 부분으로 여기며 '건전한 신체에 건전한 정신을'이라는 라틴어 mens sana in corpore sano를 표어로 삼았다(<2-hop>). 이 이념에 따르면 신사는 특정 분야에서만 우수해서는 안 되고 모든 분야에서 고르게 잘해야 하며, 공정한 결과에는 승복해야 한다고 강조한다.

In [17]:
sample1  = testset.samples[0].eval_sample
print(sample1.user_input)         # 사용자 질문
print(sample1.reference_contexts) # Vector DB의 context (이것을 바탕으로 user_input과 referenece를 생성)
print(sample1.retrieved_contexts) # RAG pipeline이 벡터디비에서 검색한 문서
print(sample1.reference)          # 정답(ground truth)
print(sample1.response)           # LLM 응답 (정답추정값)

# 평가시 필요한 속성: user_input, retrieved_contexts, reference, response
#   retrieved_context, response -> 평가할 RAG Chain으로 부터 가져와야 한다.

2012 런던 올림픽 마스코트 뭐에요?
['올림픽에서는 올림픽 헌장에 구체적으로 나타난 이상이나 철학을 표현하는 상징을 사용한다. 오륜기로 잘 알려져 있는 올림픽기는 5개의 둥근 고리가 얽혀있으며 각 원마다 5대륙을 상징한다.(남아메리카와 북아메리카는 아메리카로 합쳐 있다.) 파랑, 노랑, 검정, 초록, 빨간 고리에 흰색 바탕은 올림픽 기를 나타낸다. 이 색들이 선택된 이유는 모든 국기에서 적어도 이 5개의 색 중 하나를 가지고 있기 때문이다. 올림픽 기가 채택된 것은 1914년이지만 1920년 하계 올림픽 때부터 사용되기 시작했다. 이 때부터 올림픽 기는 올림픽을 기념하기 위해 올림픽이 열리는 기간 동안 게양한다.  \n올림픽 표어는 라틴어로 Citius, Altius, Fortius이며 "더 빨리, 더 높게, 더 힘차게"라는 뜻이다. 쿠베르탱의 이상은 올림픽 선서에 더 잘 나타나 있다.  \n- 올림픽 선서 중에서\n- "인생에서 가장 중요한 것은 승리가 아니라 이를 위해 분투하는 것이고, 올림픽에서 가장 중요한 것 역시 승리가 아니라 참가 자체에 의의가 있다. 우리에게 있어 본질은 정복하는 것이 아니라 잘 싸우는 것이다."  \n매 올림픽이 시작되기 몇 개월전에 고대 그리스에서 제사를 지냈던 그리스의 올림피아에서 올림픽 성화가 채화된다. 여자 배우가 마치 여자 사제인 것처럼 연기해서 태양광선을 포물면 거울(오목 거울의 하나)의 안쪽에 집중시켜서 점화한다. 그 후에 여자는 첫 번째 성화 봉송 주자에게 성화를 넘기고 개최도시의 개막식이 열리는 올림픽 경기장까지 여러 사람의 손을 거쳐서 올림픽 성화는 전달된다. 올림픽 상징으로서의 올림픽 성화는 1928년 하계 올림픽 때 이미 있었지만, 성화 봉송은 1936년 하계 올림픽때 독일 정부의 나치즘 선전의 일환으로 처음 시행된 것이 그 유래이다.  \n개최도시의 문화적 상징물을 동물이나 사람의 형상으로 나타내는 올림픽 마스코트는 1968년에 처음 소개되었다. 이후 1980년 하계 올림픽 때 러시아 아기곰인 미샤가 국제적인 스타의 자리에 오르며, 올림픽의 상징에 있어 마스코트가 한층 더 중요한 역할을 하게 되었다. 가장 최근의 하계 올림픽 마스코트는 2012 런던 올림픽의 마스코트인 웬록으로, 웬록은 영국 중서부 슈롭셔의 작은 마을 이름이며 이곳은 근대 올림픽 창시자인 쿠베르탱이 올림픽을 창안했던 곳이다. 또한 가장 최근의 동계 올림픽 마스코트로는 2010년 동계 올림픽의 마스코트인 미가, 콰치, 수미가 있다.']
None
2012 런던 올림픽의 마스코트는 웬록으로, 웬록은 영국 중서부 슈롭셔의 작은 마을 이름이며 이곳은 근대 올림픽 창시자인 쿠베르탱이 올림픽을 창안했던 곳이다.
None

In [18]:
# Testset을 pandas DataFrame을 변환 -> to_pandas(), to_xxxx() 를 통해서 다른 구조로 변환이 가능.
eval_df = testset.to_pandas()
eval_df

,user_input,reference_contexts,reference,persona_name,query_style,query_length,synthesizer_name
0,2012 런던 올림픽 마스코트 뭐에요?,[올림픽에서는 올림픽 헌장에 구체적으로 나타난 이상이나 철학을 표현하는 상징을 사용...,"2012 런던 올림픽의 마스코트는 웬록으로, 웬록은 영국 중서부 슈롭셔의 작은 마을...",Olympic Enthusiast,MISSPELLED,SHORT,single_hop_specific_query_synthesizer
1,파나티네코 경기장은 1896년 아테네 올림픽을 준비하는 과정에서 어떤 역할을 했으며...,[1859년 자파스 올림픽에 참가한 선수의 수는 250명을 넘지 못했다. 에방겔리스...,에방겔리스 자파스는 1896년에 개최될 2번째 올림픽을 위해 파나티네코 경기장을 보...,Olympic Enthusiast,PERFECT_GRAMMAR,LONG,single_hop_specific_query_synthesizer
2,올림픽 프로그람 커미션은 뭐하는 기구에요?,[올림픽 경기 종목은 총 33개부문 52개 종목에서 약 400개의 경기로 이루어져있...,올림픽 프로그램 위원회는 올림픽 종목과 올림픽 종목이 아닌 스포츠를 모두 재검토하는...,Olympic History Enthusiast,MISSPELLED,MEDIUM,single_hop_specific_query_synthesizer
3,1936년 하계 올림픽의 방송 관련 특징은 무엇인가요?,[베를린에서 열렸던 1936년 하계 올림픽은 전 세계가 아닌 독일 내에서만의 방송이...,베를린에서 열렸던 1936년 하계 올림픽은 전 세계가 아닌 독일 내에서만의 방송이지...,Olympic Enthusiast,WEB_SEARCH_LIKE,SHORT,single_hop_specific_query_synthesizer
4,"NHL 선수들 언제부터 올림픽 아이스 하키에 나갈 수 있었는지, 그리고 그거랑 올림...",[프로 NHL선수들은 1998년부터 아이스 하키종목에 출전할 수 있게 되었다. (나...,프로 NHL선수들은 1998년부터 아이스 하키종목에 출전할 수 있게 되었다. 현대 ...,Olympic History Enthusiast,POOR_GRAMMAR,LONG,single_hop_specific_query_synthesizer
5,1936년 하계 올림픽이 텔레비전으로 방송된 첫 번째 올림픽이었다는 점과 이후 올림...,[<1-hop>\n\n베를린에서 열렸던 1936년 하계 올림픽은 전 세계가 아닌 독...,1936년 하계 올림픽은 독일 내에서만이었지만 텔레비전으로 방송된 첫 번째 올림픽이...,NaN,NaN,NaN,multi_hop_specific_query_synthesizer
6,1960년 동계 올림픽이 중계권을 특정 방송사에 처음으로 판매한 올림픽이었다고 하는...,[<1-hop>\n\n베를린에서 열렸던 1936년 하계 올림픽은 전 세계가 아닌 독...,1960년 동계 올림픽은 중계권을 어느 특정한 방송사에 판매한 첫 번째 올림픽이었습...,NaN,NaN,NaN,multi_hop_specific_query_synthesizer
7,1960년 동계 올림픽 중계권 팔앗던거랑 그 이후 텔레비전 시청자수 증가랑 무슨 관...,[<1-hop>\n\n베를린에서 열렸던 1936년 하계 올림픽은 전 세계가 아닌 독...,1960년 동계 올림픽은 중계권을 어느 특정한 방송사에 판매한 첫 번째 올림픽이었고...,NaN,NaN,NaN,multi_hop_specific_query_synthesizer
8,"쿠베르탱의 이상이 올림픽 상징과 올림픽 선서, 그리고 영국 공립 학교의 이념과 어떻...",[<1-hop>\n\n올림픽에서는 올림픽 헌장에 구체적으로 나타난 이상이나 철학을 ...,"쿠베르탱의 이상은 올림픽 선서에 잘 나타나 있는데, 이는 '인생에서 가장 중요한 것...",NaN,NaN,NaN,multi_hop_specific_query_synthesizer
9,쿠베르탱의 이상이 올림픽 상징과 영국 공립 학교의 이념에 어떻게 반영되어 있나요?,[<1-hop>\n\n올림픽에서는 올림픽 헌장에 구체적으로 나타난 이상이나 철학을 ...,"쿠베르탱의 이상은 올림픽 선서에 잘 나타나 있으며, 이는 '인생에서 가장 중요한 것...",NaN,NaN,NaN,multi_hop_specific_query_synthesizer
10,"쿠베르탱의 이상이 올림픽 선서와 영국 공립 학교의 이념에 어떻게 반영되어 있으며, ...",[<1-hop>\n\n올림픽에서는 올림픽 헌장에 구체적으로 나타난 이상이나 철학을 ...,"쿠베르탱의 이상은 올림픽 선서에 잘 나타나 있는데, 이는 ""인생에서 가장 중요한 것...",NaN,NaN,NaN,multi_hop_specific_query_synthesizer

In [19]:
res = chain.invoke(eval_df['user_input'][0])

In [20]:
res['response']
res['retrieved_context']

['올림픽에서는 올림픽 헌장에 구체적으로 나타난 이상이나 철학을 표현하는 상징을 사용한다. 오륜기로 잘 알려져 있는 올림픽기는 5개의 둥근 고리가 얽혀있으며 각 원마다 5대륙을 상징한다.(남아메리카와 북아메리카는 아메리카로 합쳐 있다.) 파랑, 노랑, 검정, 초록, 빨간 고리에 흰색 바탕은 올림픽 기를 나타낸다. 이 색들이 선택된 이유는 모든 국기에서 적어도 이 5개의 색 중 하나를 가지고 있기 때문이다. 올림픽 기가 채택된 것은 1914년이지만 1920년 하계 올림픽 때부터 사용되기 시작했다. 이 때부터 올림픽 기는 올림픽을 기념하기 위해 올림픽이 열리는 기간 동안 게양한다.  \n올림픽 표어는 라틴어로 Citius, Altius, Fortius이며 "더 빨리, 더 높게, 더 힘차게"라는 뜻이다. 쿠베르탱의 이상은 올림픽 선서에 더 잘 나타나 있다.  \n- 올림픽 선서 중에서\n- "인생에서 가장 중요한 것은 승리가 아니라 이를 위해 분투하는 것이고, 올림픽에서 가장 중요한 것 역시 승리가 아니라 참가 자체에 의의가 있다. 우리에게 있어 본질은 정복하는 것이 아니라 잘 싸우는 것이다."  \n매 올림픽이 시작되기 몇 개월전에 고대 그리스에서 제사를 지냈던 그리스의 올림피아에서 올림픽 성화가 채화된다. 여자 배우가 마치 여자 사제인 것처럼 연기해서 태양광선을 포물면 거울(오목 거울의 하나)의 안쪽에 집중시켜서 점화한다. 그 후에 여자는 첫 번째 성화 봉송 주자에게 성화를 넘기고 개최도시의 개막식이 열리는 올림픽 경기장까지 여러 사람의 손을 거쳐서 올림픽 성화는 전달된다. 올림픽 상징으로서의 올림픽 성화는 1928년 하계 올림픽 때 이미 있었지만, 성화 봉송은 1936년 하계 올림픽때 독일 정부의 나치즘 선전의 일환으로 처음 시행된 것이 그 유래이다.  \n개최도시의 문화적 상징물을 동물이나 사람의 형상으로 나타내는 올림픽 마스코트는 1968년에 처음 소개되었다. 이후 1980년 하계 올림픽 때 러시아 아기곰인 미샤가 국제적인 스타의 자리에 오르며, 올림픽의 상징에 있어 마스코트가 한층 더 중요한 역할을 하게 되었다. 가장 최근의 하계 올림픽 마스코트는 2012 런던 올림픽의 마스코트인 웬록으로, 웬록은 영국 중서부 슈롭셔의 작은 마을 이름이며 이곳은 근대 올림픽 창시자인 쿠베르탱이 올림픽을 창안했던 곳이다. 또한 가장 최근의 동계 올림픽 마스코트로는 2010년 동계 올림픽의 마스코트인 미가, 콰치, 수미가 있다.',
 "국제 올림픽 위원회(이하 IOC로 지칭)는 몇몇 위원들이 한 행위에 대해서 비판을 받고 있다. 그 예로 IOC 위원장이었던 에이버리 브런디지와 후안 안토니오 사마란치가 대표적인 사람이다. 브런디지는 20년 넘게 IOC 위원장직을 맡았고 임기 중에 올림픽을 정치적으로 휘말려들지 않게 하기 위해 보호했다. 그러나 그는 남아프리카 공화국 대표단에게 아파르트헤이트와 관련된 이슈를 건드리고 반유대정책을 함으로써 비난을 받았다. 사마란치 위원장 시기 때는 족벌 정치와 부패로 비난받았다. 사마란치가 스페인에서 프랑코 정권에 협력했다는 것도 비판의 이유가 되었다.  \n1998년에 몇몇 IOC위원들이 2002년 솔트레이크 시티 동계 올림픽 유치 과정에서 미국에게 미국을 올림픽 개최지로 뽑아달라는 뇌물청탁을 받았다는 것이 폭로되었다. 이에 IOC는 사퇴한 IOC위원 4명과 강제 퇴출된 6명에 대한 조사를 했다. 이 스캔들은 이후에 개최지 선정에서 이와 같은 불미스러운 일이 일어나지 않게 하기 위해서 IOC가 개혁에 착수하도록 하는 긍정적인 역할을 하기도 했다.  \nBBC 다큐멘터리인 '파노라마'에서는 '매수된 올림픽'이란 주제로 2004년 8월에 방송을 내보내기도 했다. 이때 이 프로그램에서는 2012년 하계 올림픽의 개최지 선정과 관련된 뇌물에 대해서 조사했다. 이 다큐멘터리에서는 특정 후보 도시가 IOC 위원들에게 뇌물수수하는 것이 가능했다고 주장했으며, 특히 파리 시장이었던 베르트랑 들라노에(Bertrand Delanoë)는 영국의 총리인 토니 블레어와 런던올림픽유치위원회가 입후보 규정을 위반했다고 비난했다. 그는 당시 프랑스 대통령이었던 자크 시라크를 목격자로 내세웠지만 시라크 대통령은 이 분쟁에 휘말려드는 것을 주의했으며 인터뷰를 삼갔다. 결국 베르트랑 들라노에의 주장에 대한 조사는 체계적으로 이루어지지는 않았다. 2006년 동계 올림픽을 유치했던 토리노도 이 논쟁에서 빠져나갈 수 없었다. 이번에는 스위스 국적의 IOC위원 마크 호들러(Marc Hodler)가 이 논쟁의 중심이 되었는데, 이 위원은 스위스 시온의 경쟁 도시였던 토리노가 IOC위원들에게 뇌물수수를 했다고 말했고, 이 발언으로 광범위한 조사가 이루어졌다. 이 언행이 많은 IOC위원들이 시온에 대해 언짢게 생각하게 되고 토리노가 개최지로 선정되도록 도와주는 역할을 했을 가능성도 제기되고 있다.",
 '쿠베르탱의 생각과는 달리, 올림픽이 세계에 완벽한 평화를 가져다주지는 못했다. 실제로 제1차 세계대전으로 인해 독일 베를린에서 열리기로 했던 제6회 1916년 하계 올림픽이 취소되었고, 제2차 세계대전 때는 일본 도쿄에서 열리기로 했던 제12회 1940년 하계 올림픽, 삿포로에서 열리기로 했던 1940년 동계 올림픽, 영국 런던에서 열리기로 했던 제13회 1944년 하계 올림픽, 이탈리아 코르티나담페초에서 열릴 예정인 1944년 동계 올림픽이 취소되었다. 베이징에서 열린 2008년 하계 올림픽 개막식날 조지아와 러시아 간의 2008년 남오세티아 전쟁이 일어나기도 했다. 부시 대통령과 푸틴 대통령이 이 올림픽을 보러 왔으며 중국 주석인 후진타오가 주최한 오찬에 참석해서 이 현안에 대해 논의하기도 했다. 조지아 대표인 니노 살루크바체와 러시아 대표인 나탈리야 파데리나가 여자 10m 공기권총 경기에서 각각 동메달과 은메달을 땄을 때 이 일은 베이징 올림픽의 유명한 사건 중 하나로 남게 되었다. 살루크바체와 파데리나는 시상식이 끝난 뒤 서로 포옹을 하며 국적에 상관없이 기쁨을 나누었다.  \n테러도 올림픽에서 공포의 대상이었다. 뮌헨 참사로 알려진 1972년에 서독 바이에른의 뮌헨에서 열린 하계 올림픽때의 사건은 테러리스트인 검은 9월단이 일으킨 사건으로서 이스라엘 선수 11명을 인질로 붙잡았다가 전원이 사망한 사건이다. 당시 미숙한 진압으로 인해 인질 9명(선수 1명과 코치 1명은 인질로 잡기 이전에 살해), 테러범 5명, 독일 경찰관 1명이 사망했으며 이 진압 작전 이전에는 인질들은 단 한 명도 죽지 않았다. 애틀랜타에서 열린 1996년 하계 올림픽 때는 센테니얼 올림픽 공원(Centennial Olympic Park)에서 폭발 사건이 일어나 2명이 죽고 111명이 다치는 사건이 발생했다. 이 사건의 주모자 에릭 로버트 루돌프는 종신형을 선고받았다. 참고로 마라톤 역시 전쟁에서 유래한 것이다.',
 '올림픽 활동이란 많은 수의 국가, 국제 경기 연맹과 협회 • 미디어 파트너를 맺기 • 선수, 직원, 심판, 모든 사람과 기관이 올림픽 헌장을 지키는 것을 말한다.국제올림픽위원회(IOC)는 모든 올림픽 활동을 통솔하는 단체로서, 올림픽 개최 도시 선정, 계획 감독, 종목 변경, 스폰서 및 방송권 계약 체결 등의 권리가 있다. 올림픽 활동은 크게 세 가지로 구성된다.  \n- 국제경기연맹(IF)은 국제적인 규모의 경기를 관리, 감독하는 기구이다. 예를 들어서 국제 축구 연맹(FIFA)는 축구를 주관하며, 국제 배구 연맹(FIVB)은 배구를 주관하는 기구이다. 올림픽에는 현재 35개의 국제경기연맹이 있고 각 종목을 대표한다. (이 중에는 올림픽 종목은 아니지만 IOC의 승인을 받은 연맹도 있다.)\n- 국가 올림픽 위원회(NOC)는 각국의 올림픽 활동을 감독하는 기구이다. 예를 들어서 대한 올림픽 위원회(KOC)는 대한민국의 국가 올림픽 위원회이다. 현재 IOC에 소속된 국가 올림픽 위원회는 205개이다.\n- 올림픽 조직 위원회(OCOG)는 임시적인 조직으로 올림픽의 총체적인 것(개막식, 페막식 등)을 책임지기 위해 구성된 조직이다. 올림픽 조직 위원회는 올림픽이 끝나면 해산되며 최종보고서를 IOC에 제출한다.  \n올림픽의 공식언어는 프랑스어와 영어와 개최국의 공용어이다. 모든 선언(예를 들어서 개막식 때 각국 소개를 할 때)들은 세 언어가 모두 나오거나 영어나 프랑스어 중에서 한 언어로만 말하기도 한다. 개최국의 공용어가 영어나 프랑스어가 아닐 때는 당연히 그 나라의 공용어도 함께 나온다.',
 "올림픽에서 이루어지는 주요 행사로는 개막식, 폐막식, 시상식 등이 있다.  \n#### 개막식  \n개막식 때는 올림픽 헌장에 따라 다양한 행사가 열린다. 개막식의 기본 토대는 벨기에 안트베르펜에서 열린 1920년 하계 올림픽 때 만들어졌다. 개막식은 대개 개최국의 국기가 게양되고 국가가 울려퍼지며 시작된다. 그 후에 개최국이 준비한 그들의 문화를 대표하는 음악, 춤, 영상 따위가 공연된다. 개막식은 아름답기가 매회가 지날수록 웅대해지고 복잡해지는데, 이는 전 대회보다 사람들의 기억에 오래도록 남기기 위함이다. 보도에 의하면 2008 베이징 올림픽 개막식 때 든 비용은 1억 달러로 그 대부분이 예술적인 부분에 들었다고 한다.  \n행사가 끝나면 다음에는 각국의 선수단이 입장한다. 올림픽의 발상지라는 영예를 가진 그리스가 전통적으로 맨 처음에 입장한다. 나머지 각국 선수단은 주최국에서 선택한 언어의 사전 순으로 입장하고 나서, 개최국 선수단이 제일 마지막에 입장한다. 그리스 아테네에서 열린 2004년 하계 올림픽에서는 그리스 국기가 맨 처음에 입장하고, 그리스 선수단이 맨 마지막에 입장했다. 개막식 마지막에는 올림픽 성화가 들어오고 마지막 성화 봉송자에게 전달할 때까지 돌게 된다. 마지막 성화 봉송자는 대체로 유명하고 올림픽에서 성공한 개최국의 선수가 하며 올림픽 성화를 경기장 내에 점화한다. 그 다음 올림픽조직위원장과 IOC 위원장이 개막 선언을 하는데 공식적으로 개막되었다는 것과 올림픽 성화가 점화되는 것을 선언한다. 그 다음에 올림픽조직위원장과 IOC 위원장이 개회사를 낭독하게 된다. 마자막으로 올림픽기 게양에 이어 올림픽 선서를 끝으로 개막식 과정은 모두 끝나게 된다. 2020년 하계 올림픽 이후로는 그리스 - 난민 올림픽 선수단 - 나머지 각국 선수단 - 차차기 올림픽 개최국 - 차기 올림픽 개최국 - 개최국 순서대로 입장한다.  \n#### 폐막식  \n폐막식은 올림픽 경기가 모두 끝난 후에 열린다. 각국의 기수가 경기장에 들어온 후에 국적에 상관없이 모든 선수들이 함께 들어온다. 3개의 기가 국가가 울려퍼지는 동안 게양되는데, 그 3개의 국기는 그리스의 국기(올림픽의 발상지임을 기념하기 위해), 개최도시의 국기, 다음 하계·동계 올림픽의 개최도시의 국기이다. 그 다음 올림픽조직위원장과 IOC 위원장이 폐막 선언을 하는데 공식적으로 폐막되었다는 것과 올림픽 성화가 꺼지는 것을 선언한다. 일명 '안트베르펜 세레모니'라고 하는 것도 진행되는데, 이는 올림픽 개최도시의 수장이 특별한 올림픽 기를 IOC 위원장에게 넘겨주면 그것을 또다시 다음 대회의 개최도시의 수장에게 넘겨주는 것으로서 1920 안트베르펜 올림픽 때부터 시작한 것으로 알려져 있다. 이 행사가 끝나면 짧게 다음 대회 개최지에 대한 소개로 홍보 영상이나 퍼포먼스가 진행된다.  \n#### 시상식  \n시상식은 각 종목이 끝날 때마다 열린다. 개인 혹은 팀으로 참가해서 1위를 하거나 2위 혹은 3위를 한 선수(들)은 시상대에 올라서서 존경의 뜻으로 메달을 수여받는다. 올림픽 위원들에게 메달을 받은 후에 1위를 한 선수의 국가가 울려퍼지고 1, 2, 3위를 한 선수들의 국기가 올라간다. 개최도시의 자원봉사자들도 시상식 때 활동하는데 메달을 준비하거나 꽃을 들고 이동하는 것과 같은 일을 한다. 올림픽 종목마다 시상식은 대체로 그 종목의 결승전(본선)이 끝난 후 거의 하루 뒤에 이루어진다. 남자 마라톤의 경우에는 시작은 올림픽 마지막 날 아침 일찍 하고 시상식은 그 날 저녁에 폐막식 도중에 이루어진다."]

In [21]:
# Chain 응답들을 저장할 list
response_list = []
# Chain 이 반환한 context들을 지정할 list
retrieved_context_list = []

for user_input in eval_df['user_input']:
    res = chain.invoke(user_input)
    response_list.append(res['response'])
    retrieved_context_list.append(res['retrieved_context'])

In [22]:
print(len(response_list), len(retrieved_context_list))

11 11

In [23]:
response_list

['2012 런던 올림픽 마스코트는 웬록(웬록)입니다.',
 "Context에 따르면 파나티네코 경기장은 고대 경기장을 복원한 장소로서 근대 올림픽 준비와 직접 관련이 있었습니다. 에방겔리스 자파스가 1859년 자파스 올림픽 후 1896년 아테네 올림픽(당시 '2번째 올림픽'이라 언급됨)을 위해 파나티네코 경기장을 보수할 것을 권고했으나 그리스 정부가 이를 듣지 않았고, 결국 1896년 대회 준비를 위해 경기장은 두 번이나 정비를 받아야 했다는 내용이 나옵니다. 또한 자파스는 이 경기장 복원에 자금을 대어 1870년과 1875년에 자파스 올림픽을 이곳에서 개최하기도 했다는 정보도 있습니다.",
 '정보가 주어진 내용에 따르면, 올림픽 프로그램 위원회(Olympic Programme Commission)는 2004년 IOC가 설립한 위원회로서 올림픽 종목과 올림픽 종목이 아닌 스포츠를 재검토하는 기구입니다. 목표는 올림픽 종목을 더 체계적으로 다루는 것이며, 정식종목 포함을 위해 충족해야 할 7가지 기준(역사, 전통, 보편성, 인기도와 잠재성, 선수의 건강, 연맹의 스포츠 관리능력, 개최에 필요한 비용)을 제시합니다.',
 '1936년 베를린 하계 올림픽은 텔레비전으로 방송된 첫 번째 올림픽이었으나 전 세계가 아닌 독일 내에서만 방송되었습니다.',
 '- 언제부터: 프로 NHL 선수들은 1998년 나가노 동계올림픽부터 아이스하키 종목에 출전할 수 있게 되었습니다(나가노 올림픽 결승전: 러시아 vs 체코).\n\n- 올림픽의 아마추어 정신과의 관계: 근대 올림픽의 창시자 쿠베르탱은 영국 공립학교의 ‘mens sana in corpore sano’ 같은 아마추어 이념에 영향을 받아, 전문적으로 운동을 연습·생업으로 삼는 프로 선수는 아마추어에 비해 불공평하다고 보았습니다. 이런 아마추어 정신 때문에 오랜 기간 프로 선수의 참가를 제한했고, 이는 올림픽 전반에 걸쳐 많은 분쟁과 논란을 낳았습니다. 20세기 들어 계급 구조 변화와 일부 국가들이 ‘정식 아마추어’를 조직적으로 육성하는 현실 등으로 아마추어 정의가 문제화되자 1970년대 이후 아마추어 규정 폐지 논의가 일었고, 결국 프로 선수 출전 여부는 각 국제경기연맹(IF)이 결정하도록 바뀌었습니다. NHL 선수의 출전 허용은 이러한 아마추어 규정 완화의 결과로 볼 수 있습니다.\n\n- NHL 선수들 출전 허용 이전에 있었던 논란(문맥에 있는 사례들):\n  - 1912년 근대5종·10종 우승자 짐 소프는 올림픽 이전 준프로 야구 활동이 밝혀져 메달이 박탈되었다가(후에 1983년에 메달 복구) 논란이 됨.\n  - 1936년 동계올림픽에서 스위스·오스트리아 스키 선수들이 돈을 벌기 위해 경기한 것이 아마추어 정신 위배로 판단되어 출전 금지된 사례.\n  - 일부 국가들이 ‘정식 아마추어’를 조직적으로 육성해 순수 아마추어 정신을 벗어나고 있다는 비판과, 자비로 훈련하는 선수들의 불이익을 지적하는 목소리 등이 지속적으로 제기됨.\n\n위 내용은 제공된 문맥에 근거한 설명입니다.',
 '정보 출처에 따른 답변은 다음과 같습니다.\n\n- 1936년 베를린 올림픽은 독일 내에서 텔레비전으로 방송된 첫 올림픽이었다.  \n- 이 최초의 텔레비전 방송은 이후 올림픽의 방송·중계 발전의 출발점이 되었고, 이후 단계적 영향이 나타났다: 1956년 동계 올림픽이 전 세계 중계의 첫 사례가 되었고, 1960년 동계 올림픽은 중계권을 특정 방송사에 판매한 첫 사례가 되었다.  \n- 중계권 판매는 올림픽을 전 세계에 알리는 데 크게 기여했고, IOC는 중계권·스폰서 수익을 통해 이익을 증대시키려 했다. 그 결과 중계권 가격은 지속적으로 상승했고(예: 1998년 CBS 3억7500만 달러, 2000–2012년 NBC 35억 달러), 방송사들과 광고주 간의 경쟁도 심화되었다.  \n- 시청자 수는 1960년대부터 급증했다는 기록이 있으며(1968년 약 6억, 1984년 약 9억, 1992년 약 35억으로 추정). 그러나 2000년 시드니 올림픽은 1968년 이후 개최된 대회 중 가장 적은 시청자를 기록했다는 조사도 있다.  \n- 시청자 감소 원인으로는 케이블 채널 간 경쟁 심화와 인터넷의 보급(실시간 경기 영상·결과 제공)이 지목되었고, 이로 인해 방송사들은 IOC에 중계권 가격 인하를 요구하게 되었다.  \n- 이에 따른 결과로 IOC는 경기 시간과 프로그램 구성을 TV 황금시간대와 인기 종목에 맞춰 변경하는 등의 조치를 취했고(예: 체조 시간대 변경, 수영·다이빙 시간 확대), 이러한 변화의 효과는 혼재되어 특정 대회(예: 2006년 동계)는 이전 대회보다 시청률이 낮았고 반대로 2008년 베이징 하계는 시청자가 급증하는 등 차이를 보였다.\n\n결론적으로, 1936년의 텔레비전 방송은 올림픽의 전 세계적 방송·중계권 판매와 상업화의 토대를 마련했고, 이는 중계권 가치와 시청자 수의 급증, 이후의 시청률 변화 및 방송·프로그램 편성 변화로 이어졌다.',
 '문맥에 따르면 1960년 동계 올림픽이 중계권을 특정 방송사에 처음으로 판매한 것은 이후 올림픽의 상업화·중계권 거래·방송 편성 변화로 이어지는 중요한 전환점으로 묘사됩니다. 문서의 내용을 바탕으로 그 연결고리와 구체적 예시는 다음과 같습니다.\n\n1) 중계권 판매와 가격 상승\n- 1960년의 중계권 판매는 올림픽 중계권을 상업적 자산으로 취급하는 흐름을 본격화했고, IOC가 중계권 판매로 수익을 증대시키려는 방향으로 나아가게 했습니다.  \n- 그 결과 중계권에 대한 지불액은 크게 늘어났습니다. 문서에 제시된 예로는 1998년 동계 올림픽 중계권을 사기 위해 CBS가 3억 7,500만 달러를 지불한 사례와, 2000~2012년 올림픽 중계권을 따내기 위해 NBC가 35억 달러를 지불한 사례가 있습니다.\n\n2) 광고주 경쟁과 IOC 수익 증대\n- 중계권 판매로 올림픽이 전 세계적으로 방송되면서 텔레비전 광고 시간을 사려는 광고주들 간의 경쟁이 유발되었고, 이는 IOC의 수익을 높이는 요인이 되었다는 점이 문맥에 나타나 있습니다.\n- 또한 1984년 LA 올림픽(피터 우버로스 지휘)은 독점 스폰서 권리 판매로 막대한 이익(문서상 2억 2,500만 달러)을 창출한 사례로, 중계권·스폰서권 판매가 올림픽의 주요 수입원이 되었음을 보여줍니다. 이후 1985년에는 TOP(올림픽 프로그램) 제도가 만들어져 스폰서들로부터 독점적 대가를 받는 구조가 확립되었습니다.\n\n3) 텔레비전 시청자 수의 변화\n- 중계권의 세계적 판매는 시청자 수의 폭발적 증가와도 병행되었습니다. 문서의 수치 예시는 다음과 같습니다.\n  - 1968년 하계 올림픽 텔레비전 시청자: 약 6억 명(추정)  \n  - 1984년 하계 올림픽: 약 9억 명  \n  - 1992년 하계 올림픽: 약 35억 명(추정)  \n  - 2008 베이징 올림픽의 누적 시청자 수: 47억 명(문서 기록)  \n- 다만 2000년 시드니 올림픽은 NBC 조사에서 1968년 이후 개최된 올림픽 중 가장 적은 수의 시청자가 시청한 것으로 나왔고, 이후 시청률 감소 원인으로는 케이블 채널 간 경쟁 심화와 인터넷의 대중화(실시간 경기 영상·결과 제공)가 지목되고 있습니다. 문서도 방송국들이 여전히 지연방송에 의존한다고 밝힙니다.\n\n4) 경기 일정(방송 시간) 조정\n- 방송·광고 수입의 중요성이 커지면서 IOC는 올림픽 경기 시간과 프로그램 구성을 방송 시청률을 높이는 방향으로 조정하게 되었습니다. 문서상의 구체적 예:\n  - 체조 종목은 하계 올림픽에서 밤 7시에서 9시로 변경되었고, 갈라쇼는 흥미를 높이는 데 초점을 맞추게 되었다.  \n  - 수영과 다이빙 종목의 방송 시간은 늘려졌는데, 이는 해당 종목들이 텔레비전 시청자들 사이에서 인기 있는 종목이기 때문이라고 설명됩니다.  \n- 문서는 이러한 편성 변경이 미국 방송국들의 로비로 인해 미국의 황금시간대(프라임타임)에 맞춰 종목 시간까지 바뀔 수 있음을 의미한다고도 밝히고 있습니다.\n\n5) 영향의 긍정·부정 사례\n- 편성 변경과 상업화의 결과는 혼재된 효과를 낳았습니다. 예로 문서는 2006년 동계 올림픽(유럽 개최)의 시청률이 2002년 솔트레이크시티(미국 개최) 동계 올림픽보다 낮았음을 지적하는 한편, 2008년 베이징 하계 올림픽의 시청자는 급격히 늘어났다고 기록하고 있습니다. 이는 중계권 판매·편성 변경이 시청률과 수익에 복합적으로 영향을 미쳤음을 보여줍니다.\n\n요약 연결고리\n- 1960년의 중계권 판매(특정 방송사에 판매)는 올림픽을 전 세계 방송상품으로 확립하는 출발점이 되었고, 이후 IOC의 중계권·스폰서권 판매 확대 → 광고주 경쟁 촉발 → 중계권 가격 상승(예: CBS, NBC 사례) → 전체적 시청자 수 폭증(1968→1984→1992 등) 및 일부 회복 불능의 변동(예: 2000년 감소) → 방송사들의 요구와 수익성 문제로 인한 경기 일정 조정(체조·수영 등 시간 이동, 갈라쇼 편성 강화)로 이어졌다는 것이 문서의 설명입니다.\n\n위 내용은 제공된 문서의 정보에 근거한 설명입니다.',
 '문맥에 따르면 다음과 같이 관계가 설명되어 있습니다.\n\n- 1960년 동계 올림픽이 특정 방송사에 중계권을 판매한 것은 중계권 판매의 첫 사례이다.  \n- 그 이후 중계권 판매는 올림픽을 전 세계적으로 알리는 데 큰 기여를 했고, 텔레비전 광고 시간을 사려는 광고주들 간의 경쟁을 촉발하여 IOC의 수익을 늘렸다.  \n- 이와 함께 올림픽 시청자는 1960년대 이후 기하급수적으로 증가했으며(예: 1968년 약 6억 명, 1984년 약 9억 명, 1992년 약 35억 명 등), 중계권 판매가 시청자 증가와 직접적으로 연결되어 있음을 문맥에서 제시하고 있습니다.\n\n따라서 문맥상의 핵심 관계는: 1960년의 중계권 판매가 올림픽의 전 세계적 보급을 촉진했고, 이로 인해 텔레비전 시청자 수가 크게 늘어났다는 것입니다.',
 '쿠베르탱의 이상은 맥락에 따르면 ‘참가와 분투(노력)를 중시하고 승리 그 자체를 최우선으로 삼지 않는 태도’로 정리되며, 이는 올림픽의 상징들과 올림픽 선서, 그리고 그가 영향을 받은 영국 공립학교의 이념과 다음과 같이 연결된다.\n\n- 올림픽 상징(기·오륜·성화·표어 등): 문서에는 “올림픽에서는 올림픽 헌장에 구체적으로 나타난 이상이나 철학을 표현하는 상징을 사용한다.”고 되어 있고, 표어 Citius, Altius, Fortius(“더 빨리, 더 높게, 더 힘차게”)처럼 ‘분투·향상’을 강조하는 상징들이 그 철학을 시각적으로 드러낸다. (오륜기는 대륙의 연대와 보편성을, 성화는 전통과 연속성을 상징하는 등 문서의 설명이 있음.)\n\n- 올림픽 선서: 문서에 “쿠베르탱의 이상은 올림픽 선서에 더 잘 나타나 있다.”고 직접 명시되어 있으며, 선서의 핵심 구절로 “인생에서 가장 중요한 것은 승리가 아니라 이를 위해 분투하는 것이고, 올림픽에서 가장 중요한 것 역시 승리가 아니라 참가 자체에 의의가 있다. 우리에게 있어 본질은 정복하는 것이 아니라 잘 싸우는 것이다.”가 제시되어 있다. 즉 선서는 쿠베르탱이 강조한 ‘참가·분투·페어플레이’의 가치를 분명히 드러낸다.\n\n- 영국 공립학교의 이념과의 연관성: 문서에 따르면 “영국 명문 공립 학교의 이념은 쿠베르탱에게 큰 영향을 끼쳤다.”고 되어 있다. 그 이념은 mens sana in corpore sano(건전한 신체에 건전한 정신), 신사가 여러 분야에서 골고루 우수해야 한다는 관념, 공정한 결과에 승복하는 태도, 연습이나 전문 훈련을 속임수로 여기는 아마추어 정신 등으로 설명된다. 이러한 가치관이 쿠베르탱의 ‘참가·품성·아마추어리즘·페어플레이’ 중심의 올림픽 이상 형성에 기여했다는 연결이 문서에 제시되어 있다.\n\n요약하면, 쿠베르탱의 이상은(참가·분투·페어플레이 중심) 올림픽의 표어·기·성화 등 상징과 올림픽 선서에 구체적으로 반영되어 있으며, 그 근간에는 영국 공립학교의 ‘건전한 신체에 건전한 정신’과 아마추어적·도덕적 스포츠관이 자리잡고 있다는 점이 문서에 의해 설명되어 있다.',
 '컨텍스트에 따르면 다음과 같이 반영되어 있습니다.\n\n- 영국 공립 학교 이념이 쿠베르탱에게 큰 영향을 주었음  \n  - 그 이념은 스포츠를 교육의 중요한 부분으로 보고 "건전한 신체에 건전한 정신(mens sana in corpore sano)"을 표어로 삼았으며, 신사로서 모든 분야에서 고르게 잘해야 하고 공정한 결과에 승복해야 하며, 전문적 연습(프로화)은 아마추어에게 불공평하다고 여김. 쿠베르탱은 이 영향을 받아 올림픽 이상을 수립했다는 내용이 나옵니다.\n\n- 올림픽 상징(문구 및 선서)에 쿠베르탱의 이상이 드러남  \n  - 올림픽 표어인 라틴어 Citius, Altius, Fortius("더 빨리, 더 높게, 더 힘차게")가 제시되어 있음.  \n  - 특히 "쿠베르탱의 이상은 올림픽 선서에 더 잘 나타나 있다"라고 명시되어 있고, 선서의 핵심 문구가 인용되어 있음: "인생에서 가장 중요한 것은 승리가 아니라 이를 위해 분투하는 것이고, 올림픽에서 가장 중요한 것 역시 승리가 아니라 참가 자체에 의의가 있다. 우리에게 있어 본질은 정복하는 것이 아니라 잘 싸우는 것이다."\n\n따라서 쿠베르탱의 이상은 영국 공립 학교의 교육·아마추어·페어플레이 정신을 바탕으로 올림픽의 표어와 특히 올림픽 선서(참가와 분투를 중시하는 메시지)에 반영되어 있습니다.',
 '정보제공 목적에 따라 주어진 문맥만으로 답변합니다.\n\n1) 쿠베르탱의 이상이 올림픽 선서와 영국 공립학교 이념에 반영된 방식\n- 올림픽 선서: 문맥에 따르면 "쿠베르탱의 이상은 올림픽 선서에 더 잘 나타나 있다."라고 명시되어 있으며, 선서 내용은 "인생에서 가장 중요한 것은 승리가 아니라 이를 위해 분투하는 것이고, 올림픽에서 가장 중요한 것 역시 승리가 아니라 참가 자체에 의의가 있다. 우리에게 있어 본질은 정복하는 것이 아니라 잘 싸우는 것이다."라는 문구로 요약된다. 즉, 경쟁에서의 승리보다 정정당당한 경쟁과 참가 그 자체, 투쟁의 과정(페어플레이·노력)을 중시하는 가치가 선서에 반영되어 있다.\n- 영국 공립학교 이념의 영향: 문맥은 쿠베르탱이 영국 명문 공립학교의 이념에 큰 영향을 받았다고 밝힌다. 그 이념은 "mens sana in corpore sano(건전한 신체에 건전한 정신)"로 요약되며, 신사(gentleman)는 특정 분야에만 특출하지 않고 모든 분야에서 균형 있게 뛰어나야 하고 공정한 결과에 승복해야 하며, 전문적으로 훈련·연습한 사람은 취미로 하는 사람에 비해 공평하지 않다고 보는 아마추어 정신을 강조한다. 이러한 관점이 쿠베르탱의 이상으로 이어져 올림픽 이념에 반영되었다.\n\n2) 이러한 철학이 올림픽의 상징과 규정에 미친 영향\n- 상징 측면: 문맥에 제시된 올림픽 상징들(올림픽 표어 Citius, Altius, Fortius; 올림픽 선서; 올림픽 성화 및 플래그 등)은 쿠베르탱의 이상과 연관된다. 특히 표어와 선서는 \'더 빨리, 더 높게, 더 힘차게\'라는 경쟁적 이상과 동시에 선서가 강조하는 참가·투쟁의 가치를 표현한다. 또한 올림픽 성화·깃발 등은 고대와의 연계 및 보편성(깃발 색은 거의 모든 국기의 색을 포괄함)을 통해 올림픽의 철학적·문화적 상징성을 드러낸다(문맥에 의한 서술).\n- 규정(아마추어 정신) 측면: 문맥은 쿠베르탱적 아마추어 정신이 올림픽의 규정에 직접적인 영향을 미쳐 오랫동안 프로 선수의 출전을 금지하는 정책으로 이어졌음을 보여준다. 그 결과로 발생한 사례들이 문맥에 제시된다.\n  - 짐 소프(짐 소프)는 올림픽 이전 준프로 활동이 밝혀져 메달이 박탈되었다가(나중에 1983년 복권) 파문이 일어났다.\n  - 1936년 동계 올림픽에서 스위스·오스트리아 스키선수들이 돈을 벌기 위해 경기한 것이 아마추어 정신 위배로 간주되어 참가를 금지당했다는 사례가 있다.\n  - IOC는 오랫동안 아마추어 정신을 고수했으나, 1970년대 이후 규정 변화가 논의되었고 최종적으로는 전문 선수 허용 여부를 국제경기연맹(IF)에서 결정하도록 바뀌었다.\n  - 그 결과로 종목별로 차등적 변화가 생겼고(예: 프로 NHL 선수들의 아이스하키 출전은 1998년부터 허용), 2008년 기준으로는 복싱만이 아마추어 선수만 출전하는 종목으로 남아 있고 남자 축구는 23세 초과 선수 제한(3명) 같은 제한 규정을 둔 상태임이 문맥에 명시되어 있다.\n\n요약\n- 쿠베르탱의 이상은 \'참가와 투쟁의 가치, 페어플레이, 균형 있는 인격(건전한 신체와 정신)\'을 중시하는 것으로 문맥에 나타나며, 이는 올림픽 선서와 표어 등 상징적 요소들에 반영되었다.\n- 동일한 철학은 올림픽 규정, 특히 오랜 기간 유지된 아마추어 규정을 형성·유지하게 했고, 이로 인해 구체적 사건(메달 박탈, 출전 금지 등)과 이후 규정 변경(종목별 프로 허용, IF 권한 부여 등)이 발생했다.\n\n주어진 문맥 외의 추가 정보는 제공하지 않았습니다.']

In [24]:
retrieved_context_list

[['올림픽에서는 올림픽 헌장에 구체적으로 나타난 이상이나 철학을 표현하는 상징을 사용한다. 오륜기로 잘 알려져 있는 올림픽기는 5개의 둥근 고리가 얽혀있으며 각 원마다 5대륙을 상징한다.(남아메리카와 북아메리카는 아메리카로 합쳐 있다.) 파랑, 노랑, 검정, 초록, 빨간 고리에 흰색 바탕은 올림픽 기를 나타낸다. 이 색들이 선택된 이유는 모든 국기에서 적어도 이 5개의 색 중 하나를 가지고 있기 때문이다. 올림픽 기가 채택된 것은 1914년이지만 1920년 하계 올림픽 때부터 사용되기 시작했다. 이 때부터 올림픽 기는 올림픽을 기념하기 위해 올림픽이 열리는 기간 동안 게양한다.  \n올림픽 표어는 라틴어로 Citius, Altius, Fortius이며 "더 빨리, 더 높게, 더 힘차게"라는 뜻이다. 쿠베르탱의 이상은 올림픽 선서에 더 잘 나타나 있다.  \n- 올림픽 선서 중에서\n- "인생에서 가장 중요한 것은 승리가 아니라 이를 위해 분투하는 것이고, 올림픽에서 가장 중요한 것 역시 승리가 아니라 참가 자체에 의의가 있다. 우리에게 있어 본질은 정복하는 것이 아니라 잘 싸우는 것이다."  \n매 올림픽이 시작되기 몇 개월전에 고대 그리스에서 제사를 지냈던 그리스의 올림피아에서 올림픽 성화가 채화된다. 여자 배우가 마치 여자 사제인 것처럼 연기해서 태양광선을 포물면 거울(오목 거울의 하나)의 안쪽에 집중시켜서 점화한다. 그 후에 여자는 첫 번째 성화 봉송 주자에게 성화를 넘기고 개최도시의 개막식이 열리는 올림픽 경기장까지 여러 사람의 손을 거쳐서 올림픽 성화는 전달된다. 올림픽 상징으로서의 올림픽 성화는 1928년 하계 올림픽 때 이미 있었지만, 성화 봉송은 1936년 하계 올림픽때 독일 정부의 나치즘 선전의 일환으로 처음 시행된 것이 그 유래이다.  \n개최도시의 문화적 상징물을 동물이나 사람의 형상으로 나타내는 올림픽 마스코트는 1968년에 처음 소개되었다. 이후 1980년 하계 올림픽 때 러시아 아기곰인 미샤가 국제적인 스타의 자리에 오르며, 올림픽의 상징에 있어 마스코트가 한층 더 중요한 역할을 하게 되었다. 가장 최근의 하계 올림픽 마스코트는 2012 런던 올림픽의 마스코트인 웬록으로, 웬록은 영국 중서부 슈롭셔의 작은 마을 이름이며 이곳은 근대 올림픽 창시자인 쿠베르탱이 올림픽을 창안했던 곳이다. 또한 가장 최근의 동계 올림픽 마스코트로는 2010년 동계 올림픽의 마스코트인 미가, 콰치, 수미가 있다.',
  "국제 올림픽 위원회(이하 IOC로 지칭)는 몇몇 위원들이 한 행위에 대해서 비판을 받고 있다. 그 예로 IOC 위원장이었던 에이버리 브런디지와 후안 안토니오 사마란치가 대표적인 사람이다. 브런디지는 20년 넘게 IOC 위원장직을 맡았고 임기 중에 올림픽을 정치적으로 휘말려들지 않게 하기 위해 보호했다. 그러나 그는 남아프리카 공화국 대표단에게 아파르트헤이트와 관련된 이슈를 건드리고 반유대정책을 함으로써 비난을 받았다. 사마란치 위원장 시기 때는 족벌 정치와 부패로 비난받았다. 사마란치가 스페인에서 프랑코 정권에 협력했다는 것도 비판의 이유가 되었다.  \n1998년에 몇몇 IOC위원들이 2002년 솔트레이크 시티 동계 올림픽 유치 과정에서 미국에게 미국을 올림픽 개최지로 뽑아달라는 뇌물청탁을 받았다는 것이 폭로되었다. 이에 IOC는 사퇴한 IOC위원 4명과 강제 퇴출된 6명에 대한 조사를 했다. 이 스캔들은 이후에 개최지 선정에서 이와 같은 불미스러운 일이 일어나지 않게 하기 위해서 IOC가 개혁에 착수하도록 하는 긍정적인 역할을 하기도 했다.  \nBBC 다큐멘터리인 '파노라마'에서는 '매수된 올림픽'이란 주제로 2004년 8월에 방송을 내보내기도 했다. 이때 이 프로그램에서는 2012년 하계 올림픽의 개최지 선정과 관련된 뇌물에 대해서 조사했다. 이 다큐멘터리에서는 특정 후보 도시가 IOC 위원들에게 뇌물수수하는 것이 가능했다고 주장했으며, 특히 파리 시장이었던 베르트랑 들라노에(Bertrand Delanoë)는 영국의 총리인 토니 블레어와 런던올림픽유치위원회가 입후보 규정을 위반했다고 비난했다. 그는 당시 프랑스 대통령이었던 자크 시라크를 목격자로 내세웠지만 시라크 대통령은 이 분쟁에 휘말려드는 것을 주의했으며 인터뷰를 삼갔다. 결국 베르트랑 들라노에의 주장에 대한 조사는 체계적으로 이루어지지는 않았다. 2006년 동계 올림픽을 유치했던 토리노도 이 논쟁에서 빠져나갈 수 없었다. 이번에는 스위스 국적의 IOC위원 마크 호들러(Marc Hodler)가 이 논쟁의 중심이 되었는데, 이 위원은 스위스 시온의 경쟁 도시였던 토리노가 IOC위원들에게 뇌물수수를 했다고 말했고, 이 발언으로 광범위한 조사가 이루어졌다. 이 언행이 많은 IOC위원들이 시온에 대해 언짢게 생각하게 되고 토리노가 개최지로 선정되도록 도와주는 역할을 했을 가능성도 제기되고 있다.",
  '쿠베르탱의 생각과는 달리, 올림픽이 세계에 완벽한 평화를 가져다주지는 못했다. 실제로 제1차 세계대전으로 인해 독일 베를린에서 열리기로 했던 제6회 1916년 하계 올림픽이 취소되었고, 제2차 세계대전 때는 일본 도쿄에서 열리기로 했던 제12회 1940년 하계 올림픽, 삿포로에서 열리기로 했던 1940년 동계 올림픽, 영국 런던에서 열리기로 했던 제13회 1944년 하계 올림픽, 이탈리아 코르티나담페초에서 열릴 예정인 1944년 동계 올림픽이 취소되었다. 베이징에서 열린 2008년 하계 올림픽 개막식날 조지아와 러시아 간의 2008년 남오세티아 전쟁이 일어나기도 했다. 부시 대통령과 푸틴 대통령이 이 올림픽을 보러 왔으며 중국 주석인 후진타오가 주최한 오찬에 참석해서 이 현안에 대해 논의하기도 했다. 조지아 대표인 니노 살루크바체와 러시아 대표인 나탈리야 파데리나가 여자 10m 공기권총 경기에서 각각 동메달과 은메달을 땄을 때 이 일은 베이징 올림픽의 유명한 사건 중 하나로 남게 되었다. 살루크바체와 파데리나는 시상식이 끝난 뒤 서로 포옹을 하며 국적에 상관없이 기쁨을 나누었다.  \n테러도 올림픽에서 공포의 대상이었다. 뮌헨 참사로 알려진 1972년에 서독 바이에른의 뮌헨에서 열린 하계 올림픽때의 사건은 테러리스트인 검은 9월단이 일으킨 사건으로서 이스라엘 선수 11명을 인질로 붙잡았다가 전원이 사망한 사건이다. 당시 미숙한 진압으로 인해 인질 9명(선수 1명과 코치 1명은 인질로 잡기 이전에 살해), 테러범 5명, 독일 경찰관 1명이 사망했으며 이 진압 작전 이전에는 인질들은 단 한 명도 죽지 않았다. 애틀랜타에서 열린 1996년 하계 올림픽 때는 센테니얼 올림픽 공원(Centennial Olympic Park)에서 폭발 사건이 일어나 2명이 죽고 111명이 다치는 사건이 발생했다. 이 사건의 주모자 에릭 로버트 루돌프는 종신형을 선고받았다. 참고로 마라톤 역시 전쟁에서 유래한 것이다.',
  '올림픽 활동이란 많은 수의 국가, 국제 경기 연맹과 협회 • 미디어 파트너를 맺기 • 선수, 직원, 심판, 모든 사람과 기관이 올림픽 헌장을 지키는 것을 말한다.국제올림픽위원회(IOC)는 모든 올림픽 활동을 통솔하는 단체로서, 올림픽 개최 도시 선정, 계획 감독, 종목 변경, 스폰서 및 방송권 계약 체결 등의 권리가 있다. 올림픽 활동은 크게 세 가지로 구성된다.  \n- 국제경기연맹(IF)은 국제적인 규모의 경기를 관리, 감독하는 기구이다. 예를 들어서 국제 축구 연맹(FIFA)는 축구를 주관하며, 국제 배구 연맹(FIVB)은 배구를 주관하는 기구이다. 올림픽에는 현재 35개의 국제경기연맹이 있고 각 종목을 대표한다. (이 중에는 올림픽 종목은 아니지만 IOC의 승인을 받은 연맹도 있다.)\n- 국가 올림픽 위원회(NOC)는 각국의 올림픽 활동을 감독하는 기구이다. 예를 들어서 대한 올림픽 위원회(KOC)는 대한민국의 국가 올림픽 위원회이다. 현재 IOC에 소속된 국가 올림픽 위원회는 205개이다.\n- 올림픽 조직 위원회(OCOG)는 임시적인 조직으로 올림픽의 총체적인 것(개막식, 페막식 등)을 책임지기 위해 구성된 조직이다. 올림픽 조직 위원회는 올림픽이 끝나면 해산되며 최종보고서를 IOC에 제출한다.  \n올림픽의 공식언어는 프랑스어와 영어와 개최국의 공용어이다. 모든 선언(예를 들어서 개막식 때 각국 소개를 할 때)들은 세 언어가 모두 나오거나 영어나 프랑스어 중에서 한 언어로만 말하기도 한다. 개최국의 공용어가 영어나 프랑스어가 아닐 때는 당연히 그 나라의 공용어도 함께 나온다.',
  "올림픽에서 이루어지는 주요 행사로는 개막식, 폐막식, 시상식 등이 있다.  \n#### 개막식  \n개막식 때는 올림픽 헌장에 따라 다양한 행사가 열린다. 개막식의 기본 토대는 벨기에 안트베르펜에서 열린 1920년 하계 올림픽 때 만들어졌다. 개막식은 대개 개최국의 국기가 게양되고 국가가 울려퍼지며 시작된다. 그 후에 개최국이 준비한 그들의 문화를 대표하는 음악, 춤, 영상 따위가 공연된다. 개막식은 아름답기가 매회가 지날수록 웅대해지고 복잡해지는데, 이는 전 대회보다 사람들의 기억에 오래도록 남기기 위함이다. 보도에 의하면 2008 베이징 올림픽 개막식 때 든 비용은 1억 달러로 그 대부분이 예술적인 부분에 들었다고 한다.  \n행사가 끝나면 다음에는 각국의 선수단이 입장한다. 올림픽의 발상지라는 영예를 가진 그리스가 전통적으로 맨 처음에 입장한다. 나머지 각국 선수단은 주최국에서 선택한 언어의 사전 순으로 입장하고 나서, 개최국 선수단이 제일 마지막에 입장한다. 그리스 아테네에서 열린 2004년 하계 올림픽에서는 그리스 국기가 맨 처음에 입장하고, 그리스 선수단이 맨 마지막에 입장했다. 개막식 마지막에는 올림픽 성화가 들어오고 마지막 성화 봉송자에게 전달할 때까지 돌게 된다. 마지막 성화 봉송자는 대체로 유명하고 올림픽에서 성공한 개최국의 선수가 하며 올림픽 성화를 경기장 내에 점화한다. 그 다음 올림픽조직위원장과 IOC 위원장이 개막 선언을 하는데 공식적으로 개막되었다는 것과 올림픽 성화가 점화되는 것을 선언한다. 그 다음에 올림픽조직위원장과 IOC 위원장이 개회사를 낭독하게 된다. 마자막으로 올림픽기 게양에 이어 올림픽 선서를 끝으로 개막식 과정은 모두 끝나게 된다. 2020년 하계 올림픽 이후로는 그리스 - 난민 올림픽 선수단 - 나머지 각국 선수단 - 차차기 올림픽 개최국 - 차기 올림픽 개최국 - 개최국 순서대로 입장한다.  \n#### 폐막식  \n폐막식은 올림픽 경기가 모두 끝난 후에 열린다. 각국의 기수가 경기장에 들어온 후에 국적에 상관없이 모든 선수들이 함께 들어온다. 3개의 기가 국가가 울려퍼지는 동안 게양되는데, 그 3개의 국기는 그리스의 국기(올림픽의 발상지임을 기념하기 위해), 개최도시의 국기, 다음 하계·동계 올림픽의 개최도시의 국기이다. 그 다음 올림픽조직위원장과 IOC 위원장이 폐막 선언을 하는데 공식적으로 폐막되었다는 것과 올림픽 성화가 꺼지는 것을 선언한다. 일명 '안트베르펜 세레모니'라고 하는 것도 진행되는데, 이는 올림픽 개최도시의 수장이 특별한 올림픽 기를 IOC 위원장에게 넘겨주면 그것을 또다시 다음 대회의 개최도시의 수장에게 넘겨주는 것으로서 1920 안트베르펜 올림픽 때부터 시작한 것으로 알려져 있다. 이 행사가 끝나면 짧게 다음 대회 개최지에 대한 소개로 홍보 영상이나 퍼포먼스가 진행된다.  \n#### 시상식  \n시상식은 각 종목이 끝날 때마다 열린다. 개인 혹은 팀으로 참가해서 1위를 하거나 2위 혹은 3위를 한 선수(들)은 시상대에 올라서서 존경의 뜻으로 메달을 수여받는다. 올림픽 위원들에게 메달을 받은 후에 1위를 한 선수의 국가가 울려퍼지고 1, 2, 3위를 한 선수들의 국기가 올라간다. 개최도시의 자원봉사자들도 시상식 때 활동하는데 메달을 준비하거나 꽃을 들고 이동하는 것과 같은 일을 한다. 올림픽 종목마다 시상식은 대체로 그 종목의 결승전(본선)이 끝난 후 거의 하루 뒤에 이루어진다. 남자 마라톤의 경우에는 시작은 올림픽 마지막 날 아침 일찍 하고 시상식은 그 날 저녁에 폐막식 도중에 이루어진다."],
 ['1859년 자파스 올림픽에 참가한 선수의 수는 250명을 넘지 못했다. 에방겔리스 자파스는 "지난 자파스 올림픽을 포함, 1896년에 개최될 2번째 올림픽을 위해 파나티네코 경기장을 보수해야 한다."라는 충고를 하지만, 그리스 정부는 그의 말을 듣지 않았고 결국 1896년 아테네 올림픽 준비를 위해 파나티네코 경기장은 두 번이나 정비해야 했다. 1회 대회 정식종목으로는 9종목이 있었는데 육상, 사이클, 펜싱, 체조, 사격, 수영, 테니스, 역도, 레슬링이 있었으며, 조정도 정식종목이었으나 매우 나쁜 날씨로 인해 조정 경기는 취소되었다. 펜싱 경기는 역사적 건물인 자피온(에반젤리스 자파스의 이름을 딴 것이다)에서 열렸다. 그리스의 관리들과 국민들은 올림픽 경기 개최에 열광적이었다. 많은 선수들이 이에 동감하면서 앞으로도 올림픽 대회를 아테네에서 영구히 개최해야 한다고 요구하기까지 하였다. 그러나 국제올림픽위원회(IOC)는 근대 올림픽은 순환 개최로 열리는 세계적인 행사가 되어야 한다고 생각했다. 결국 2회 올림픽은 프랑스 파리에서 열기로 결정되었다.  \n#### 변화와 발전  \n1896년 올림픽 대회의 성공을 이어서 개최된 두 번째 올림픽인 1900년 올림픽에서는 올림픽의 존폐여부를 위협받는 지경에 이르게 되었다. 1900년에 파리와 1904년에 세인트루이스에서 열린 올림픽은 하필이면 엑스포와 시간과 장소가 겹치는 바람에 빛을 바래게 된다. 1904년 대회를 예로 들면 650명의 선수단이 참가했지만 그중 580명은 미국국적을 가진 사람이었다. 1900년과 1904년의 두 올림픽 대회는 역대 올림픽중에 최저점을 기록한다. 올림픽은 1906년 올림픽이 아테네에서 개최되었을 때 다시 일어서게 된다. 또 다른 성공적인 올림픽은 그리스 올림픽 협회가 조직했으며 세 차례나 올림픽을 치른 경기장에서 개최되었다. 이 경기는 비공식 올림픽이긴 했지만 세계적으로 상당한 참가자들을 불러 모았으며 대중들에게 큰 재미를 갖다주었다. 이 때를 시작으로 올림픽의 인기와 번영이 시작되었다.',
  '고대 올림피아 경기를 제대로 구현한 최초의 시도는 혁명 시대의 프랑스에서 1796년부터 1798년까지 3년동안 실시했던 프랑스 국내 올림픽인 \'공화국 올림픽\'(L\'Olympiade de la République)이었다. 이 대회의 종목 중에는 고대 그리스 올림피아 경기 때 행한 일부 종목도 있었다. 특히 1798년 공화국 올림픽 대회는 미터법을 최초로 스포츠에 도입시킨 대회이기도 하다. 이후 52년뒤인 1850년에는 잉글랜드 슈롭셔주의 웬록에서 올림픽급의 대회가 열리기 시작하였다. 이 대회는 1859년에 아테네에서 열렸을 때 웬록 올림픽으로 명칭이 변경되었으며 지금도 열리고 있다. 브룩스 박사는 1859년에 아테네에서 열린 올림픽 경기의 내용을 이후 경기에 채택하였다. 1866년 런던의 수정궁에서는 윌리엄 페니 브룩스가 영국의 국가 올림픽 대회를 만들었다.  \n1821년 그리스에서는 오스만 제국의 지배에 반기를 들고 독립 전쟁이 일어나면서, 이때부터 올림픽 부활에 대한 관심이 생겨났다. 시인이자 신문 편집자였던 파나요티스 수초스(Παναγιώτης Σούτσος)는 1833년에 출간한 자신의 시 \'망자(亡者)의 대화\'에서 최초로 올림픽 부활에 대한 제안을 내놓았다. 그리스의 부유한 박애주의자였던 에방겔리스 자파스(Ευαγγέλης Ζάππας)는 1859년에 아테네 시 광장에서 열린 "올림픽 경기(일명 자파스 올림픽)"를 후원하였다. 이 경기에는 그리스와 오스만 제국 출신의 선수들이 참가하였다. 에방겔리스 자파스는 이후에도 올림픽 경기를 개최할 수 있도록 고대의 경기장이었던 파나티네코 경기장을 복원하는 데도 돈을 썼다. 파나티네코 경기장에서 1870년과 1875년에 자파스 올림픽을 개최했으며, 현대 올림픽인 2004년 하계 올림픽 때는 양궁 경기장으로도 쓰였다.  \n역사학자였던 쿠베르탱은 프로이센-프랑스 전쟁(1870–1871)에서 프랑스의 패배 원인을 분석하면서 군사들이 체계적인 체력 훈련을 받지 않았기 때문에 전쟁에서 패배했다고 말한 인물이다. 1890년 웬록 올림픽에 참석한 쿠베르탱은 그 이후부터 올림픽을 대규모로 부활시킬 수 있으리라 생각했다. 쿠베르탱은 웬록 올림픽과 자파스 올림픽을 토대로 하여 올림픽 경기를 국제적으로 시행하기 위해 나라별로 올림픽을 번갈아가며 개최하는 방식을 생각해냈다. 그는 이 방안을 새로 설립된 국제 올림픽 위원회(IOC)의 첫 올림픽 의회 기간 중에 언급했다. 총회는 파리의 소르본 대학교에서 1894년 6월 16일부터 6월 23일까지 7일간 지속되었으며, 총회 마지막날, 2년 후인 1896년에 아테네에서 국제적 규모의 올림픽 대회를 열기로 결정되었다. IOC는 올림픽을 조직하는 데에 모든 책임을 졌으며, 초대 위원장으로는 그리스의 작가였던 디미트리오스 비켈라스(Δημήτριος Βικέλας)가 선출되었다.',
  '고대의 올림픽 경기(올림피아 경기)는 고대 그리스의 여러 도시 국가의 대표선수들이 모여 벌인 일련의 시합이었으며, 육상 경기가 주 종목이지만 격투기와 전차 경기도 열렸다. 그리고 패배하면 죽기도 하였다. 고대 올림픽의 유래는 수수께끼로 남아있다. 잘 알려진 신화로는 헤라클레스와 그의 아버지인 제우스가 올림픽의 창시자였다는 것이다. 전설에 따르면 이 경기를 최초로 \'올림픽\'이라고 부르고, 4년마다 대회를 개최하는 관례를 만든 사람이 헤라클레스라고 한다. 어떤 전설에서는 헤라클레스가 이른바 헤라클레스의 12업을 달성한 뒤에 제우스를 기리고자 올림픽 경기장을 지었다고 한다. 경기장이 완성되자 헤라클레스는 일직선으로 200 걸음을 걸었으며, 이 거리를 "스타디온"이라 불렀는데, 후에 이것이 길이 단위인 \'스타디온\'(그리스어: στάδιον → 라틴어: 영어: stadium)이 되었다. 또 다른 설로는 \'올림픽 휴전\'(그리스어: ἐκεχειρία 에케케이리아[*])이라는 고대 그리스의 관념이 최초의 올림피아 경기와 관련이 있다고 한다. \'올림픽 휴전\'이란 어느 도시 국가라도 올림피아 경기 기간 중에 다른 나라를 침범하면 그에 대한 응징을 받을 수 있다는 뜻으로, "올림픽 기간에는 전쟁하지 말 것"으로 요약할 수 있다.  \n고대 올림피아 경기가 처음 열린 시점은 보통 기원전 776년으로 인정되고 있는데, 이 연대는 그리스 올림피아에서 발견된 비문에 근거를 둔 것이다. 이 비문의 내용은 달리기 경주 승자 목록이며 기원전 776년부터 4년 이후 올림피아 경기 마다의 기록이 남겨져 있다. 고대 올림픽의 종목으로는 육상, 5종 경기(원반던지기, 창던지기, 달리기, 레슬링, 멀리뛰기), 복싱, 레슬링, 승마 경기가 있었다. 전설에 따르면 엘리스의 코로이보스가 최초로 올림피아 경기에서 우승한 사람이라고 한다.  \n고대 올림피아 경기는 근본적으로 종교적인 중요성을 띄고 있었는데, 스포츠 경기를 할 때는 제우스(올림피아의 제우스 신전에는 페이디아스가 만든 제우스 상이 있음)와 펠롭스를 기리기 위하여 제물 봉헌 의식을 치렀다. 펠롭스는 올림피아의 전설상의 임금이었던 피사티스의 오이노마오스 왕과 전차 경주를 겨룬 영웅으로 유명한 인물이다. 올림피아 경기의 승자는 시와 조각상으로 칭송받았다. 올림피아 경기는 4년마다 열렸으며, 이 기간을 \'올림피아드\'(Olympiad)라고 했는데, 그리스인들은 이를 시간 단위로 이용하였다. 올림피아 경기는 고대 그리스에서 정기적으로 열렸던 범그리스 대회의 순환 대회 가운데 하나였다.  \n올림피아 경기는 기원전 6세기~기원전 5세기에 절정에 이르렀으나, 그 후 로마가 패권을 잡은 뒤 그리스에 영향력을 행사하면서 서서히 쇠퇴하게 된다. 고대 올림픽이 공식적으로 끝난 해는 확실히 알 수 없으나, 대부분 테오도시우스 1세 황제가 모든 이단 숭배 및 예배를 금지했던 393년을 고대 올림픽의 마지막이라고 추정한다. 다른 설에 따르면 테오도시우스의 후계자인 테오도시우스 2세가 모든 그리스 신전을 파괴하라고 명령한 426년이라고도 한다. 이렇게 올림픽이 사라진 이후로 이보다 한참 뒤인 19세기에 이르러서야 비로소 다시 올림픽 경기가 열리게 된다.',
  '쿠베르탱의 생각과는 달리, 올림픽이 세계에 완벽한 평화를 가져다주지는 못했다. 실제로 제1차 세계대전으로 인해 독일 베를린에서 열리기로 했던 제6회 1916년 하계 올림픽이 취소되었고, 제2차 세계대전 때는 일본 도쿄에서 열리기로 했던 제12회 1940년 하계 올림픽, 삿포로에서 열리기로 했던 1940년 동계 올림픽, 영국 런던에서 열리기로 했던 제13회 1944년 하계 올림픽, 이탈리아 코르티나담페초에서 열릴 예정인 1944년 동계 올림픽이 취소되었다. 베이징에서 열린 2008년 하계 올림픽 개막식날 조지아와 러시아 간의 2008년 남오세티아 전쟁이 일어나기도 했다. 부시 대통령과 푸틴 대통령이 이 올림픽을 보러 왔으며 중국 주석인 후진타오가 주최한 오찬에 참석해서 이 현안에 대해 논의하기도 했다. 조지아 대표인 니노 살루크바체와 러시아 대표인 나탈리야 파데리나가 여자 10m 공기권총 경기에서 각각 동메달과 은메달을 땄을 때 이 일은 베이징 올림픽의 유명한 사건 중 하나로 남게 되었다. 살루크바체와 파데리나는 시상식이 끝난 뒤 서로 포옹을 하며 국적에 상관없이 기쁨을 나누었다.  \n테러도 올림픽에서 공포의 대상이었다. 뮌헨 참사로 알려진 1972년에 서독 바이에른의 뮌헨에서 열린 하계 올림픽때의 사건은 테러리스트인 검은 9월단이 일으킨 사건으로서 이스라엘 선수 11명을 인질로 붙잡았다가 전원이 사망한 사건이다. 당시 미숙한 진압으로 인해 인질 9명(선수 1명과 코치 1명은 인질로 잡기 이전에 살해), 테러범 5명, 독일 경찰관 1명이 사망했으며 이 진압 작전 이전에는 인질들은 단 한 명도 죽지 않았다. 애틀랜타에서 열린 1996년 하계 올림픽 때는 센테니얼 올림픽 공원(Centennial Olympic Park)에서 폭발 사건이 일어나 2명이 죽고 111명이 다치는 사건이 발생했다. 이 사건의 주모자 에릭 로버트 루돌프는 종신형을 선고받았다. 참고로 마라톤 역시 전쟁에서 유래한 것이다.',
  '올림픽에서는 올림픽 헌장에 구체적으로 나타난 이상이나 철학을 표현하는 상징을 사용한다. 오륜기로 잘 알려져 있는 올림픽기는 5개의 둥근 고리가 얽혀있으며 각 원마다 5대륙을 상징한다.(남아메리카와 북아메리카는 아메리카로 합쳐 있다.) 파랑, 노랑, 검정, 초록, 빨간 고리에 흰색 바탕은 올림픽 기를 나타낸다. 이 색들이 선택된 이유는 모든 국기에서 적어도 이 5개의 색 중 하나를 가지고 있기 때문이다. 올림픽 기가 채택된 것은 1914년이지만 1920년 하계 올림픽 때부터 사용되기 시작했다. 이 때부터 올림픽 기는 올림픽을 기념하기 위해 올림픽이 열리는 기간 동안 게양한다.  \n올림픽 표어는 라틴어로 Citius, Altius, Fortius이며 "더 빨리, 더 높게, 더 힘차게"라는 뜻이다. 쿠베르탱의 이상은 올림픽 선서에 더 잘 나타나 있다.  \n- 올림픽 선서 중에서\n- "인생에서 가장 중요한 것은 승리가 아니라 이를 위해 분투하는 것이고, 올림픽에서 가장 중요한 것 역시 승리가 아니라 참가 자체에 의의가 있다. 우리에게 있어 본질은 정복하는 것이 아니라 잘 싸우는 것이다."  \n매 올림픽이 시작되기 몇 개월전에 고대 그리스에서 제사를 지냈던 그리스의 올림피아에서 올림픽 성화가 채화된다. 여자 배우가 마치 여자 사제인 것처럼 연기해서 태양광선을 포물면 거울(오목 거울의 하나)의 안쪽에 집중시켜서 점화한다. 그 후에 여자는 첫 번째 성화 봉송 주자에게 성화를 넘기고 개최도시의 개막식이 열리는 올림픽 경기장까지 여러 사람의 손을 거쳐서 올림픽 성화는 전달된다. 올림픽 상징으로서의 올림픽 성화는 1928년 하계 올림픽 때 이미 있었지만, 성화 봉송은 1936년 하계 올림픽때 독일 정부의 나치즘 선전의 일환으로 처음 시행된 것이 그 유래이다.  \n개최도시의 문화적 상징물을 동물이나 사람의 형상으로 나타내는 올림픽 마스코트는 1968년에 처음 소개되었다. 이후 1980년 하계 올림픽 때 러시아 아기곰인 미샤가 국제적인 스타의 자리에 오르며, 올림픽의 상징에 있어 마스코트가 한층 더 중요한 역할을 하게 되었다. 가장 최근의 하계 올림픽 마스코트는 2012 런던 올림픽의 마스코트인 웬록으로, 웬록은 영국 중서부 슈롭셔의 작은 마을 이름이며 이곳은 근대 올림픽 창시자인 쿠베르탱이 올림픽을 창안했던 곳이다. 또한 가장 최근의 동계 올림픽 마스코트로는 2010년 동계 올림픽의 마스코트인 미가, 콰치, 수미가 있다.'],
 ['올림픽 활동이란 많은 수의 국가, 국제 경기 연맹과 협회 • 미디어 파트너를 맺기 • 선수, 직원, 심판, 모든 사람과 기관이 올림픽 헌장을 지키는 것을 말한다.국제올림픽위원회(IOC)는 모든 올림픽 활동을 통솔하는 단체로서, 올림픽 개최 도시 선정, 계획 감독, 종목 변경, 스폰서 및 방송권 계약 체결 등의 권리가 있다. 올림픽 활동은 크게 세 가지로 구성된다.  \n- 국제경기연맹(IF)은 국제적인 규모의 경기를 관리, 감독하는 기구이다. 예를 들어서 국제 축구 연맹(FIFA)는 축구를 주관하며, 국제 배구 연맹(FIVB)은 배구를 주관하는 기구이다. 올림픽에는 현재 35개의 국제경기연맹이 있고 각 종목을 대표한다. (이 중에는 올림픽 종목은 아니지만 IOC의 승인을 받은 연맹도 있다.)\n- 국가 올림픽 위원회(NOC)는 각국의 올림픽 활동을 감독하는 기구이다. 예를 들어서 대한 올림픽 위원회(KOC)는 대한민국의 국가 올림픽 위원회이다. 현재 IOC에 소속된 국가 올림픽 위원회는 205개이다.\n- 올림픽 조직 위원회(OCOG)는 임시적인 조직으로 올림픽의 총체적인 것(개막식, 페막식 등)을 책임지기 위해 구성된 조직이다. 올림픽 조직 위원회는 올림픽이 끝나면 해산되며 최종보고서를 IOC에 제출한다.  \n올림픽의 공식언어는 프랑스어와 영어와 개최국의 공용어이다. 모든 선언(예를 들어서 개막식 때 각국 소개를 할 때)들은 세 언어가 모두 나오거나 영어나 프랑스어 중에서 한 언어로만 말하기도 한다. 개최국의 공용어가 영어나 프랑스어가 아닐 때는 당연히 그 나라의 공용어도 함께 나온다.',
  '올림픽(영어: Olympic Games, 프랑스어: Jeux olympiques)은 전 세계 각 대륙 각국에서 모인 수천 명의 선수가 참가해 여름과 겨울에 스포츠 경기를 하는 국제적인 대회이다. 전 세계에서 가장 큰 지구촌 최대의 스포츠 축제인 올림픽은 세계에서 가장 인지도있는 국제 행사이다. 올림픽은 2년마다 하계 올림픽과 동계 올림픽이 번갈아 열리며, 국제 올림픽 위원회(IOC)가 감독하고 있다. 또한 오늘날의 올림픽은 기원전 8세기부터 서기 5세기에 이르기까지 고대 그리스 올림피아에서 열렸던 올림피아 제전에서 비롯되었다. 그리고 19세기 말에 피에르 드 쿠베르탱 남작이 고대 올림피아 제전에서 영감을 얻어, 근대 올림픽을 부활시켰다. 이를 위해 쿠베르탱 남작은 1894년에 IOC를 창설했으며, 2년 뒤인 1896년에 그리스 아테네에서 제 1회 올림픽이 열렸다. 이때부터 IOC는 올림픽 운동의 감독 기구가 되었으며, 조직과 활동은 올림픽 헌장을 따른다. 오늘날 전 세계 대부분의 국가에서 올림픽 메달은 매우 큰 영예이며, 특히 올림픽 금메달리스트는 국가 영웅급의 대우를 받으며 스포츠 스타가 된다. 국가별로 올림픽 메달리스트들에게 지급하는 포상금도 크다. 대부분의 인기있는 종목들이나 일상에서 쉽게 접하고 즐길 수 있는 생활스포츠 종목들이 올림픽이라는 한 대회에서 동시에 열리고, 전 세계 대부분의 국가 출신의 선수들이 참여하는 만큼 전 세계 스포츠 팬들이 가장 많이 시청하는 이벤트이다. 2008 베이징 올림픽의 모든 종목 누적 시청자 수만 47억 명에 달하며, 이는 인류 역사상 가장 많은 수의 인구가 시청한 이벤트였다.  \n또한 20세기에 올림픽 운동이 발전함에 따라, IOC는 변화하는 세계의 사회 환경에 적응해야 했다. 이러한 변화의 예로는 얼음과 눈을 이용한 경기 종목을 다루는 동계 올림픽, 장애인이 참여하는 패럴림픽, 스페셜 올림픽, 데플림픽, 10대 선수들이 참여하는 유스 올림픽 등을 들 수 있다. 그 뿐만 아니라 IOC는 20세기의 변화하는 경제, 정치, 기술 환경에도 적응해야 했다. 그리하여 올림픽은 피에르 드 쿠베르탱이 기대했던 순수한 아마추어 정신에서 벗어나서, 프로 선수도 참가할 수 있게 되었다. 올림픽은 점차 대중 매체의 중요성이 커짐에 따라 올림픽의 상업화와 기업 후원을 놓고도 논란이 생겨났다. 또한 올림픽을 치르며 발생한 보이콧, 도핑, 심판 매수, 테러와 같은 수많은 일들은 올림픽이 더욱 굳건히 성장할 수 있는 원동력이 되었다.  \n올림픽은 국제경기연맹(IF), 국가 올림픽 위원회(NOC), 각 올림픽의 위원회(예-벤쿠버동계올림픽조직위원회)로 구성된다. 의사 결정 기구인 IOC는 올림픽 개최 도시를 선정하며, 각 올림픽 대회마다 열리는 올림픽 종목도 IOC에서 결정한다. 올림픽 경기 개최 도시는 경기 축하 의식이 올림픽 헌장에 부합하도록 조직하고 기금을 마련해야 한다. 올림픽 축하 행사로는 여러 의식과 상징을 들 수 있는데 올림픽기나 성화가 그 예이다.  \n올림픽은 거의 모든 국가가 참여할 정도로 규모가 커졌다. 하계 올림픽은 33개의 종목과 약 400개의 세부종목에서 13,000명이 넘는 선수들이 겨루고 그중 각 종목별 1, 2, 3위는 각각 금/은/동을 수여받는다. 전 세계 언론에서 각각 4년마다 열리는 올림픽 경기를 중계하기 때문에 이름 없는 선수가 개인적, 국가적, 세계적으로 명성을 얻을 수 있는 기회가 된다. 이와 더불어 올림픽 경기는 개최지와 개최국에게도 전 세계에 그 이름을 널리 알리는 좋은 기회가 된다.',
  "1950년대까지 IOC는 적은 예산으로 운영되어 왔다. 에이버리 브런디지가 위원장으로 있던 1952년부터 1972년까지, 에이버리 브런디지는 그 어떤 상업적인 관심도 올림픽과 연계를 꾀하는 것을 거부했다. 협력 스폰서의 관심이 IOC의 결정에 지나치게 간섭할 우려가 있다고 생각했기 때문이다. 브런디지가 이러한 수익창출을 거부했다는 것은 IOC가 스폰서 계약이나 올림픽 상징의 사용에 대한 협상을 포기했다는 뜻이다. 브런디지가 IOC에 200만 달러를 남기고 은퇴한 후 8년 뒤에 IOC의 잔고는 4500만 달러로 늘어났다. 그 이유는 IOC가 처음으로 텔레비전 중계권을 판매하고 스폰서와 계약함으로써 올림픽의 팽창을 노리는 이데올로기(관념)의 변화가 있었기 때문이다. 1980년에 IOC위원장으로 후안 안토니오 사마란치가 당선되었을 때, 그의 소원이 IOC의 재정적 독립이었을 정도로 상업성에 대한 시각도 많이 달라졌다.  \n1984년 하계 올림픽은 올림픽 역사에 있어서 획기적인 순간이었다. 피터 워버로스(Peter Ueberroth)의 지휘하에 있던 LA 하계 올림픽 조직위원회는 그 당시 2억 2500만 달러라는 전례가 없던 이익을 얻었다. 왜냐하면 조직위원회는 독점스폰서에 대한 권리를 판매하였고 그로 인해 이익을 창출할 수 있었기 때문이다. IOC는 이러한 재정적 후원 권리를 통제하기 위한 방법을 강구했다. 1년 뒤인 1985년 사마란치 IOC 위원장은 올림픽 브랜드를 만들어내기 위한 '올림픽 프로그램(The Olympic Program, TOP)'을 설립했다. TOP의 회원들은 '독점'적이고, '비싼 비용'을 IOC에 지불해야만 한다. 4년마다 TOP 회원들은 5000만 달러를 내야 한다. 그 대가로 TOP의 회원은 생산하는 물품에 올림픽 상징인 오륜기를 국제적, 독점적으로 사용하고 출판물이나 광고에도 이용할 수 있는 혜택을 누리게 된다.",
  "올림픽 경기 종목은 총 33개부문 52개 종목에서 약 400개의 경기로 이루어져있다. 예를 들어서 하계 올림픽 부문인 레슬링은 자유형과 그레코로만형의 두 종목으로 나뉜다. 여기에서 10경기는 남자부, 4경기는 여자부로 열리며 분류기준은 체중이다. 하계 올림픽은 26개, 동계 올림픽은 7개 부문으로 이루어져있다. 하계 올림픽에서는 육상, 수영, 펜싱, 체조가 1회 대회때부터 한번도 빠짐없이 정식종목이었으며, 동계 올림픽에서는 크로스컨트리, 피겨 스케이팅, 아이스 하키, 노르딕 복합, 스키 점프, 스피드 스케이팅이 1924년 동계 올림픽부터 빠짐없이 정식종목이었다. 배드민턴, 농구, 배구와 같은 정식종목들은 처음에는 시범종목이었으며 그 후에 정식종목으로 승인 되었다. 야구처럼 예전에는 정식종목 이었지만 지금은 정식 종목에서 빠진 종목도 있다.  \n각 올림픽 종목들은 IOC로부터 승인을 받은 국제경기연맹의 관리를 받는다. 35개의 연맹이 IOC에서 승인을 받았으며, 승인을 받았지만 현재 정식종목이 아닌 종목을 감독하는 연맹도 있다. IOC의 승인을 받았지만 올림픽 종목이 아닌 스포츠들은 올림픽 종목으로 고려되지는 않으나, 올림픽이 끝난 후 처음으로 열리는 IOC총회 때마다 정식종목이 되도록 신청을 할 수는 있다. IOC 총회 때 정식종목 선정은 총회에 참석중인 IOC위원들의 투표를 통해 이루어지며, 재적 위원 수의 과반수 이상 찬성표를 얻어야 정식종목으로 인정을 받는다. IOC의 승인을 받은 스포츠이나 찬성표를 받지 못해 정식종목이 되지 못한 스포츠로는 체스와 서핑과 같은 것이 있다.  \n2004년 10월과 11월에 IOC는 '올림픽 프로그램 위원회'(Olympic Programme Commission)를 설립했다. 여기서는 올림픽 종목과 올림픽 종목이 아닌 스포츠를 모두 재검토하는 일을 한다. 이 위원회의 목표는 올림픽 종목에 더 체계적으로 다가가는 것이다. 위원회에서는 우선적으로 올림픽 종목으로 포함되기 위해서는 7개의 기준을 충족시켜야 한다고 말한다. 이 7개의 기준은 역사, 전통, 보편성, 인기도와 잠재성, 선수의 건강, 연맹의 스포츠를 관리할만한 능력, 스포츠를 여는 데에 필요한 비용이다. 예를 들면 2012년 하계 올림픽의 정식종목 후보에 7개 조건을 포함한 비(非)올림픽 스포츠가 올랐고 그 내용은, 골프, 가라테, 럭비, 인라인 스케이팅, 스쿼시였다. 이 스포츠들은 IOC 상임이사회에서 재검토되어 2005년 7월에 열린 싱가포르 총회에서 최종 결정하기로 했다. 결국 5개 중 2개(가라테와 스쿼시) 가 최종 후보로 올라왔으나 가라테와 스쿼시 둘 다 2/3의 미만의 찬성표로 정식종목이 되지는 못한다. 그 후 2016년 올림픽 정식종목에는 7개의 스포츠가 정식종목 신청을 했는데, 내용은 가라테, 골프, 스쿼시, 야구, 소프트볼, 7인제 럭비, 인라인 스케이팅이었다. 2009년 8월 13일, 신청된 7개의 스포츠 중 단 2개만 최종후보로 선정되었는데, 이는 7인제 럭비와 골프였다. 같은해인 2009년 10월에 열린 IOC 총회에서 골프와 럭비는 과반수 이상의 득표를 얻어서 2016년 하계 올림픽과 2020년 하계 올림픽의 정식종목으로 채택되었다.  \n2002년에 열린 제114차 IOC 총회에서는 하계 올림픽 종목은 최대 28부문 301개 경기에 10,500명이 참가하는 것으로 제한하기로 결정했다. 그 후 3년 뒤인 제117차 IOC 총회에서는 정식종목이었던 야구와 소프트볼을 정식 종목에서 제외시킨다. 이 결과에 대한 이견이 없었으므로 2012년 올림픽 때는 26개부문에서 경기가 열린다. 2016년과 2020년 올림픽 때는 럭비와 골프가 추가되어 다시 28개부문에서 경기가 열린다.",
  '올림픽에서는 올림픽 헌장에 구체적으로 나타난 이상이나 철학을 표현하는 상징을 사용한다. 오륜기로 잘 알려져 있는 올림픽기는 5개의 둥근 고리가 얽혀있으며 각 원마다 5대륙을 상징한다.(남아메리카와 북아메리카는 아메리카로 합쳐 있다.) 파랑, 노랑, 검정, 초록, 빨간 고리에 흰색 바탕은 올림픽 기를 나타낸다. 이 색들이 선택된 이유는 모든 국기에서 적어도 이 5개의 색 중 하나를 가지고 있기 때문이다. 올림픽 기가 채택된 것은 1914년이지만 1920년 하계 올림픽 때부터 사용되기 시작했다. 이 때부터 올림픽 기는 올림픽을 기념하기 위해 올림픽이 열리는 기간 동안 게양한다.  \n올림픽 표어는 라틴어로 Citius, Altius, Fortius이며 "더 빨리, 더 높게, 더 힘차게"라는 뜻이다. 쿠베르탱의 이상은 올림픽 선서에 더 잘 나타나 있다.  \n- 올림픽 선서 중에서\n- "인생에서 가장 중요한 것은 승리가 아니라 이를 위해 분투하는 것이고, 올림픽에서 가장 중요한 것 역시 승리가 아니라 참가 자체에 의의가 있다. 우리에게 있어 본질은 정복하는 것이 아니라 잘 싸우는 것이다."  \n매 올림픽이 시작되기 몇 개월전에 고대 그리스에서 제사를 지냈던 그리스의 올림피아에서 올림픽 성화가 채화된다. 여자 배우가 마치 여자 사제인 것처럼 연기해서 태양광선을 포물면 거울(오목 거울의 하나)의 안쪽에 집중시켜서 점화한다. 그 후에 여자는 첫 번째 성화 봉송 주자에게 성화를 넘기고 개최도시의 개막식이 열리는 올림픽 경기장까지 여러 사람의 손을 거쳐서 올림픽 성화는 전달된다. 올림픽 상징으로서의 올림픽 성화는 1928년 하계 올림픽 때 이미 있었지만, 성화 봉송은 1936년 하계 올림픽때 독일 정부의 나치즘 선전의 일환으로 처음 시행된 것이 그 유래이다.  \n개최도시의 문화적 상징물을 동물이나 사람의 형상으로 나타내는 올림픽 마스코트는 1968년에 처음 소개되었다. 이후 1980년 하계 올림픽 때 러시아 아기곰인 미샤가 국제적인 스타의 자리에 오르며, 올림픽의 상징에 있어 마스코트가 한층 더 중요한 역할을 하게 되었다. 가장 최근의 하계 올림픽 마스코트는 2012 런던 올림픽의 마스코트인 웬록으로, 웬록은 영국 중서부 슈롭셔의 작은 마을 이름이며 이곳은 근대 올림픽 창시자인 쿠베르탱이 올림픽을 창안했던 곳이다. 또한 가장 최근의 동계 올림픽 마스코트로는 2010년 동계 올림픽의 마스코트인 미가, 콰치, 수미가 있다.'],

In [25]:
# eval_df 에 추가
eval_df['response'] = response_list
eval_df['retrieved_contexts'] = retrieved_context_list
eval_df.head()

,user_input,reference_contexts,reference,persona_name,query_style,query_length,synthesizer_name,response,retrieved_contexts
0,2012 런던 올림픽 마스코트 뭐에요?,[올림픽에서는 올림픽 헌장에 구체적으로 나타난 이상이나 철학을 표현하는 상징을 사용...,"2012 런던 올림픽의 마스코트는 웬록으로, 웬록은 영국 중서부 슈롭셔의 작은 마을...",Olympic Enthusiast,MISSPELLED,SHORT,single_hop_specific_query_synthesizer,2012 런던 올림픽 마스코트는 웬록(웬록)입니다.,[올림픽에서는 올림픽 헌장에 구체적으로 나타난 이상이나 철학을 표현하는 상징을 사용...
1,파나티네코 경기장은 1896년 아테네 올림픽을 준비하는 과정에서 어떤 역할을 했으며...,[1859년 자파스 올림픽에 참가한 선수의 수는 250명을 넘지 못했다. 에방겔리스...,에방겔리스 자파스는 1896년에 개최될 2번째 올림픽을 위해 파나티네코 경기장을 보...,Olympic Enthusiast,PERFECT_GRAMMAR,LONG,single_hop_specific_query_synthesizer,Context에 따르면 파나티네코 경기장은 고대 경기장을 복원한 장소로서 근대 올림...,[1859년 자파스 올림픽에 참가한 선수의 수는 250명을 넘지 못했다. 에방겔리스...
2,올림픽 프로그람 커미션은 뭐하는 기구에요?,[올림픽 경기 종목은 총 33개부문 52개 종목에서 약 400개의 경기로 이루어져있...,올림픽 프로그램 위원회는 올림픽 종목과 올림픽 종목이 아닌 스포츠를 모두 재검토하는...,Olympic History Enthusiast,MISSPELLED,MEDIUM,single_hop_specific_query_synthesizer,"정보가 주어진 내용에 따르면, 올림픽 프로그램 위원회(Olympic Programm...","[올림픽 활동이란 많은 수의 국가, 국제 경기 연맹과 협회 • 미디어 파트너를 맺기..."
3,1936년 하계 올림픽의 방송 관련 특징은 무엇인가요?,[베를린에서 열렸던 1936년 하계 올림픽은 전 세계가 아닌 독일 내에서만의 방송이...,베를린에서 열렸던 1936년 하계 올림픽은 전 세계가 아닌 독일 내에서만의 방송이지...,Olympic Enthusiast,WEB_SEARCH_LIKE,SHORT,single_hop_specific_query_synthesizer,1936년 베를린 하계 올림픽은 텔레비전으로 방송된 첫 번째 올림픽이었으나 전 세계...,[베를린에서 열렸던 1936년 하계 올림픽은 전 세계가 아닌 독일 내에서만의 방송이...
4,"NHL 선수들 언제부터 올림픽 아이스 하키에 나갈 수 있었는지, 그리고 그거랑 올림...",[프로 NHL선수들은 1998년부터 아이스 하키종목에 출전할 수 있게 되었다. (나...,프로 NHL선수들은 1998년부터 아이스 하키종목에 출전할 수 있게 되었다. 현대 ...,Olympic History Enthusiast,POOR_GRAMMAR,LONG,single_hop_specific_query_synthesizer,- 언제부터: 프로 NHL 선수들은 1998년 나가노 동계올림픽부터 아이스하키 종목...,[프로 NHL선수들은 1998년부터 아이스 하키종목에 출전할 수 있게 되었다. (나...

In [26]:
################################################################
# EvaluationDataset을 생성 -> RAGAS 평가 데이터셋 타입
################################################################
from ragas import EvaluationDataset
# from_xxxx() xxxx 타입의 객체를 EvaluationDataset객체로 변환.
eval_dataset = EvaluationDataset.from_pandas(
    eval_df[["user_input", "retrieved_contexts", "response", "reference"]]
)
eval_dataset

EvaluationDataset(features=['user_input', 'retrieved_contexts', 'response', 'reference'], len=11)

In [27]:
##########################
# 평가
##########################
from ragas.metrics import (
    LLMContextRecall, # Context Recall 평가함수
    LLMContextPrecisionWithReference, # Context Precision
    Faithfulness, 
    AnswerRelevancy
)

from ragas import evaluate

eval_llm = LangchainLLMWrapper(ChatOpenAI(model="gpt-4.1"))
eval_embeddings = LangchainEmbeddingsWrapper(OpenAIEmbeddings(model="text-embedding-3-large"))
# 평가할 함수들을 List로 묶어준다.
metrics = [
    LLMContextRecall(llm=eval_llm),
    LLMContextPrecisionWithReference(llm=eval_llm),
    Faithfulness(llm=eval_llm),
    AnswerRelevancy(llm=eval_llm, embeddings=eval_embeddings)
]

# 평가를 진행 - evaluate() 함수 이용
eval_result = evaluate(dataset=eval_dataset, metrics=metrics)

C:\Users\82107\AppData\Local\Temp\ipykernel_356236\1589191573.py:4: DeprecationWarning: Importing LLMContextRecall from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import LLMContextRecall
  from ragas.metrics import (
C:\Users\82107\AppData\Local\Temp\ipykernel_356236\1589191573.py:4: DeprecationWarning: Importing LLMContextPrecisionWithReference from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import LLMContextPrecisionWithReference
  from ragas.metrics import (
C:\Users\82107\AppData\Local\Temp\ipykernel_356236\1589191573.py:4: DeprecationWarning: Importing Faithfulness from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import Faithfulness
  from ragas.metrics import (
C:\Users\82107\AppData\Local\Temp\ipykernel_356236\1589191573.py:4: DeprecationWarning: Importing AnswerRelevancy from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import AnswerRelevancy
  from ragas.metrics import (
C:\Users\82107\AppData\Local\Temp\ipykernel_356236\1589191573.py:13: DeprecationWarning: LangchainLLMWrapper is deprecated and will be removed in a future version. Use llm_factory instead: from openai import OpenAI; from ragas.llms import llm_factory; llm = llm_factory('gpt-4o-mini', client=OpenAI(api_key='...'))
  eval_llm = LangchainLLMWrapper(ChatOpenAI(model="gpt-4.1"))
C:\Users\82107\AppData\Local\Temp\ipykernel_356236\1589191573.py:14: DeprecationWarning: LangchainEmbeddingsWrapper is deprecated and will be removed in a future version. Use the modern embedding providers instead: embedding_factory('openai', model='text-embedding-3-small', client=openai_client) or from ragas.embeddings import OpenAIEmbeddings, GoogleEmbeddings, HuggingFaceEmbeddings
  eval_embeddings = LangchainEmbeddingsWrapper(OpenAIEmbeddings(model="text-embedding-3-large"))

Evaluating:   0%|          | 0/44 [00:00<?, ?it/s]

LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Exception raised in Job[13]: APIConnectionError(Connection error.)
Exception raised in Job[1]: TimeoutError()
Exception raised in Job[5]: TimeoutError()
Exception raised in Job[9]: TimeoutError()
Exception raised in Job[32]: APIConnectionError(Connection error.)
Exception raised in Job[26]: APIConnectionError(Connection error.)
Exception raised in Job[36]: APIConnectionError(Connection error.)
Exception raised in Job[21]: TimeoutError()
Exception raised in Job[24]: TimeoutError()
Exception raised in Job[18]: TimeoutError()
Exception raised in Job[22]: TimeoutError()
Exception raised in Job[25]: TimeoutError()
Exception raised in Job[29]: TimeoutError()
Exception raised in Job[34]: TimeoutError()

In [28]:
print(type(eval_result))
eval_result

<class 'ragas.dataset_schema.EvaluationResult'>

{'context_recall': 0.9583, 'llm_context_precision_with_reference': 0.9167, 'faithfulness': 0.9464, 'answer_relevancy': 0.7656}

In [29]:
# 개별 Point에 대한 평가 결과.
result_df = eval_result.to_pandas()
result_df

,user_input,retrieved_contexts,response,reference,context_recall,llm_context_precision_with_reference,faithfulness,answer_relevancy
0,2012 런던 올림픽 마스코트 뭐에요?,[올림픽에서는 올림픽 헌장에 구체적으로 나타난 이상이나 철학을 표현하는 상징을 사용...,2012 런던 올림픽 마스코트는 웬록(웬록)입니다.,"2012 런던 올림픽의 마스코트는 웬록으로, 웬록은 영국 중서부 슈롭셔의 작은 마을...",1.000000,NaN,1.000000,0.884268
1,파나티네코 경기장은 1896년 아테네 올림픽을 준비하는 과정에서 어떤 역할을 했으며...,[1859년 자파스 올림픽에 참가한 선수의 수는 250명을 넘지 못했다. 에방겔리스...,Context에 따르면 파나티네코 경기장은 고대 경기장을 복원한 장소로서 근대 올림...,에방겔리스 자파스는 1896년에 개최될 2번째 올림픽을 위해 파나티네코 경기장을 보...,1.000000,NaN,1.000000,0.759145
2,올림픽 프로그람 커미션은 뭐하는 기구에요?,"[올림픽 활동이란 많은 수의 국가, 국제 경기 연맹과 협회 • 미디어 파트너를 맺기...","정보가 주어진 내용에 따르면, 올림픽 프로그램 위원회(Olympic Programm...",올림픽 프로그램 위원회는 올림픽 종목과 올림픽 종목이 아닌 스포츠를 모두 재검토하는...,1.000000,NaN,1.000000,0.767043
3,1936년 하계 올림픽의 방송 관련 특징은 무엇인가요?,[베를린에서 열렸던 1936년 하계 올림픽은 전 세계가 아닌 독일 내에서만의 방송이...,1936년 베를린 하계 올림픽은 텔레비전으로 방송된 첫 번째 올림픽이었으나 전 세계...,베를린에서 열렸던 1936년 하계 올림픽은 전 세계가 아닌 독일 내에서만의 방송이지...,1.000000,NaN,1.000000,0.737697
4,"NHL 선수들 언제부터 올림픽 아이스 하키에 나갈 수 있었는지, 그리고 그거랑 올림...",[프로 NHL선수들은 1998년부터 아이스 하키종목에 출전할 수 있게 되었다. (나...,- 언제부터: 프로 NHL 선수들은 1998년 나가노 동계올림픽부터 아이스하키 종목...,프로 NHL선수들은 1998년부터 아이스 하키종목에 출전할 수 있게 되었다. 현대 ...,1.000000,0.833333,NaN,0.702586
5,1936년 하계 올림픽이 텔레비전으로 방송된 첫 번째 올림픽이었다는 점과 이후 올림...,[베를린에서 열렸던 1936년 하계 올림픽은 전 세계가 아닌 독일 내에서만의 방송이...,정보 출처에 따른 답변은 다음과 같습니다.\n\n- 1936년 베를린 올림픽은 독일...,1936년 하계 올림픽은 독일 내에서만이었지만 텔레비전으로 방송된 첫 번째 올림픽이...,1.000000,NaN,NaN,0.737517
6,1960년 동계 올림픽이 중계권을 특정 방송사에 처음으로 판매한 올림픽이었다고 하는...,[베를린에서 열렸던 1936년 하계 올림픽은 전 세계가 아닌 독일 내에서만의 방송이...,문맥에 따르면 1960년 동계 올림픽이 중계권을 특정 방송사에 처음으로 판매한 것은...,1960년 동계 올림픽은 중계권을 어느 특정한 방송사에 판매한 첫 번째 올림픽이었습...,NaN,NaN,NaN,0.858931
7,1960년 동계 올림픽 중계권 팔앗던거랑 그 이후 텔레비전 시청자수 증가랑 무슨 관...,[베를린에서 열렸던 1936년 하계 올림픽은 전 세계가 아닌 독일 내에서만의 방송이...,문맥에 따르면 다음과 같이 관계가 설명되어 있습니다.\n\n- 1960년 동계 올림...,1960년 동계 올림픽은 중계권을 어느 특정한 방송사에 판매한 첫 번째 올림픽이었고...,0.666667,NaN,0.909091,0.794861
8,"쿠베르탱의 이상이 올림픽 상징과 올림픽 선서, 그리고 영국 공립 학교의 이념과 어떻...",[올림픽에서는 올림픽 헌장에 구체적으로 나타난 이상이나 철학을 표현하는 상징을 사용...,쿠베르탱의 이상은 맥락에 따르면 ‘참가와 분투(노력)를 중시하고 승리 그 자체를 최...,"쿠베르탱의 이상은 올림픽 선서에 잘 나타나 있는데, 이는 '인생에서 가장 중요한 것...",NaN,0.833333,NaN,0.942758
9,쿠베르탱의 이상이 올림픽 상징과 영국 공립 학교의 이념에 어떻게 반영되어 있나요?,[올림픽에서는 올림픽 헌장에 구체적으로 나타난 이상이나 철학을 표현하는 상징을 사용...,컨텍스트에 따르면 다음과 같이 반영되어 있습니다.\n\n- 영국 공립 학교 이념이 ...,"쿠베르탱의 이상은 올림픽 선서에 잘 나타나 있으며, 이는 '인생에서 가장 중요한 것...",NaN,1.000000,0.750000,0.618841
10,"쿠베르탱의 이상이 올림픽 선서와 영국 공립 학교의 이념에 어떻게 반영되어 있으며, ...",[올림픽에서는 올림픽 헌장에 구체적으로 나타난 이상이나 철학을 표현하는 상징을 사용...,정보제공 목적에 따라 주어진 문맥만으로 답변합니다.\n\n1) 쿠베르탱의 이상이 올...,"쿠베르탱의 이상은 올림픽 선서에 잘 나타나 있는데, 이는 ""인생에서 가장 중요한 것...",1.000000,1.000000,0.965517,0.618016